// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Attributes.Network;

/// <summary>Network Attributes.</summary>
public static class NetworkAttributes
{
    /// <summary>
    /// Local address of the network connection - IP address or Unix domain socket name.
    /// </summary>
    public const string LocalAddress = "network.local.address";

    /// <summary>
    /// Local port number of the network connection.
    /// </summary>
    public const string LocalPort = "network.local.port";

    /// <summary>
    /// Peer address of the network connection - IP address or Unix domain socket name.
    /// </summary>
    public const string PeerAddress = "network.peer.address";

    /// <summary>
    /// Peer port number of the network connection.
    /// </summary>
    public const string PeerPort = "network.peer.port";

    /// <summary>
    /// <a href="https://wikipedia.org/wiki/Application_layer">OSI application layer</a> or non-OSI equivalent.
    /// </summary>
    /// <remarks>
    /// The value SHOULD be normalized to lowercase.
    /// </remarks>
    public const string ProtocolName = "network.protocol.name";

    /// <summary>
    /// The actual version of the protocol used for network communication.
    /// </summary>
    /// <remarks>
    /// If protocol version is subject to negotiation (for example using <a href="https://www.rfc-editor.org/rfc/rfc7301.html">ALPN</a>), this attribute SHOULD be set to the negotiated version. If the actual protocol version is not known, this attribute SHOULD NOT be set.
    /// </remarks>
    public const string ProtocolVersion = "network.protocol.version";

    /// <summary>
    /// <a href="https://wikipedia.org/wiki/Transport_layer">OSI transport layer</a> or <a href="https://wikipedia.org/wiki/Inter-process_communication">inter-process communication method</a>.
    /// </summary>
    /// <remarks>
    /// The value SHOULD be normalized to lowercase.
    /// <p>
    /// Consider always setting the transport when setting a port number, since
    /// a port number is ambiguous without knowing the transport. For example
    /// different processes could be listening on TCP port 12345 and UDP port 12345.
    /// </remarks>
    public const string Transport = "network.transport";

    /// <summary>
    /// Values for the <c>Transport</c> attribute.
    /// </summary>
    public static class TransportValues
    {
        /// <summary>
        /// Named or anonymous pipe.
        /// </summary>
        public const string Pipe = "pipe";

        /// <summary>
        /// QUIC.
        /// </summary>
        public const string Quic = "quic";

        /// <summary>
        /// TCP.
        /// </summary>
        public const string Tcp = "tcp";

        /// <summary>
        /// UDP.
        /// </summary>
        public const string Udp = "udp";

        /// <summary>
        /// Unix domain socket.
        /// </summary>
        public const string Unix = "unix";
    }

    /// <summary>
    /// <a href="https://wikipedia.org/wiki/Network_layer">OSI network layer</a> or non-OSI equivalent.
    /// </summary>
    /// <remarks>
    /// The value SHOULD be normalized to lowercase.
    /// </remarks>
    public const string Type = "network.type";

    /// <summary>
    /// Values for the <c>Type</c> attribute.
    /// </summary>
    public static class TypeValues
    {
        /// <summary>
        /// IPv4.
        /// </summary>
        public const string Ipv4 = "ipv4";

        /// <summary>
        /// IPv6.
        /// </summary>
        public const string Ipv6 = "ipv6";
    }
}
