// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Artifact;

/// <summary>Artifact Attributes (incubating).</summary>
public static class ArtifactAttributes
{
    /// <summary>The provenance filename of the built attestation which directly relates to the build artifact filename. This filename SHOULD accompany the artifact at publish time. See the [SLSA Relationship](https://slsa.dev/spec/v1.0/distributing-provenance#relationship-between-artifacts-and-attestations) specification for more information..</summary>
    public const string AttestationFilename = "artifact.attestation.filename";

    /// <summary>The full [hash value (see glossary)](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf), of the built attestation. Some envelopes in the [software attestation space](https://github.com/in-toto/attestation/tree/main/spec) also refer to this as the **digest**..</summary>
    public const string AttestationHash = "artifact.attestation.hash";

    /// <summary>The id of the build [software attestation](https://slsa.dev/attestation-model)..</summary>
    public const string AttestationId = "artifact.attestation.id";

    /// <summary>The human readable file name of the artifact, typically generated during build and release processes. Often includes the package name and version in the file name..</summary>
    /// <remarks>This file name can also act as the [Package Name](https://slsa.dev/spec/v1.0/terminology#package-model) in cases where the package ecosystem maps accordingly. Additionally, the artifact [can be published](https://slsa.dev/spec/v1.0/terminology#software-supply-chain) for others, but that is not a guarantee.</remarks>
    public const string Filename = "artifact.filename";

    /// <summary>The full [hash value (see glossary)](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf), often found in checksum.txt on a release of the artifact and used to verify package integrity..</summary>
    /// <remarks>The specific algorithm used to create the cryptographic hash value is not defined. In situations where an artifact has multiple cryptographic hashes, it is up to the implementer to choose which hash value to set here; this should be the most secure hash algorithm that is suitable for the situation and consistent with the corresponding attestation. The implementer can then provide the other hash values through an additional set of attribute extensions as they deem necessary.</remarks>
    public const string Hash = "artifact.hash";

    /// <summary>The [Package URL](https://github.com/package-url/purl-spec) of the [package artifact](https://slsa.dev/spec/v1.0/terminology#package-model) provides a standard way to identify and locate the packaged artifact..</summary>
    public const string Purl = "artifact.purl";

    /// <summary>The version of the artifact..</summary>
    public const string Version = "artifact.version";

}