// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Peer;

/// <summary>Peer Attributes (incubating).</summary>
public static class PeerAttributes
{
    /// <summary>The [`service.name`](/docs/resource/README.md#service) of the remote service. SHOULD be equal to the actual `service.name` resource attribute of the remote service if any..</summary>
    /// <remarks>Examples of `peer.service` that users may specify:  - A Redis cache of auth tokens as `peer.service="AuthTokenCache"`. - A gRPC service `rpc.service="io.opentelemetry.AuthService"` may be hosted in both a gateway, `peer.service="ExternalApiService"` and a backend, `peer.service="AuthService"`.</remarks>
    [global::System.Obsolete("Replaced by service.peer.name.", false)]
    public const string Service = "peer.service";

}