// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@7fe537301d17919af7d7eb65b32e9be35da2c497
// Schema: https://opentelemetry.io/schemas/1.40.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Aws;

/// <summary>Aws Attributes (incubating).</summary>
public static class AwsAttributes
{
    /// <summary>The unique identifier of the AWS Bedrock Guardrail. A [guardrail](https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails.html) helps safeguard and prevent unwanted behavior from model responses or user messages..</summary>
    public const string BedrockGuardrailId = "aws.bedrock.guardrail.id";

    /// <summary>The unique identifier of the AWS Bedrock Knowledge base. A [knowledge base](https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base.html) is a bank of information that can be queried by models to generate more relevant responses and augment prompts..</summary>
    public const string BedrockKnowledgeBaseId = "aws.bedrock.knowledge_base.id";

    /// <summary>The JSON-serialized value of each item in the `AttributeDefinitions` request field..</summary>
    public const string DynamodbAttributeDefinitions = "aws.dynamodb.attribute_definitions";

    /// <summary>The value of the `AttributesToGet` request parameter..</summary>
    public const string DynamodbAttributesToGet = "aws.dynamodb.attributes_to_get";

    /// <summary>The value of the `ConsistentRead` request parameter..</summary>
    public const string DynamodbConsistentRead = "aws.dynamodb.consistent_read";

    /// <summary>The JSON-serialized value of each item in the `ConsumedCapacity` response field..</summary>
    public const string DynamodbConsumedCapacity = "aws.dynamodb.consumed_capacity";

    /// <summary>The value of the `Count` response parameter..</summary>
    public const string DynamodbCount = "aws.dynamodb.count";

    /// <summary>The value of the `ExclusiveStartTableName` request parameter..</summary>
    public const string DynamodbExclusiveStartTable = "aws.dynamodb.exclusive_start_table";

    /// <summary>The JSON-serialized value of each item in the `GlobalSecondaryIndexUpdates` request field..</summary>
    public const string DynamodbGlobalSecondaryIndexUpdates = "aws.dynamodb.global_secondary_index_updates";

    /// <summary>The JSON-serialized value of each item of the `GlobalSecondaryIndexes` request field.</summary>
    public const string DynamodbGlobalSecondaryIndexes = "aws.dynamodb.global_secondary_indexes";

    /// <summary>The value of the `IndexName` request parameter..</summary>
    public const string DynamodbIndexName = "aws.dynamodb.index_name";

    /// <summary>The JSON-serialized value of the `ItemCollectionMetrics` response field..</summary>
    public const string DynamodbItemCollectionMetrics = "aws.dynamodb.item_collection_metrics";

    /// <summary>The value of the `Limit` request parameter..</summary>
    public const string DynamodbLimit = "aws.dynamodb.limit";

    /// <summary>The JSON-serialized value of each item of the `LocalSecondaryIndexes` request field..</summary>
    public const string DynamodbLocalSecondaryIndexes = "aws.dynamodb.local_secondary_indexes";

    /// <summary>The value of the `ProjectionExpression` request parameter..</summary>
    public const string DynamodbProjection = "aws.dynamodb.projection";

    /// <summary>The value of the `ProvisionedThroughput.ReadCapacityUnits` request parameter..</summary>
    public const string DynamodbProvisionedReadCapacity = "aws.dynamodb.provisioned_read_capacity";

    /// <summary>The value of the `ProvisionedThroughput.WriteCapacityUnits` request parameter..</summary>
    public const string DynamodbProvisionedWriteCapacity = "aws.dynamodb.provisioned_write_capacity";

    /// <summary>The value of the `ScanIndexForward` request parameter..</summary>
    public const string DynamodbScanForward = "aws.dynamodb.scan_forward";

    /// <summary>The value of the `ScannedCount` response parameter..</summary>
    public const string DynamodbScannedCount = "aws.dynamodb.scanned_count";

    /// <summary>The value of the `Segment` request parameter..</summary>
    public const string DynamodbSegment = "aws.dynamodb.segment";

    /// <summary>The value of the `Select` request parameter..</summary>
    public const string DynamodbSelect = "aws.dynamodb.select";

    /// <summary>The number of items in the `TableNames` response parameter..</summary>
    public const string DynamodbTableCount = "aws.dynamodb.table_count";

    /// <summary>The keys in the `RequestItems` object field..</summary>
    public const string DynamodbTableNames = "aws.dynamodb.table_names";

    /// <summary>The value of the `TotalSegments` request parameter..</summary>
    public const string DynamodbTotalSegments = "aws.dynamodb.total_segments";

    /// <summary>The ARN of an [ECS cluster](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/clusters.html)..</summary>
    public const string EcsClusterArn = "aws.ecs.cluster.arn";

    /// <summary>The Amazon Resource Name (ARN) of an [ECS container instance](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_instances.html)..</summary>
    public const string EcsContainerArn = "aws.ecs.container.arn";

    /// <summary>The [launch type](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_types.html) for an ECS task..</summary>
    public const string EcsLaunchtype = "aws.ecs.launchtype";

    /// <summary>Values for <see cref="EcsLaunchtype"/>.</summary>
    public static class EcsLaunchtypeValues
    {
        /// <summary>Amazon EC2.</summary>
        public const string Ec2 = "ec2";
        /// <summary>Amazon Fargate.</summary>
        public const string Fargate = "fargate";
    }

    /// <summary>The ARN of a running [ECS task](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-account-settings.html#ecs-resource-ids)..</summary>
    public const string EcsTaskArn = "aws.ecs.task.arn";

    /// <summary>The family name of the [ECS task definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definitions.html) used to create the ECS task..</summary>
    public const string EcsTaskFamily = "aws.ecs.task.family";

    /// <summary>The ID of a running ECS task. The ID MUST be extracted from `task.arn`..</summary>
    public const string EcsTaskId = "aws.ecs.task.id";

    /// <summary>The revision for the task definition used to create the ECS task..</summary>
    public const string EcsTaskRevision = "aws.ecs.task.revision";

    /// <summary>The ARN of an EKS cluster..</summary>
    public const string EksClusterArn = "aws.eks.cluster.arn";

    /// <summary>The AWS extended request ID as returned in the response header `x-amz-id-2`..</summary>
    public const string ExtendedRequestId = "aws.extended_request_id";

    /// <summary>The name of the AWS Kinesis [stream](https://docs.aws.amazon.com/streams/latest/dev/introduction.html) the request refers to. Corresponds to the `--stream-name` parameter of the Kinesis [describe-stream](https://docs.aws.amazon.com/cli/latest/reference/kinesis/describe-stream.html) operation..</summary>
    public const string KinesisStreamName = "aws.kinesis.stream_name";

    /// <summary>The full invoked ARN as provided on the `Context` passed to the function (`Lambda-Runtime-Invoked-Function-Arn` header on the `/runtime/invocation/next` applicable)..</summary>
    /// <remarks>This may be different from `cloud.resource_id` if an alias is involved.</remarks>
    public const string LambdaInvokedArn = "aws.lambda.invoked_arn";

    /// <summary>The UUID of the [AWS Lambda EvenSource Mapping](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html). An event source is mapped to a lambda function. It's contents are read by Lambda and used to trigger a function. This isn't available in the lambda execution context or the lambda runtime environtment. This is going to be populated by the AWS SDK for each language when that UUID is present. Some of these operations are Create/Delete/Get/List/Update EventSourceMapping..</summary>
    public const string LambdaResourceMappingId = "aws.lambda.resource_mapping.id";

    /// <summary>The Amazon Resource Name(s) (ARN) of the AWS log group(s)..</summary>
    /// <remarks>See the [log group ARN format documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-access-control-overview-cwl.html#CWL_ARN_Format).</remarks>
    public const string LogGroupArns = "aws.log.group.arns";

    /// <summary>The name(s) of the AWS log group(s) an application is writing to..</summary>
    /// <remarks>Multiple log groups must be supported for cases like multi-container applications, where a single application has sidecar containers, and each write to their own log group.</remarks>
    public const string LogGroupNames = "aws.log.group.names";

    /// <summary>The ARN(s) of the AWS log stream(s)..</summary>
    /// <remarks>See the [log stream ARN format documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-access-control-overview-cwl.html#CWL_ARN_Format). One log group can contain several log streams, so these ARNs necessarily identify both a log group and a log stream.</remarks>
    public const string LogStreamArns = "aws.log.stream.arns";

    /// <summary>The name(s) of the AWS log stream(s) an application is writing to..</summary>
    public const string LogStreamNames = "aws.log.stream.names";

    /// <summary>The AWS request ID as returned in the response headers `x-amzn-requestid`, `x-amzn-request-id` or `x-amz-request-id`..</summary>
    public const string RequestId = "aws.request_id";

    /// <summary>The S3 bucket name the request refers to. Corresponds to the `--bucket` parameter of the [S3 API](https://docs.aws.amazon.com/cli/latest/reference/s3api/index.html) operations..</summary>
    /// <remarks>The `bucket` attribute is applicable to all S3 operations that reference a bucket, i.e. that require the bucket name as a mandatory parameter. This applies to almost all S3 operations except `list-buckets`.</remarks>
    public const string S3Bucket = "aws.s3.bucket";

    /// <summary>The source object (in the form `bucket`/`key`) for the copy operation..</summary>
    /// <remarks>The `copy_source` attribute applies to S3 copy operations and corresponds to the `--copy-source` parameter of the [copy-object operation within the S3 API](https://docs.aws.amazon.com/cli/latest/reference/s3api/copy-object.html). This applies in particular to the following operations:  - [copy-object](https://docs.aws.amazon.com/cli/latest/reference/s3api/copy-object.html) - [upload-part-copy](https://docs.aws.amazon.com/cli/latest/reference/s3api/upload-part-copy.html)</remarks>
    public const string S3CopySource = "aws.s3.copy_source";

    /// <summary>The delete request container that specifies the objects to be deleted..</summary>
    /// <remarks>The `delete` attribute is only applicable to the [delete-object](https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-object.html) operation. The `delete` attribute corresponds to the `--delete` parameter of the [delete-objects operation within the S3 API](https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-objects.html).</remarks>
    public const string S3Delete = "aws.s3.delete";

    /// <summary>The S3 object key the request refers to. Corresponds to the `--key` parameter of the [S3 API](https://docs.aws.amazon.com/cli/latest/reference/s3api/index.html) operations..</summary>
    /// <remarks>The `key` attribute is applicable to all object-related S3 operations, i.e. that require the object key as a mandatory parameter. This applies in particular to the following operations:  - [copy-object](https://docs.aws.amazon.com/cli/latest/reference/s3api/copy-object.html) - [delete-object](https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-object.html) - [get-object](https://docs.aws.amazon.com/cli/latest/reference/s3api/get-object.html) - [head-object](https://docs.aws.amazon.com/cli/latest/reference/s3api/head-object.html) - [put-object](https://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html) - [restore-object](https://docs.aws.amazon.com/cli/latest/reference/s3api/restore-object.html) - [select-object-content](https://docs.aws.amazon.com/cli/latest/reference/s3api/select-object-content.html) - [abort-multipart-upload](https://docs.aws.amazon.com/cli/latest/reference/s3api/abort-multipart-upload.html) - [complete-multipart-upload](https://docs.aws.amazon.com/cli/latest/reference/s3api/complete-multipart-upload.html) - [create-multipart-upload](https://docs.aws.amazon.com/cli/latest/reference/s3api/create-multipart-upload.html) - [list-parts](https://docs.aws.amazon.com/cli/latest/reference/s3api/list-parts.html) - [upload-part](https://docs.aws.amazon.com/cli/latest/reference/s3api/upload-part.html) - [upload-part-copy](https://docs.aws.amazon.com/cli/latest/reference/s3api/upload-part-copy.html)</remarks>
    public const string S3Key = "aws.s3.key";

    /// <summary>The part number of the part being uploaded in a multipart-upload operation. This is a positive integer between 1 and 10,000..</summary>
    /// <remarks>The `part_number` attribute is only applicable to the [upload-part](https://docs.aws.amazon.com/cli/latest/reference/s3api/upload-part.html) and [upload-part-copy](https://docs.aws.amazon.com/cli/latest/reference/s3api/upload-part-copy.html) operations. The `part_number` attribute corresponds to the `--part-number` parameter of the [upload-part operation within the S3 API](https://docs.aws.amazon.com/cli/latest/reference/s3api/upload-part.html).</remarks>
    public const string S3PartNumber = "aws.s3.part_number";

    /// <summary>Upload ID that identifies the multipart upload..</summary>
    /// <remarks>The `upload_id` attribute applies to S3 multipart-upload operations and corresponds to the `--upload-id` parameter of the [S3 API](https://docs.aws.amazon.com/cli/latest/reference/s3api/index.html) multipart operations. This applies in particular to the following operations:  - [abort-multipart-upload](https://docs.aws.amazon.com/cli/latest/reference/s3api/abort-multipart-upload.html) - [complete-multipart-upload](https://docs.aws.amazon.com/cli/latest/reference/s3api/complete-multipart-upload.html) - [list-parts](https://docs.aws.amazon.com/cli/latest/reference/s3api/list-parts.html) - [upload-part](https://docs.aws.amazon.com/cli/latest/reference/s3api/upload-part.html) - [upload-part-copy](https://docs.aws.amazon.com/cli/latest/reference/s3api/upload-part-copy.html)</remarks>
    public const string S3UploadId = "aws.s3.upload_id";

    /// <summary>The ARN of the Secret stored in the Secrets Mangger.</summary>
    public const string SecretsmanagerSecretArn = "aws.secretsmanager.secret.arn";

    /// <summary>The ARN of the AWS SNS Topic. An Amazon SNS [topic](https://docs.aws.amazon.com/sns/latest/dg/sns-create-topic.html) is a logical access point that acts as a communication channel..</summary>
    public const string SnsTopicArn = "aws.sns.topic.arn";

    /// <summary>The URL of the AWS SQS Queue. It's a unique identifier for a queue in Amazon Simple Queue Service (SQS) and is used to access the queue and perform actions on it..</summary>
    public const string SqsQueueUrl = "aws.sqs.queue.url";

    /// <summary>The ARN of the AWS Step Functions Activity..</summary>
    public const string StepFunctionsActivityArn = "aws.step_functions.activity.arn";

    /// <summary>The ARN of the AWS Step Functions State Machine..</summary>
    public const string StepFunctionsStateMachineArn = "aws.step_functions.state_machine.arn";

}