// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Messaging;

/// <summary>Messaging Attributes (incubating).</summary>
public static class MessagingAttributes
{
    /// <summary>The number of messages sent, received, or processed in the scope of the batching operation..</summary>
    /// <remarks>Instrumentations SHOULD NOT set `messaging.batch.message_count` on spans that operate with a single message. When a messaging client library supports both batch and single-message API for the same operation, instrumentations SHOULD use `messaging.batch.message_count` for batching APIs and SHOULD NOT use it for single-message APIs.</remarks>
    public const string BatchMessageCount = "messaging.batch.message_count";

    /// <summary>A unique identifier for the client that consumes or produces a message..</summary>
    public const string ClientId = "messaging.client.id";

    /// <summary>The name of the consumer group with which a consumer is associated..</summary>
    /// <remarks>Semantic conventions for individual messaging systems SHOULD document whether `messaging.consumer.group.name` is applicable and what it means in the context of that system.</remarks>
    public const string ConsumerGroupName = "messaging.consumer.group.name";

    /// <summary>A boolean that is true if the message destination is anonymous (could be unnamed or have auto-generated name)..</summary>
    public const string DestinationAnonymous = "messaging.destination.anonymous";

    /// <summary>The message destination name.</summary>
    /// <remarks>Destination name SHOULD uniquely identify a specific queue, topic or other entity within the broker. If the broker doesn't have such notion, the destination name SHOULD uniquely identify the broker.</remarks>
    public const string DestinationName = "messaging.destination.name";

    /// <summary>The identifier of the partition messages are sent to or received from, unique within the `messaging.destination.name`..</summary>
    public const string DestinationPartitionId = "messaging.destination.partition.id";

    /// <summary>The name of the destination subscription from which a message is consumed..</summary>
    /// <remarks>Semantic conventions for individual messaging systems SHOULD document whether `messaging.destination.subscription.name` is applicable and what it means in the context of that system.</remarks>
    public const string DestinationSubscriptionName = "messaging.destination.subscription.name";

    /// <summary>Low cardinality representation of the messaging destination name.</summary>
    /// <remarks>Destination names could be constructed from templates. An example would be a destination name involving a user name or product id. Although the destination name in this case is of high cardinality, the underlying template is of low cardinality and can be effectively used for grouping and aggregation.</remarks>
    public const string DestinationTemplate = "messaging.destination.template";

    /// <summary>A boolean that is true if the message destination is temporary and might not exist anymore after messages are processed..</summary>
    public const string DestinationTemporary = "messaging.destination.temporary";

    /// <summary>Deprecated, no replacement at this time..</summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string DestinationPublishAnonymous = "messaging.destination_publish.anonymous";

    /// <summary>Deprecated, no replacement at this time..</summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string DestinationPublishName = "messaging.destination_publish.name";

    /// <summary>Deprecated, use `messaging.consumer.group.name` instead..</summary>
    [global::System.Obsolete("Replaced by messaging.consumer.group.name.", false)]
    public const string EventhubsConsumerGroup = "messaging.eventhubs.consumer.group";

    /// <summary>The UTC epoch seconds at which the message has been accepted and stored in the entity..</summary>
    public const string EventhubsMessageEnqueuedTime = "messaging.eventhubs.message.enqueued_time";

    /// <summary>The ack deadline in seconds set for the modify ack deadline request..</summary>
    public const string GcpPubsubMessageAckDeadline = "messaging.gcp_pubsub.message.ack_deadline";

    /// <summary>The ack id for a given message..</summary>
    public const string GcpPubsubMessageAckId = "messaging.gcp_pubsub.message.ack_id";

    /// <summary>The delivery attempt for a given message..</summary>
    public const string GcpPubsubMessageDeliveryAttempt = "messaging.gcp_pubsub.message.delivery_attempt";

    /// <summary>The ordering key for a given message. If the attribute is not present, the message does not have an ordering key..</summary>
    public const string GcpPubsubMessageOrderingKey = "messaging.gcp_pubsub.message.ordering_key";

    /// <summary>Deprecated, use `messaging.consumer.group.name` instead..</summary>
    [global::System.Obsolete("Replaced by messaging.consumer.group.name.", false)]
    public const string KafkaConsumerGroup = "messaging.kafka.consumer.group";

    /// <summary>Deprecated, use `messaging.destination.partition.id` instead..</summary>
    [global::System.Obsolete("Record string representation of the partition id in `messaging.destination.partition.id` attribute.", false)]
    public const string KafkaDestinationPartition = "messaging.kafka.destination.partition";

    /// <summary>Message keys in Kafka are used for grouping alike messages to ensure they're processed on the same partition. They differ from `messaging.message.id` in that they're not unique. If the key is `null`, the attribute MUST NOT be set..</summary>
    /// <remarks>If the key type is not string, it's string representation has to be supplied for the attribute. If the key has no unambiguous, canonical string form, don't include its value.</remarks>
    public const string KafkaMessageKey = "messaging.kafka.message.key";

    /// <summary>Deprecated, use `messaging.kafka.offset` instead..</summary>
    [global::System.Obsolete("Replaced by messaging.kafka.offset.", false)]
    public const string KafkaMessageOffset = "messaging.kafka.message.offset";

    /// <summary>A boolean that is true if the message is a tombstone..</summary>
    public const string KafkaMessageTombstone = "messaging.kafka.message.tombstone";

    /// <summary>The offset of a record in the corresponding Kafka partition..</summary>
    public const string KafkaOffset = "messaging.kafka.offset";

    /// <summary>The size of the message body in bytes..</summary>
    /// <remarks>This can refer to both the compressed or uncompressed body size. If both sizes are known, the uncompressed body size should be used.</remarks>
    public const string MessageBodySize = "messaging.message.body.size";

    /// <summary>The conversation ID identifying the conversation to which the message belongs, represented as a string. Sometimes called "Correlation ID"..</summary>
    public const string MessageConversationId = "messaging.message.conversation_id";

    /// <summary>The size of the message body and metadata in bytes..</summary>
    /// <remarks>This can refer to both the compressed or uncompressed size. If both sizes are known, the uncompressed size should be used.</remarks>
    public const string MessageEnvelopeSize = "messaging.message.envelope.size";

    /// <summary>A value used by the messaging system as an identifier for the message, represented as a string..</summary>
    public const string MessageId = "messaging.message.id";

    /// <summary>Deprecated, use `messaging.operation.type` instead..</summary>
    [global::System.Obsolete("Replaced by messaging.operation.type.", false)]
    public const string Operation = "messaging.operation";

    /// <summary>The system-specific name of the messaging operation..</summary>
    public const string OperationName = "messaging.operation.name";

    /// <summary>A string identifying the type of the messaging operation..</summary>
    /// <remarks>If a custom value is used, it MUST be of low cardinality.</remarks>
    public const string OperationType = "messaging.operation.type";

    /// <summary>Values for the <c>OperationType</c> attribute.</summary>
    public static class OperationTypeValues
    {
        /// <summary>A message is created. "Create" spans always refer to a single message and are used to provide a unique creation context for messages in batch sending scenarios..</summary>
        public const string Create = "create";
        /// <summary>Deprecated. Use `process` instead..</summary>
        [global::System.Obsolete("{\"note\": \"Replaced by `process`.\", \"reason\": \"renamed\", \"renamed_to\": \"process\"}", false)]
        public const string Deliver = "deliver";
        /// <summary>One or more messages are processed by a consumer..</summary>
        public const string Process = "process";
        /// <summary>Deprecated. Use `send` instead..</summary>
        [global::System.Obsolete("{\"note\": \"Replaced by `send`.\", \"reason\": \"renamed\", \"renamed_to\": \"send\"}", false)]
        public const string Publish = "publish";
        /// <summary>One or more messages are requested by a consumer. This operation refers to pull-based scenarios, where consumers explicitly call methods of messaging SDKs to receive messages..</summary>
        public const string Receive = "receive";
        /// <summary>One or more messages are provided for sending to an intermediary. If a single message is sent, the context of the "Send" span can be used as the creation context and no "Create" span needs to be created..</summary>
        public const string Send = "send";
        /// <summary>One or more messages are settled..</summary>
        public const string Settle = "settle";
    }

    /// <summary>RabbitMQ message routing key..</summary>
    public const string RabbitmqDestinationRoutingKey = "messaging.rabbitmq.destination.routing_key";

    /// <summary>RabbitMQ message delivery tag.</summary>
    public const string RabbitmqMessageDeliveryTag = "messaging.rabbitmq.message.delivery_tag";

    /// <summary>Deprecated, use `messaging.consumer.group.name` instead..</summary>
    [global::System.Obsolete("Replaced by `messaging.consumer.group.name` on the consumer spans. No replacement for producer spans.", false)]
    public const string RocketmqClientGroup = "messaging.rocketmq.client_group";

    /// <summary>Model of message consumption. This only applies to consumer spans..</summary>
    public const string RocketmqConsumptionModel = "messaging.rocketmq.consumption_model";

    /// <summary>Values for the <c>RocketmqConsumptionModel</c> attribute.</summary>
    public static class RocketmqConsumptionModelValues
    {
        /// <summary>Broadcasting consumption model.</summary>
        public const string Broadcasting = "broadcasting";
        /// <summary>Clustering consumption model.</summary>
        public const string Clustering = "clustering";
    }

    /// <summary>The delay time level for delay message, which determines the message delay time..</summary>
    public const string RocketmqMessageDelayTimeLevel = "messaging.rocketmq.message.delay_time_level";

    /// <summary>The timestamp in milliseconds that the delay message is expected to be delivered to consumer..</summary>
    public const string RocketmqMessageDeliveryTimestamp = "messaging.rocketmq.message.delivery_timestamp";

    /// <summary>It is essential for FIFO message. Messages that belong to the same message group are always processed one by one within the same consumer group..</summary>
    public const string RocketmqMessageGroup = "messaging.rocketmq.message.group";

    /// <summary>Key(s) of message, another way to mark message besides message id..</summary>
    public const string RocketmqMessageKeys = "messaging.rocketmq.message.keys";

    /// <summary>The secondary classifier of message besides topic..</summary>
    public const string RocketmqMessageTag = "messaging.rocketmq.message.tag";

    /// <summary>Type of message..</summary>
    public const string RocketmqMessageType = "messaging.rocketmq.message.type";

    /// <summary>Values for the <c>RocketmqMessageType</c> attribute.</summary>
    public static class RocketmqMessageTypeValues
    {
        /// <summary>Delay message.</summary>
        public const string Delay = "delay";
        /// <summary>FIFO message.</summary>
        public const string Fifo = "fifo";
        /// <summary>Normal message.</summary>
        public const string Normal = "normal";
        /// <summary>Transaction message.</summary>
        public const string Transaction = "transaction";
    }

    /// <summary>Namespace of RocketMQ resources, resources in different namespaces are individual..</summary>
    public const string RocketmqNamespace = "messaging.rocketmq.namespace";

    /// <summary>Deprecated, use `messaging.destination.subscription.name` instead..</summary>
    [global::System.Obsolete("Replaced by messaging.destination.subscription.name.", false)]
    public const string ServicebusDestinationSubscriptionName = "messaging.servicebus.destination.subscription_name";

    /// <summary>Describes the [settlement type](https://learn.microsoft.com/azure/service-bus-messaging/message-transfers-locks-settlement#peeklock)..</summary>
    public const string ServicebusDispositionStatus = "messaging.servicebus.disposition_status";

    /// <summary>Values for the <c>ServicebusDispositionStatus</c> attribute.</summary>
    public static class ServicebusDispositionStatusValues
    {
        /// <summary>Message is abandoned.</summary>
        public const string Abandon = "abandon";
        /// <summary>Message is completed.</summary>
        public const string Complete = "complete";
        /// <summary>Message is sent to dead letter queue.</summary>
        public const string DeadLetter = "dead_letter";
        /// <summary>Message is deferred.</summary>
        public const string Defer = "defer";
    }

    /// <summary>Number of deliveries that have been attempted for this message..</summary>
    public const string ServicebusMessageDeliveryCount = "messaging.servicebus.message.delivery_count";

    /// <summary>The UTC epoch seconds at which the message has been accepted and stored in the entity..</summary>
    public const string ServicebusMessageEnqueuedTime = "messaging.servicebus.message.enqueued_time";

    /// <summary>The messaging system as identified by the client instrumentation..</summary>
    /// <remarks>The actual messaging system may differ from the one known by the client. For example, when using Kafka client libraries to communicate with Azure Event Hubs, the `messaging.system` is set to `kafka` based on the instrumentation's best knowledge.</remarks>
    public const string System = "messaging.system";

    /// <summary>Values for the <c>System</c> attribute.</summary>
    public static class SystemValues
    {
        /// <summary>Apache ActiveMQ.</summary>
        public const string Activemq = "activemq";
        /// <summary>Amazon Simple Notification Service (SNS).</summary>
        public const string AwsSns = "aws.sns";
        /// <summary>Amazon Simple Queue Service (SQS).</summary>
        public const string AwsSqs = "aws_sqs";
        /// <summary>Azure Event Grid.</summary>
        public const string Eventgrid = "eventgrid";
        /// <summary>Azure Event Hubs.</summary>
        public const string Eventhubs = "eventhubs";
        /// <summary>Google Cloud Pub/Sub.</summary>
        public const string GcpPubsub = "gcp_pubsub";
        /// <summary>Java Message Service.</summary>
        public const string Jms = "jms";
        /// <summary>Apache Kafka.</summary>
        public const string Kafka = "kafka";
        /// <summary>Apache Pulsar.</summary>
        public const string Pulsar = "pulsar";
        /// <summary>RabbitMQ.</summary>
        public const string Rabbitmq = "rabbitmq";
        /// <summary>Apache RocketMQ.</summary>
        public const string Rocketmq = "rocketmq";
        /// <summary>Azure Service Bus.</summary>
        public const string Servicebus = "servicebus";
    }

}