// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.K8s;

/// <summary>K8s Attributes (incubating).</summary>
public static class K8sAttributes
{
    /// <summary>
    /// The name of the cluster.
    /// </summary>
    public const string ClusterName = "k8s.cluster.name";

    /// <summary>
    /// A pseudo-ID for the cluster, set to the UID of the <c>kube-system</c> namespace.
    /// </summary>
    /// <remarks>
    /// K8s doesn't have support for obtaining a cluster ID. If this is ever
    /// added, we will recommend collecting the <c>k8s.cluster.uid</c> through the
    /// official APIs. In the meantime, we are able to use the <c>uid</c> of the
    /// <c>kube-system</c> namespace as a proxy for cluster ID. Read on for the
    /// rationale.
    /// <p>
    /// Every object created in a K8s cluster is assigned a distinct UID. The
    /// <c>kube-system</c> namespace is used by Kubernetes itself and will exist
    /// for the lifetime of the cluster. Using the <c>uid</c> of the <c>kube-system</c>
    /// namespace is a reasonable proxy for the K8s ClusterID as it will only
    /// change if the cluster is rebuilt. Furthermore, Kubernetes UIDs are
    /// UUIDs as standardized by
    /// <a href="https://www.itu.int/ITU-T/studygroups/com17/oid.html">ISO/IEC 9834-8 and ITU-T X.667</a>.
    /// Which states:
    /// <blockquote>
    /// If generated according to one of the mechanisms defined in Rec.
    /// ITU-T X.667 | ISO/IEC 9834-8, a UUID is either guaranteed to be
    /// different from all other UUIDs generated before 3603 A.D., or is
    /// extremely likely to be different (depending on the mechanism chosen).</blockquote>
    /// <p>
    /// Therefore, UIDs between clusters should be extremely unlikely to
    /// conflict.
    /// </remarks>
    public const string ClusterUid = "k8s.cluster.uid";

    /// <summary>
    /// The name of the Container from Pod specification, must be unique within a Pod. Container runtime usually uses different globally unique name (<c>container.name</c>).
    /// </summary>
    public const string ContainerName = "k8s.container.name";

    /// <summary>
    /// Number of times the container was restarted. This attribute can be used to identify a particular container (running or stopped) within a container spec.
    /// </summary>
    public const string ContainerRestartCount = "k8s.container.restart_count";

    /// <summary>
    /// Last terminated reason of the Container.
    /// </summary>
    public const string ContainerStatusLastTerminatedReason = "k8s.container.status.last_terminated_reason";

    /// <summary>
    /// The reason for the container state. Corresponds to the <c>reason</c> field of the: <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#containerstatewaiting-v1-core">K8s ContainerStateWaiting</a> or <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#containerstateterminated-v1-core">K8s ContainerStateTerminated</a>.
    /// </summary>
    public const string ContainerStatusReason = "k8s.container.status.reason";

    /// <summary>
    /// Values for the <c>ContainerStatusReason</c> attribute.
    /// </summary>
    public static class ContainerStatusReasonValues
    {
        /// <summary>
        /// The container has completed execution.
        /// </summary>
        public const string Completed = "Completed";

        /// <summary>
        /// The container cannot run.
        /// </summary>
        public const string ContainerCannotRun = "ContainerCannotRun";

        /// <summary>
        /// The container is being created.
        /// </summary>
        public const string ContainerCreating = "ContainerCreating";

        /// <summary>
        /// The container is in a crash loop back off state.
        /// </summary>
        public const string CrashLoopBackOff = "CrashLoopBackOff";

        /// <summary>
        /// There was an error creating the container configuration.
        /// </summary>
        public const string CreateContainerConfigError = "CreateContainerConfigError";

        /// <summary>
        /// There was an error pulling the container image.
        /// </summary>
        public const string ErrImagePull = "ErrImagePull";

        /// <summary>
        /// There was an error with the container.
        /// </summary>
        public const string Error = "Error";

        /// <summary>
        /// The container image pull is in back off state.
        /// </summary>
        public const string ImagePullBackOff = "ImagePullBackOff";

        /// <summary>
        /// The container was killed due to out of memory.
        /// </summary>
        public const string OomKilled = "OOMKilled";
    }

    /// <summary>
    /// The state of the container. <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#containerstate-v1-core">K8s ContainerState</a>.
    /// </summary>
    public const string ContainerStatusState = "k8s.container.status.state";

    /// <summary>
    /// Values for the <c>ContainerStatusState</c> attribute.
    /// </summary>
    public static class ContainerStatusStateValues
    {
        /// <summary>
        /// The container is running.
        /// </summary>
        public const string Running = "running";

        /// <summary>
        /// The container has terminated.
        /// </summary>
        public const string Terminated = "terminated";

        /// <summary>
        /// The container is waiting.
        /// </summary>
        public const string Waiting = "waiting";
    }

    /// <summary>
    /// The cronjob annotation placed on the CronJob, the <c><key></c> being the annotation name, the value being the annotation value.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>An annotation <c>retries</c> with value <c>4</c> SHOULD be recorded as the
    /// <c>k8s.cronjob.annotation.retries</c> attribute with value <c>"4"</c>.</li>
    ///   <li>An annotation <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.cronjob.annotation.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string CronjobAnnotation = "k8s.cronjob.annotation";

    /// <summary>
    /// The label placed on the CronJob, the <c><key></c> being the label name, the value being the label value.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>type</c> with value <c>weekly</c> SHOULD be recorded as the
    /// <c>k8s.cronjob.label.type</c> attribute with value <c>"weekly"</c>.</li>
    ///   <li>A label <c>automated</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.cronjob.label.automated</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string CronjobLabel = "k8s.cronjob.label";

    /// <summary>
    /// The name of the CronJob.
    /// </summary>
    public const string CronjobName = "k8s.cronjob.name";

    /// <summary>
    /// The UID of the CronJob.
    /// </summary>
    public const string CronjobUid = "k8s.cronjob.uid";

    /// <summary>
    /// The annotation placed on the DaemonSet, the <c><key></c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>replicas</c> with value <c>1</c> SHOULD be recorded
    /// as the <c>k8s.daemonset.annotation.replicas</c> attribute with value <c>"1"</c>.</li>
    ///   <li>A label <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.daemonset.annotation.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string DaemonsetAnnotation = "k8s.daemonset.annotation";

    /// <summary>
    /// The label placed on the DaemonSet, the <c><key></c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>app</c> with value <c>guestbook</c> SHOULD be recorded
    /// as the <c>k8s.daemonset.label.app</c> attribute with value <c>"guestbook"</c>.</li>
    ///   <li>A label <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.daemonset.label.injected</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string DaemonsetLabel = "k8s.daemonset.label";

    /// <summary>
    /// The name of the DaemonSet.
    /// </summary>
    public const string DaemonsetName = "k8s.daemonset.name";

    /// <summary>
    /// The UID of the DaemonSet.
    /// </summary>
    public const string DaemonsetUid = "k8s.daemonset.uid";

    /// <summary>
    /// The annotation placed on the Deployment, the <c><key></c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>replicas</c> with value <c>1</c> SHOULD be recorded
    /// as the <c>k8s.deployment.annotation.replicas</c> attribute with value <c>"1"</c>.</li>
    ///   <li>A label <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.deployment.annotation.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string DeploymentAnnotation = "k8s.deployment.annotation";

    /// <summary>
    /// The label placed on the Deployment, the <c><key></c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>replicas</c> with value <c>0</c> SHOULD be recorded
    /// as the <c>k8s.deployment.label.app</c> attribute with value <c>"guestbook"</c>.</li>
    ///   <li>A label <c>injected</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.deployment.label.injected</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string DeploymentLabel = "k8s.deployment.label";

    /// <summary>
    /// The name of the Deployment.
    /// </summary>
    public const string DeploymentName = "k8s.deployment.name";

    /// <summary>
    /// The UID of the Deployment.
    /// </summary>
    public const string DeploymentUid = "k8s.deployment.uid";

    /// <summary>
    /// The type of metric source for the horizontal pod autoscaler.
    /// </summary>
    /// <remarks>
    /// This attribute reflects the <c>type</c> field of spec.metrics[] in the HPA.
    /// </remarks>
    public const string HpaMetricType = "k8s.hpa.metric.type";

    /// <summary>
    /// The name of the horizontal pod autoscaler.
    /// </summary>
    public const string HpaName = "k8s.hpa.name";

    /// <summary>
    /// The API version of the target resource to scale for the HorizontalPodAutoscaler.
    /// </summary>
    /// <remarks>
    /// This maps to the <c>apiVersion</c> field in the <c>scaleTargetRef</c> of the HPA spec.
    /// </remarks>
    public const string HpaScaletargetrefApiVersion = "k8s.hpa.scaletargetref.api_version";

    /// <summary>
    /// The kind of the target resource to scale for the HorizontalPodAutoscaler.
    /// </summary>
    /// <remarks>
    /// This maps to the <c>kind</c> field in the <c>scaleTargetRef</c> of the HPA spec.
    /// </remarks>
    public const string HpaScaletargetrefKind = "k8s.hpa.scaletargetref.kind";

    /// <summary>
    /// The name of the target resource to scale for the HorizontalPodAutoscaler.
    /// </summary>
    /// <remarks>
    /// This maps to the <c>name</c> field in the <c>scaleTargetRef</c> of the HPA spec.
    /// </remarks>
    public const string HpaScaletargetrefName = "k8s.hpa.scaletargetref.name";

    /// <summary>
    /// The UID of the horizontal pod autoscaler.
    /// </summary>
    public const string HpaUid = "k8s.hpa.uid";

    /// <summary>
    /// The size (identifier) of the K8s huge page.
    /// </summary>
    public const string HugepageSize = "k8s.hugepage.size";

    /// <summary>
    /// The annotation placed on the Job, the <c><key></c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>number</c> with value <c>1</c> SHOULD be recorded
    /// as the <c>k8s.job.annotation.number</c> attribute with value <c>"1"</c>.</li>
    ///   <li>A label <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.job.annotation.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string JobAnnotation = "k8s.job.annotation";

    /// <summary>
    /// The label placed on the Job, the <c><key></c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>jobtype</c> with value <c>ci</c> SHOULD be recorded
    /// as the <c>k8s.job.label.jobtype</c> attribute with value <c>"ci"</c>.</li>
    ///   <li>A label <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.job.label.automated</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string JobLabel = "k8s.job.label";

    /// <summary>
    /// The name of the Job.
    /// </summary>
    public const string JobName = "k8s.job.name";

    /// <summary>
    /// The UID of the Job.
    /// </summary>
    public const string JobUid = "k8s.job.uid";

    /// <summary>
    /// The annotation placed on the Namespace, the <c><key></c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>ttl</c> with value <c>0</c> SHOULD be recorded
    /// as the <c>k8s.namespace.annotation.ttl</c> attribute with value <c>"0"</c>.</li>
    ///   <li>A label <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.namespace.annotation.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string NamespaceAnnotation = "k8s.namespace.annotation";

    /// <summary>
    /// The label placed on the Namespace, the <c><key></c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>kubernetes.io/metadata.name</c> with value <c>default</c> SHOULD be recorded
    /// as the <c>k8s.namespace.label.kubernetes.io/metadata.name</c> attribute with value <c>"default"</c>.</li>
    ///   <li>A label <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.namespace.label.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string NamespaceLabel = "k8s.namespace.label";

    /// <summary>
    /// The name of the namespace that the pod is running in.
    /// </summary>
    public const string NamespaceName = "k8s.namespace.name";

    /// <summary>
    /// The phase of the K8s namespace.
    /// </summary>
    /// <remarks>
    /// This attribute aligns with the <c>phase</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#namespacestatus-v1-core">K8s NamespaceStatus</a>.
    /// </remarks>
    public const string NamespacePhase = "k8s.namespace.phase";

    /// <summary>
    /// Values for the <c>NamespacePhase</c> attribute.
    /// </summary>
    public static class NamespacePhaseValues
    {
        /// <summary>
        /// Active namespace phase as described by <a href="https://pkg.go.dev/k8s.io/api@v0.31.3/core/v1#NamespacePhase">K8s API</a>.
        /// </summary>
        public const string Active = "active";

        /// <summary>
        /// Terminating namespace phase as described by <a href="https://pkg.go.dev/k8s.io/api@v0.31.3/core/v1#NamespacePhase">K8s API</a>.
        /// </summary>
        public const string Terminating = "terminating";
    }

    /// <summary>
    /// The annotation placed on the Node, the <c><key></c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>An annotation <c>node.alpha.kubernetes.io/ttl</c> with value <c>0</c> SHOULD be recorded as
    /// the <c>k8s.node.annotation.node.alpha.kubernetes.io/ttl</c> attribute with value <c>"0"</c>.</li>
    ///   <li>An annotation <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.node.annotation.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string NodeAnnotation = "k8s.node.annotation";

    /// <summary>
    /// The status of the condition, one of True, False, Unknown.
    /// </summary>
    /// <remarks>
    /// This attribute aligns with the <c>status</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#nodecondition-v1-core">NodeCondition</a>.
    /// </remarks>
    public const string NodeConditionStatus = "k8s.node.condition.status";

    /// <summary>
    /// Values for the <c>NodeConditionStatus</c> attribute.
    /// </summary>
    public static class NodeConditionStatusValues
    {
        /// <summary>
        /// condition_false.
        /// </summary>
        public const string ConditionFalse = "false";

        /// <summary>
        /// condition_true.
        /// </summary>
        public const string ConditionTrue = "true";

        /// <summary>
        /// condition_unknown.
        /// </summary>
        public const string ConditionUnknown = "unknown";
    }

    /// <summary>
    /// The condition type of a K8s Node.
    /// </summary>
    /// <remarks>
    /// K8s Node conditions as described
    /// by <a href="https://v1-32.docs.kubernetes.io/docs/reference/node/node-status/#condition">K8s documentation</a>.
    /// <p>
    /// This attribute aligns with the <c>type</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#nodecondition-v1-core">NodeCondition</a>
    /// <p>
    /// The set of possible values is not limited to those listed here. Managed Kubernetes environments,
    /// or custom controllers MAY introduce additional node condition types.
    /// When this occurs, the exact value as reported by the Kubernetes API SHOULD be used.
    /// </remarks>
    public const string NodeConditionType = "k8s.node.condition.type";

    /// <summary>
    /// Values for the <c>NodeConditionType</c> attribute.
    /// </summary>
    public static class NodeConditionTypeValues
    {
        /// <summary>
        /// Pressure exists on the disk size—that is, if the disk capacity is low.
        /// </summary>
        public const string DiskPressure = "DiskPressure";

        /// <summary>
        /// Pressure exists on the node memory—that is, if the node memory is low.
        /// </summary>
        public const string MemoryPressure = "MemoryPressure";

        /// <summary>
        /// The network for the node is not correctly configured.
        /// </summary>
        public const string NetworkUnavailable = "NetworkUnavailable";

        /// <summary>
        /// Pressure exists on the processes—that is, if there are too many processes on the node.
        /// </summary>
        public const string PidPressure = "PIDPressure";

        /// <summary>
        /// The node is healthy and ready to accept pods.
        /// </summary>
        public const string Ready = "Ready";
    }

    /// <summary>
    /// The label placed on the Node, the <c><key></c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>kubernetes.io/arch</c> with value <c>arm64</c> SHOULD be recorded
    /// as the <c>k8s.node.label.kubernetes.io/arch</c> attribute with value <c>"arm64"</c>.</li>
    ///   <li>A label <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.node.label.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string NodeLabel = "k8s.node.label";

    /// <summary>
    /// The name of the Node.
    /// </summary>
    public const string NodeName = "k8s.node.name";

    /// <summary>
    /// The name of the system container running on the K8s Node.
    /// </summary>
    public const string NodeSystemContainerName = "k8s.node.system_container.name";

    /// <summary>
    /// The UID of the Node.
    /// </summary>
    public const string NodeUid = "k8s.node.uid";

    /// <summary>
    /// The annotation placed on the PersistentVolume, the <c><key></c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>An annotation <c>pv.kubernetes.io/provisioned-by</c> with value <c>kubernetes.io/aws-ebs</c> SHOULD be recorded as
    /// the <c>k8s.persistentvolume.annotation.pv.kubernetes.io/provisioned-by</c> attribute with value <c>"kubernetes.io/aws-ebs"</c>.</li>
    ///   <li>An annotation <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.persistentvolume.annotation.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string PersistentvolumeAnnotation = "k8s.persistentvolume.annotation";

    /// <summary>
    /// The label placed on the PersistentVolume, the <c><key></c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>type</c> with value <c>ssd</c> SHOULD be recorded as
    /// the <c>k8s.persistentvolume.label.type</c> attribute with value <c>"ssd"</c>.</li>
    ///   <li>A label <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.persistentvolume.label.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string PersistentvolumeLabel = "k8s.persistentvolume.label";

    /// <summary>
    /// The name of the PersistentVolume.
    /// </summary>
    public const string PersistentvolumeName = "k8s.persistentvolume.name";

    /// <summary>
    /// The reclaim policy of the PersistentVolume.
    /// </summary>
    /// <remarks>
    /// This attribute aligns with the <c>persistentVolumeReclaimPolicy</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1/#PersistentVolumeSpec">K8s PersistentVolumeSpec</a>.
    /// </remarks>
    public const string PersistentvolumeReclaimPolicy = "k8s.persistentvolume.reclaim_policy";

    /// <summary>
    /// Values for the <c>PersistentvolumeReclaimPolicy</c> attribute.
    /// </summary>
    public static class PersistentvolumeReclaimPolicyValues
    {
        /// <summary>
        /// The volume will be deleted when released from its claim.
        /// </summary>
        public const string Delete = "Delete";

        /// <summary>
        /// The volume will be recycled (basic scrub) when released from its claim.
        /// </summary>
        public const string Recycle = "Recycle";

        /// <summary>
        /// The volume will be retained when released from its claim.
        /// </summary>
        public const string Retain = "Retain";
    }

    /// <summary>
    /// The phase of the PersistentVolume.
    /// </summary>
    /// <remarks>
    /// This attribute aligns with the <c>phase</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1/#PersistentVolumeStatus">K8s PersistentVolumeStatus</a>.
    /// </remarks>
    public const string PersistentvolumeStatusPhase = "k8s.persistentvolume.status.phase";

    /// <summary>
    /// Values for the <c>PersistentvolumeStatusPhase</c> attribute.
    /// </summary>
    public static class PersistentvolumeStatusPhaseValues
    {
        /// <summary>
        /// The volume is available and not yet bound to a claim.
        /// </summary>
        public const string Available = "Available";

        /// <summary>
        /// The volume is bound to a claim.
        /// </summary>
        public const string Bound = "Bound";

        /// <summary>
        /// The volume has failed its automatic reclamation.
        /// </summary>
        public const string Failed = "Failed";

        /// <summary>
        /// The volume is being provisioned.
        /// </summary>
        public const string Pending = "Pending";

        /// <summary>
        /// The claim has been deleted but the volume is not yet available.
        /// </summary>
        public const string Released = "Released";
    }

    /// <summary>
    /// The UID of the PersistentVolume.
    /// </summary>
    public const string PersistentvolumeUid = "k8s.persistentvolume.uid";

    /// <summary>
    /// The annotation placed on the PersistentVolumeClaim, the <c><key></c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>An annotation <c>volume.beta.kubernetes.io/storage-provisioner</c> with value <c>kubernetes.io/aws-ebs</c> SHOULD be recorded as
    /// the <c>k8s.persistentvolumeclaim.annotation.volume.beta.kubernetes.io/storage-provisioner</c> attribute with value <c>"kubernetes.io/aws-ebs"</c>.</li>
    ///   <li>An annotation <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.persistentvolumeclaim.annotation.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string PersistentvolumeclaimAnnotation = "k8s.persistentvolumeclaim.annotation";

    /// <summary>
    /// The label placed on the PersistentVolumeClaim, the <c><key></c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>app</c> with value <c>my-app</c> SHOULD be recorded as
    /// the <c>k8s.persistentvolumeclaim.label.app</c> attribute with value <c>"my-app"</c>.</li>
    ///   <li>A label <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.persistentvolumeclaim.label.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string PersistentvolumeclaimLabel = "k8s.persistentvolumeclaim.label";

    /// <summary>
    /// The name of the PersistentVolumeClaim.
    /// </summary>
    public const string PersistentvolumeclaimName = "k8s.persistentvolumeclaim.name";

    /// <summary>
    /// The phase of the PersistentVolumeClaim.
    /// </summary>
    /// <remarks>
    /// This attribute aligns with the <c>phase</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1/#PersistentVolumeClaimStatus">K8s PersistentVolumeClaimStatus</a>.
    /// </remarks>
    public const string PersistentvolumeclaimStatusPhase = "k8s.persistentvolumeclaim.status.phase";

    /// <summary>
    /// Values for the <c>PersistentvolumeclaimStatusPhase</c> attribute.
    /// </summary>
    public static class PersistentvolumeclaimStatusPhaseValues
    {
        /// <summary>
        /// The claim is bound to a volume.
        /// </summary>
        public const string Bound = "Bound";

        /// <summary>
        /// The claim has lost its underlying volume (the volume does not exist anymore).
        /// </summary>
        public const string Lost = "Lost";

        /// <summary>
        /// The claim has not yet been bound to a volume.
        /// </summary>
        public const string Pending = "Pending";
    }

    /// <summary>
    /// The UID of the PersistentVolumeClaim.
    /// </summary>
    public const string PersistentvolumeclaimUid = "k8s.persistentvolumeclaim.uid";

    /// <summary>
    /// The annotation placed on the Pod, the <c><key></c> being the annotation name, the value being the annotation value.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>An annotation <c>kubernetes.io/enforce-mountable-secrets</c> with value <c>true</c> SHOULD be recorded as
    /// the <c>k8s.pod.annotation.kubernetes.io/enforce-mountable-secrets</c> attribute with value <c>"true"</c>.</li>
    ///   <li>An annotation <c>mycompany.io/arch</c> with value <c>x64</c> SHOULD be recorded as
    /// the <c>k8s.pod.annotation.mycompany.io/arch</c> attribute with value <c>"x64"</c>.</li>
    ///   <li>An annotation <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.pod.annotation.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string PodAnnotation = "k8s.pod.annotation";

    /// <summary>
    /// Specifies the hostname of the Pod.
    /// </summary>
    /// <remarks>
    /// The K8s Pod spec has an optional hostname field, which can be used to specify a hostname.
    /// Refer to <a href="https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-hostname-and-subdomain-field">K8s docs</a>
    /// for more information about this field.
    /// <p>
    /// This attribute aligns with the <c>hostname</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.34/#podspec-v1-core">K8s PodSpec</a>.
    /// </remarks>
    public const string PodHostname = "k8s.pod.hostname";

    /// <summary>
    /// IP address allocated to the Pod.
    /// </summary>
    /// <remarks>
    /// This attribute aligns with the <c>podIP</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.34/#podstatus-v1-core">K8s PodStatus</a>.
    /// </remarks>
    public const string PodIp = "k8s.pod.ip";

    /// <summary>
    /// The label placed on the Pod, the <c><key></c> being the label name, the value being the label value.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>app</c> with value <c>my-app</c> SHOULD be recorded as
    /// the <c>k8s.pod.label.app</c> attribute with value <c>"my-app"</c>.</li>
    ///   <li>A label <c>mycompany.io/arch</c> with value <c>x64</c> SHOULD be recorded as
    /// the <c>k8s.pod.label.mycompany.io/arch</c> attribute with value <c>"x64"</c>.</li>
    ///   <li>A label <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.pod.label.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string PodLabel = "k8s.pod.label";

    /// <summary>
    /// Deprecated, use <c>k8s.pod.label</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by k8s.pod.label.", false)]
    public const string PodLabels = "k8s.pod.labels";

    /// <summary>
    /// The name of the Pod.
    /// </summary>
    public const string PodName = "k8s.pod.name";

    /// <summary>
    /// The start timestamp of the Pod.
    /// </summary>
    /// <remarks>
    /// Date and time at which the object was acknowledged by the Kubelet.
    /// This is before the Kubelet pulled the container image(s) for the pod.
    /// <p>
    /// This attribute aligns with the <c>startTime</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.34/#podstatus-v1-core">K8s PodStatus</a>,
    /// in ISO 8601 (RFC 3339 compatible) format.
    /// </remarks>
    public const string PodStartTime = "k8s.pod.start_time";

    /// <summary>
    /// The phase for the pod. Corresponds to the <c>phase</c> field of the: <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.33/#podstatus-v1-core">K8s PodStatus</a>.
    /// </summary>
    public const string PodStatusPhase = "k8s.pod.status.phase";

    /// <summary>
    /// Values for the <c>PodStatusPhase</c> attribute.
    /// </summary>
    public static class PodStatusPhaseValues
    {
        /// <summary>
        /// All containers in the pod have terminated, and at least one container has terminated in a failure (exited with a non-zero exit code or was stopped by the system).
        /// </summary>
        public const string Failed = "Failed";

        /// <summary>
        /// The pod has been accepted by the system, but one or more of the containers has not been started. This includes time before being bound to a node, as well as time spent pulling images onto the host.
        /// </summary>
        public const string Pending = "Pending";

        /// <summary>
        /// The pod has been bound to a node and all of the containers have been started. At least one container is still running or is in the process of being restarted.
        /// </summary>
        public const string Running = "Running";

        /// <summary>
        /// All containers in the pod have voluntarily terminated with a container exit code of 0, and the system is not going to restart any of these containers.
        /// </summary>
        public const string Succeeded = "Succeeded";

        /// <summary>
        /// For some reason the state of the pod could not be obtained, typically due to an error in communicating with the host of the pod.
        /// </summary>
        public const string Unknown = "Unknown";
    }

    /// <summary>
    /// The reason for the pod state. Corresponds to the <c>reason</c> field of the: <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.33/#podstatus-v1-core">K8s PodStatus</a>.
    /// </summary>
    public const string PodStatusReason = "k8s.pod.status.reason";

    /// <summary>
    /// Values for the <c>PodStatusReason</c> attribute.
    /// </summary>
    public static class PodStatusReasonValues
    {
        /// <summary>
        /// The pod is evicted.
        /// </summary>
        public const string Evicted = "Evicted";

        /// <summary>
        /// The pod is in a status because of its node affinity.
        /// </summary>
        public const string NodeAffinity = "NodeAffinity";

        /// <summary>
        /// The reason on a pod when its state cannot be confirmed as kubelet is unresponsive on the node it is (was) running.
        /// </summary>
        public const string NodeLost = "NodeLost";

        /// <summary>
        /// The node is shutdown.
        /// </summary>
        public const string Shutdown = "Shutdown";

        /// <summary>
        /// The pod was rejected admission to the node because of an error during admission that could not be categorized.
        /// </summary>
        public const string UnexpectedAdmissionError = "UnexpectedAdmissionError";
    }

    /// <summary>
    /// The UID of the Pod.
    /// </summary>
    public const string PodUid = "k8s.pod.uid";

    /// <summary>
    /// The annotation placed on the ReplicaSet, the <c><key></c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>replicas</c> with value <c>0</c> SHOULD be recorded
    /// as the <c>k8s.replicaset.annotation.replicas</c> attribute with value <c>"0"</c>.</li>
    ///   <li>A label <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.replicaset.annotation.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string ReplicasetAnnotation = "k8s.replicaset.annotation";

    /// <summary>
    /// The label placed on the ReplicaSet, the <c><key></c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>app</c> with value <c>guestbook</c> SHOULD be recorded
    /// as the <c>k8s.replicaset.label.app</c> attribute with value <c>"guestbook"</c>.</li>
    ///   <li>A label <c>injected</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.replicaset.label.injected</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string ReplicasetLabel = "k8s.replicaset.label";

    /// <summary>
    /// The name of the ReplicaSet.
    /// </summary>
    public const string ReplicasetName = "k8s.replicaset.name";

    /// <summary>
    /// The UID of the ReplicaSet.
    /// </summary>
    public const string ReplicasetUid = "k8s.replicaset.uid";

    /// <summary>
    /// The name of the replication controller.
    /// </summary>
    public const string ReplicationcontrollerName = "k8s.replicationcontroller.name";

    /// <summary>
    /// The UID of the replication controller.
    /// </summary>
    public const string ReplicationcontrollerUid = "k8s.replicationcontroller.uid";

    /// <summary>
    /// The name of the resource quota.
    /// </summary>
    public const string ResourcequotaName = "k8s.resourcequota.name";

    /// <summary>
    /// The name of the K8s resource a resource quota defines.
    /// </summary>
    /// <remarks>
    /// The value for this attribute can be either the full <c>count/<resource>[.<group>]</c> string (e.g., count/deployments.apps, count/pods), or, for certain core Kubernetes resources, just the resource name (e.g., pods, services, configmaps). Both forms are supported by Kubernetes for object count quotas. See <a href="https://kubernetes.io/docs/concepts/policy/resource-quotas/#quota-on-object-count">Kubernetes Resource Quotas documentation</a> for more details.
    /// </remarks>
    public const string ResourcequotaResourceName = "k8s.resourcequota.resource_name";

    /// <summary>
    /// The UID of the resource quota.
    /// </summary>
    public const string ResourcequotaUid = "k8s.resourcequota.uid";

    /// <summary>
    /// The annotation placed on the Service, the <c><key></c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>An annotation <c>prometheus.io/scrape</c> with value <c>true</c> SHOULD be recorded as
    /// the <c>k8s.service.annotation.prometheus.io/scrape</c> attribute with value <c>"true"</c>.</li>
    ///   <li>An annotation <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.service.annotation.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string ServiceAnnotation = "k8s.service.annotation";

    /// <summary>
    /// The address type of the service endpoint.
    /// </summary>
    /// <remarks>
    /// The network address family or type of the endpoint.
    /// This attribute aligns with the <c>addressType</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/kubernetes-api/service-resources/endpoint-slice-v1/">K8s EndpointSlice</a>.
    /// It is used to differentiate metrics when a Service is backed by multiple address types
    /// (e.g., in dual-stack clusters).
    /// </remarks>
    public const string ServiceEndpointAddressType = "k8s.service.endpoint.address_type";

    /// <summary>
    /// Values for the <c>ServiceEndpointAddressType</c> attribute.
    /// </summary>
    public static class ServiceEndpointAddressTypeValues
    {
        /// <summary>
        /// FQDN address type.
        /// </summary>
        public const string Fqdn = "FQDN";

        /// <summary>
        /// IPv4 address type.
        /// </summary>
        public const string Ipv4 = "IPv4";

        /// <summary>
        /// IPv6 address type.
        /// </summary>
        public const string Ipv6 = "IPv6";
    }

    /// <summary>
    /// The condition of the service endpoint.
    /// </summary>
    /// <remarks>
    /// The current operational condition of the service endpoint.
    /// An endpoint can have multiple conditions set at once (e.g., both <c>serving</c> and <c>terminating</c> during rollout).
    /// This attribute aligns with the condition fields in the <a href="https://kubernetes.io/docs/reference/kubernetes-api/service-resources/endpoint-slice-v1/">K8s EndpointSlice</a>.
    /// </remarks>
    public const string ServiceEndpointCondition = "k8s.service.endpoint.condition";

    /// <summary>
    /// Values for the <c>ServiceEndpointCondition</c> attribute.
    /// </summary>
    public static class ServiceEndpointConditionValues
    {
        /// <summary>
        /// The endpoint is ready to receive new connections.
        /// </summary>
        public const string Ready = "ready";

        /// <summary>
        /// The endpoint is currently handling traffic.
        /// </summary>
        public const string Serving = "serving";

        /// <summary>
        /// The endpoint is in the process of shutting down.
        /// </summary>
        public const string Terminating = "terminating";
    }

    /// <summary>
    /// The zone of the service endpoint.
    /// </summary>
    /// <remarks>
    /// The zone where the endpoint is located, typically corresponding to a failure domain.
    /// This attribute aligns with the <c>zone</c> field of endpoints in the
    /// <a href="https://kubernetes.io/docs/reference/kubernetes-api/service-resources/endpoint-slice-v1/">K8s EndpointSlice</a>.
    /// It enables zone-aware monitoring of service endpoint distribution and supports
    /// features like <a href="https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/">Topology Aware Routing</a>.
    /// <p>
    /// If the zone is not populated (e.g., nodes without the <c>topology.kubernetes.io/zone</c> label),
    /// the attribute value will be an empty string.
    /// </remarks>
    public const string ServiceEndpointZone = "k8s.service.endpoint.zone";

    /// <summary>
    /// The label placed on the Service, the <c><key></c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>app</c> with value <c>my-service</c> SHOULD be recorded as
    /// the <c>k8s.service.label.app</c> attribute with value <c>"my-service"</c>.</li>
    ///   <li>A label <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.service.label.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string ServiceLabel = "k8s.service.label";

    /// <summary>
    /// The name of the Service.
    /// </summary>
    public const string ServiceName = "k8s.service.name";

    /// <summary>
    /// Whether the Service publishes not-ready endpoints.
    /// </summary>
    /// <remarks>
    /// Whether the Service is configured to publish endpoints before the pods are ready.
    /// This attribute is typically used to indicate that a Service (such as a headless
    /// Service for a StatefulSet) allows peer discovery before pods pass their readiness probes.
    /// It aligns with the <c>publishNotReadyAddresses</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec">K8s ServiceSpec</a>.
    /// </remarks>
    public const string ServicePublishNotReadyAddresses = "k8s.service.publish_not_ready_addresses";

    /// <summary>
    /// The selector key-value pair placed on the Service, the <c><key></c> being the selector key, the value being the selector value.
    /// </summary>
    /// <remarks>
    /// These selectors are used to correlate with pod labels. Each selector key-value pair becomes a separate attribute.
    /// <p>
    /// Examples:
    /// <ul>
    ///   <li>A selector <c>app=my-app</c> SHOULD be recorded as
    /// the <c>k8s.service.selector.app</c> attribute with value <c>"my-app"</c>.</li>
    ///   <li>A selector <c>version=v1</c> SHOULD be recorded as
    /// the <c>k8s.service.selector.version</c> attribute with value <c>"v1"</c>.</li>
    /// </ul>
    /// </remarks>
    public const string ServiceSelector = "k8s.service.selector";

    /// <summary>
    /// The traffic distribution policy for the Service.
    /// </summary>
    /// <remarks>
    /// Specifies how traffic is distributed to endpoints for this Service.
    /// This attribute aligns with the <c>trafficDistribution</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/networking/virtual-ips/#traffic-distribution">K8s ServiceSpec</a>.
    /// Known values include <c>PreferSameZone</c> (prefer endpoints in the same zone as the client) and
    /// <c>PreferSameNode</c> (prefer endpoints on the same node, fallback to same zone, then cluster-wide).
    /// If this field is not set on the Service, the attribute SHOULD NOT be emitted.
    /// When not set, Kubernetes distributes traffic evenly across all endpoints cluster-wide.
    /// </remarks>
    public const string ServiceTrafficDistribution = "k8s.service.traffic_distribution";

    /// <summary>
    /// The type of the Kubernetes Service.
    /// </summary>
    /// <remarks>
    /// This attribute aligns with the <c>type</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec">K8s ServiceSpec</a>.
    /// </remarks>
    public const string ServiceType = "k8s.service.type";

    /// <summary>
    /// Values for the <c>ServiceType</c> attribute.
    /// </summary>
    public static class ServiceTypeValues
    {
        /// <summary>
        /// ClusterIP service type.
        /// </summary>
        public const string ClusterIp = "ClusterIP";

        /// <summary>
        /// ExternalName service type.
        /// </summary>
        public const string ExternalName = "ExternalName";

        /// <summary>
        /// LoadBalancer service type.
        /// </summary>
        public const string LoadBalancer = "LoadBalancer";

        /// <summary>
        /// NodePort service type.
        /// </summary>
        public const string NodePort = "NodePort";
    }

    /// <summary>
    /// The UID of the Service.
    /// </summary>
    public const string ServiceUid = "k8s.service.uid";

    /// <summary>
    /// The annotation placed on the StatefulSet, the <c><key></c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>replicas</c> with value <c>1</c> SHOULD be recorded
    /// as the <c>k8s.statefulset.annotation.replicas</c> attribute with value <c>"1"</c>.</li>
    ///   <li>A label <c>data</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.statefulset.annotation.data</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string StatefulsetAnnotation = "k8s.statefulset.annotation";

    /// <summary>
    /// The label placed on the StatefulSet, the <c><key></c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <ul>
    ///   <li>A label <c>replicas</c> with value <c>0</c> SHOULD be recorded
    /// as the <c>k8s.statefulset.label.app</c> attribute with value <c>"guestbook"</c>.</li>
    ///   <li>A label <c>injected</c> with empty string value SHOULD be recorded as
    /// the <c>k8s.statefulset.label.injected</c> attribute with value <c>""</c>.</li>
    /// </ul>
    /// </remarks>
    public const string StatefulsetLabel = "k8s.statefulset.label";

    /// <summary>
    /// The name of the StatefulSet.
    /// </summary>
    public const string StatefulsetName = "k8s.statefulset.name";

    /// <summary>
    /// The UID of the StatefulSet.
    /// </summary>
    public const string StatefulsetUid = "k8s.statefulset.uid";

    /// <summary>
    /// The name of K8s <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#storageclass-v1-storage-k8s-io">StorageClass</a> object.
    /// </summary>
    public const string StorageclassName = "k8s.storageclass.name";

    /// <summary>
    /// The name of the K8s volume.
    /// </summary>
    public const string VolumeName = "k8s.volume.name";

    /// <summary>
    /// The type of the K8s volume.
    /// </summary>
    public const string VolumeType = "k8s.volume.type";

    /// <summary>
    /// Values for the <c>VolumeType</c> attribute.
    /// </summary>
    public static class VolumeTypeValues
    {
        /// <summary>
        /// A <a href="https://v1-30.docs.kubernetes.io/docs/concepts/storage/volumes/#configmap">configMap</a> volume.
        /// </summary>
        public const string ConfigMap = "configMap";

        /// <summary>
        /// A <a href="https://v1-30.docs.kubernetes.io/docs/concepts/storage/volumes/#downwardapi">downwardAPI</a> volume.
        /// </summary>
        public const string DownwardApi = "downwardAPI";

        /// <summary>
        /// An <a href="https://v1-30.docs.kubernetes.io/docs/concepts/storage/volumes/#emptydir">emptyDir</a> volume.
        /// </summary>
        public const string EmptyDir = "emptyDir";

        /// <summary>
        /// A <a href="https://v1-30.docs.kubernetes.io/docs/concepts/storage/volumes/#local">local</a> volume.
        /// </summary>
        public const string Local = "local";

        /// <summary>
        /// A <a href="https://v1-30.docs.kubernetes.io/docs/concepts/storage/volumes/#persistentvolumeclaim">persistentVolumeClaim</a> volume.
        /// </summary>
        public const string PersistentVolumeClaim = "persistentVolumeClaim";

        /// <summary>
        /// A <a href="https://v1-30.docs.kubernetes.io/docs/concepts/storage/volumes/#secret">secret</a> volume.
        /// </summary>
        public const string Secret = "secret";
    }
}
