// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Message;

/// <summary>Message Attributes (incubating).</summary>
public static class MessageAttributes
{
    /// <summary>Deprecated, no replacement at this time..</summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string CompressedSize = "message.compressed_size";

    /// <summary>Deprecated, no replacement at this time..</summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string Id = "message.id";

    /// <summary>Deprecated, no replacement at this time..</summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string Type = "message.type";

    /// <summary>Values for the <c>Type</c> attribute.</summary>
    public static class TypeValues
    {
        /// <summary>.</summary>
        public const string Received = "RECEIVED";
        /// <summary>.</summary>
        public const string Sent = "SENT";
    }

    /// <summary>Deprecated, no replacement at this time..</summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string UncompressedSize = "message.uncompressed_size";

}