// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Attributes.Code;

/// <summary>Code Attributes.</summary>
public static class CodeAttributes
{
    /// <summary>
    /// The column number in <c>code.file.path</c> best representing the operation. It SHOULD point within the code unit named in <c>code.function.name</c>. This attribute MUST NOT be used on the Profile signal since the data is already captured in 'message Line'. This constraint is imposed to prevent redundancy and maintain data integrity.
    /// </summary>
    public const string ColumnNumber = "code.column.number";

    /// <summary>
    /// The source code file name that identifies the code unit as uniquely as possible (preferably an absolute file path). This attribute MUST NOT be used on the Profile signal since the data is already captured in 'message Function'. This constraint is imposed to prevent redundancy and maintain data integrity.
    /// </summary>
    public const string FilePath = "code.file.path";

    /// <summary>
    /// The method or function fully-qualified name without arguments. The value should fit the natural representation of the language runtime, which is also likely the same used within <c>code.stacktrace</c> attribute value. This attribute MUST NOT be used on the Profile signal since the data is already captured in 'message Function'. This constraint is imposed to prevent redundancy and maintain data integrity.
    /// </summary>
    /// <remarks>
    /// Values and format depends on each language runtime, thus it is impossible to provide an exhaustive list of examples.
    /// The values are usually the same (or prefixes of) the ones found in native stack trace representation stored in
    /// <c>code.stacktrace</c> without information on arguments.
    /// <p>
    /// Examples:
    /// <ul>
    ///   <li>Java method: <c>com.example.MyHttpService.serveRequest</c></li>
    ///   <li>Java anonymous class method: <c>com.mycompany.Main$1.myMethod</c></li>
    ///   <li>Java lambda method: <c>com.mycompany.Main$$Lambda/0x0000748ae4149c00.myMethod</c></li>
    ///   <li>PHP function: <c>GuzzleHttp\Client::transfer</c></li>
    ///   <li>Go function: <c>github.com/my/repo/pkg.foo.func5</c></li>
    ///   <li>Elixir: <c>OpenTelemetry.Ctx.new</c></li>
    ///   <li>Erlang: <c>opentelemetry_ctx:new</c></li>
    ///   <li>Rust: <c>playground::my_module::my_cool_func</c></li>
    ///   <li>C function: <c>fopen</c>.</li>
    /// </ul>
    /// </remarks>
    public const string FunctionName = "code.function.name";

    /// <summary>
    /// The line number in <c>code.file.path</c> best representing the operation. It SHOULD point within the code unit named in <c>code.function.name</c>. This attribute MUST NOT be used on the Profile signal since the data is already captured in 'message Line'. This constraint is imposed to prevent redundancy and maintain data integrity.
    /// </summary>
    public const string LineNumber = "code.line.number";

    /// <summary>
    /// A stacktrace as a string in the natural representation for the language runtime. The representation is identical to <a href="/docs/exceptions/exceptions-spans.md#stacktrace-representation"><c>exception.stacktrace</c></a>. This attribute MUST NOT be used on the Profile signal since the data is already captured in 'message Location'. This constraint is imposed to prevent redundancy and maintain data integrity.
    /// </summary>
    public const string Stacktrace = "code.stacktrace";
}
