// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Go;

/// <summary>Go Attributes (incubating).</summary>
public static class GoAttributes
{
    /// <summary>
    /// The detailed state of the CPU.
    /// </summary>
    /// <remarks>
    /// Value SHOULD match the specific CPU class reported by the Go runtime under <c>/cpu/classes/...</c>. The list of possible values is subject to change with the Go version used.
    /// </remarks>
    public const string CpuDetailedState = "go.cpu.detailed_state";

    /// <summary>
    /// The state of the CPU.
    /// </summary>
    public const string CpuState = "go.cpu.state";

    /// <summary>
    /// Values for the <c>CpuState</c> attribute.
    /// </summary>
    public static class CpuStateValues
    {
        /// <summary>
        /// CPU time spent performing garbage collection tasks.
        /// </summary>
        public const string Gc = "gc";

        /// <summary>
        /// Available CPU time not spent executing any Go or Go runtime code.
        /// </summary>
        public const string Idle = "idle";

        /// <summary>
        /// CPU time spent returning unused memory to the underlying platform.
        /// </summary>
        public const string Scavenge = "scavenge";

        /// <summary>
        /// CPU time spent running user Go code.
        /// </summary>
        public const string User = "user";
    }

    /// <summary>
    /// The detailed type of memory.
    /// </summary>
    /// <remarks>
    /// Value SHOULD match the specific memory class reported by the Go runtime under <c>/memory/classes/...</c>. The list of possible values is subject to change with the Go version used.
    /// </remarks>
    public const string MemoryDetailedType = "go.memory.detailed_type";

    /// <summary>
    /// The type of memory.
    /// </summary>
    public const string MemoryType = "go.memory.type";

    /// <summary>
    /// Values for the <c>MemoryType</c> attribute.
    /// </summary>
    public static class MemoryTypeValues
    {
        /// <summary>
        /// Memory used by the Go runtime, excluding other categories of memory usage described in this enumeration.
        /// </summary>
        public const string Other = "other";

        /// <summary>
        /// Memory allocated from the heap that is reserved for stack space, whether or not it is currently in-use.
        /// </summary>
        public const string Stack = "stack";
    }
}
