global using System.Buffers;
global using System.Collections.Frozen;
global using System.Globalization;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Security.Cryptography;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Data.Common;
global using System.Threading.Channels;
global using Microsoft.Extensions.Logging;
global using Qyl.Collector.Ingestion;
global using QylSessionActivity = Qyl.Collector.Primitives.SessionActivity;
global using QylTimeConversions = Qyl.Collector.Primitives.TimeConversions;
