// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.UserAgent;

/// <summary>UserAgent Attributes (incubating).</summary>
public static class UserAgentAttributes
{
    /// <summary>
    /// Name of the user-agent extracted from original. Usually refers to the browser's name.
    /// </summary>
    /// <remarks>
    /// <a href="https://uaparser.dev/#demo">Example</a> of extracting browser's name from original string. In the case of using a user-agent for non-browser products, such as microservices with multiple names/versions inside the <c>user_agent.original</c>, the most significant name SHOULD be selected. In such a scenario it should align with <c>user_agent.version</c>.
    /// </remarks>
    public const string Name = "user_agent.name";

    /// <summary>
    /// Human readable operating system name.
    /// </summary>
    /// <remarks>
    /// For mapping user agent strings to OS names, libraries such as <a href="https://github.com/ua-parser">ua-parser</a> can be utilized.
    /// </remarks>
    public const string OsName = "user_agent.os.name";

    /// <summary>
    /// The version string of the operating system as defined in <a href="/docs/resource/README.md#version-attributes">Version Attributes</a>.
    /// </summary>
    /// <remarks>
    /// For mapping user agent strings to OS versions, libraries such as <a href="https://github.com/ua-parser">ua-parser</a> can be utilized.
    /// </remarks>
    public const string OsVersion = "user_agent.os.version";

    /// <summary>
    /// Specifies the category of synthetic traffic, such as tests or bots.
    /// </summary>
    /// <remarks>
    /// This attribute MAY be derived from the contents of the <c>user_agent.original</c> attribute. Components that populate the attribute are responsible for determining what they consider to be synthetic bot or test traffic. This attribute can either be set for self-identification purposes, or on telemetry detected to be generated as a result of a synthetic request. This attribute is useful for distinguishing between genuine client traffic and synthetic traffic generated by bots or tests.
    /// </remarks>
    public const string SyntheticType = "user_agent.synthetic.type";

    /// <summary>
    /// Values for the <c>SyntheticType</c> attribute.
    /// </summary>
    public static class SyntheticTypeValues
    {
        /// <summary>
        /// Bot source.
        /// </summary>
        public const string Bot = "bot";

        /// <summary>
        /// Synthetic test source.
        /// </summary>
        public const string Test = "test";
    }

    /// <summary>
    /// Version of the user-agent extracted from original. Usually refers to the browser's version.
    /// </summary>
    /// <remarks>
    /// <a href="https://uaparser.dev/#demo">Example</a> of extracting browser's version from original string. In the case of using a user-agent for non-browser products, such as microservices with multiple names/versions inside the <c>user_agent.original</c>, the most significant version SHOULD be selected. In such a scenario it should align with <c>user_agent.name</c>.
    /// </remarks>
    public const string Version = "user_agent.version";
}
