// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Attributes.Telemetry;

/// <summary>Telemetry Attributes.</summary>
public static class TelemetryAttributes
{
    /// <summary>The name of the auto instrumentation agent or distribution, if used..</summary>
    /// <remarks>Official auto instrumentation agents and distributions SHOULD set the `telemetry.distro.name` attribute to a string starting with `opentelemetry-`, e.g. `opentelemetry-java-instrumentation`.</remarks>
    public const string DistroName = "telemetry.distro.name";

    /// <summary>The version string of the auto instrumentation agent or distribution, if used..</summary>
    public const string DistroVersion = "telemetry.distro.version";

    /// <summary>The language of the telemetry SDK..</summary>
    public const string SdkLanguage = "telemetry.sdk.language";

    /// <summary>Values for the <c>SdkLanguage</c> attribute.</summary>
    public static class SdkLanguageValues
    {
        /// <summary>.</summary>
        public const string Cpp = "cpp";
        /// <summary>.</summary>
        public const string Dotnet = "dotnet";
        /// <summary>.</summary>
        public const string Erlang = "erlang";
        /// <summary>.</summary>
        public const string Go = "go";
        /// <summary>.</summary>
        public const string Java = "java";
        /// <summary>.</summary>
        public const string Nodejs = "nodejs";
        /// <summary>.</summary>
        public const string Php = "php";
        /// <summary>.</summary>
        public const string Python = "python";
        /// <summary>.</summary>
        public const string Ruby = "ruby";
        /// <summary>.</summary>
        public const string Rust = "rust";
        /// <summary>.</summary>
        public const string Swift = "swift";
        /// <summary>.</summary>
        public const string Webjs = "webjs";
    }

    /// <summary>The name of the telemetry SDK as defined above..</summary>
    /// <remarks>The OpenTelemetry SDK MUST set the `telemetry.sdk.name` attribute to `opentelemetry`. If another SDK, like a fork or a vendor-provided implementation, is used, this SDK MUST set the `telemetry.sdk.name` attribute to the fully-qualified class or module name of this SDK's main entry point or another suitable identifier depending on the language. The identifier `opentelemetry` is reserved and MUST NOT be used in this case. All custom identifiers SHOULD be stable across different versions of an implementation.</remarks>
    public const string SdkName = "telemetry.sdk.name";

    /// <summary>The version string of the telemetry SDK..</summary>
    public const string SdkVersion = "telemetry.sdk.version";

}