// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Attributes.Deployment;

/// <summary>Deployment Attributes.</summary>
public static class DeploymentAttributes
{
    /// <summary>Name of the [deployment environment](https://wikipedia.org/wiki/Deployment_environment) (aka deployment tier)..</summary>
    /// <remarks>`deployment.environment.name` does not affect the uniqueness constraints defined through the `service.namespace`, `service.name` and `service.instance.id` resource attributes. This implies that resources carrying the following attribute combinations MUST be considered to be identifying the same service:  - `service.name=frontend`, `deployment.environment.name=production` - `service.name=frontend`, `deployment.environment.name=staging`.</remarks>
    public const string EnvironmentName = "deployment.environment.name";

    /// <summary>Values for the <c>EnvironmentName</c> attribute.</summary>
    public static class EnvironmentNameValues
    {
        /// <summary>Development environment.</summary>
        public const string Development = "development";
        /// <summary>Production environment.</summary>
        public const string Production = "production";
        /// <summary>Staging environment.</summary>
        public const string Staging = "staging";
        /// <summary>Testing environment.</summary>
        public const string Test = "test";
    }

}