// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Cassandra;

/// <summary>Cassandra Attributes (incubating).</summary>
public static class CassandraAttributes
{
    /// <summary>The consistency level of the query. Based on consistency values from [CQL](https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/dml/dmlConfigConsistency.html)..</summary>
    public const string ConsistencyLevel = "cassandra.consistency.level";

    /// <summary>Values for the <c>ConsistencyLevel</c> attribute.</summary>
    public static class ConsistencyLevelValues
    {
        /// <summary>All.</summary>
        public const string All = "all";
        /// <summary>Any.</summary>
        public const string Any = "any";
        /// <summary>Each Quorum.</summary>
        public const string EachQuorum = "each_quorum";
        /// <summary>Local One.</summary>
        public const string LocalOne = "local_one";
        /// <summary>Local Quorum.</summary>
        public const string LocalQuorum = "local_quorum";
        /// <summary>Local Serial.</summary>
        public const string LocalSerial = "local_serial";
        /// <summary>One.</summary>
        public const string One = "one";
        /// <summary>Quorum.</summary>
        public const string Quorum = "quorum";
        /// <summary>Serial.</summary>
        public const string Serial = "serial";
        /// <summary>Three.</summary>
        public const string Three = "three";
        /// <summary>Two.</summary>
        public const string Two = "two";
    }

    /// <summary>The data center of the coordinating node for a query..</summary>
    public const string CoordinatorDc = "cassandra.coordinator.dc";

    /// <summary>The ID of the coordinating node for a query..</summary>
    public const string CoordinatorId = "cassandra.coordinator.id";

    /// <summary>The fetch size used for paging, i.e. how many rows will be returned at once..</summary>
    public const string PageSize = "cassandra.page.size";

    /// <summary>Whether or not the query is idempotent..</summary>
    public const string QueryIdempotent = "cassandra.query.idempotent";

    /// <summary>The number of times a query was speculatively executed. Not set or `0` if the query was not executed speculatively..</summary>
    public const string SpeculativeExecutionCount = "cassandra.speculative_execution.count";

}