namespace Qyl.Collector.Storage;

// =============================================================================
// Storage Types - Internal to Qyl.Collector
// =============================================================================

/// <summary>
///     GenAI aggregated statistics for queries.
/// </summary>
public sealed record GenAiStats
{
    public long RequestCount { get; init; }
    public long TotalInputTokens { get; init; }
    public long TotalOutputTokens { get; init; }
    public double TotalCostUsd { get; init; }
    public double? AverageEvalScore { get; init; }
}

/// <summary>
///     Batch of spans for ingestion. Uses IReadOnlyList for immutable API contract.
/// </summary>
public sealed record SpanBatch(IReadOnlyList<SpanStorageRow> Spans);

/// <summary>
///     DuckDB storage row for spans. Matches generated DuckDbSchema.SpansDdl.
///     Uses UBIGINT timestamps (ulong) for OTel wire format compatibility.
///     Owner: Qyl.Collector | For external API use SpanRecord from protocol.
/// </summary>
/// <remarks>
///     Generator creates: AddParameters, MapFromReader, BuildMultiRowInsertSql.
///     Property order must match SELECT column order for MapFromReader.
/// </remarks>
[DuckDbTable("spans")]
public sealed partial record SpanStorageRow
{
    // Identity (PRIMARY KEY is span_id in new schema)
    public required string SpanId { get; init; }
    public required string TraceId { get; init; }
    public string? ParentSpanId { get; init; }
    public string? SessionId { get; init; }

    // Core span fields
    public required string Name { get; init; }
    public required byte Kind { get; init; } // TINYINT - SpanKind enum
    [DuckDbColumn(IsUBigInt = true)] public required ulong StartTimeUnixNano { get; init; } // UBIGINT
    [DuckDbColumn(IsUBigInt = true)] public required ulong EndTimeUnixNano { get; init; } // UBIGINT
    [DuckDbColumn(IsUBigInt = true)] public required ulong DurationNs { get; init; } // UBIGINT - computed
    public required byte StatusCode { get; init; } // TINYINT - StatusCode enum
    public string? StatusMessage { get; init; }

    // Resource attributes
    public string? ServiceName { get; init; }

    // GenAI attributes (OTel 1.40 - gen_ai.system is the provider name)
    public string? GenAiProviderName { get; init; }
    public string? GenAiRequestModel { get; init; }
    public string? GenAiResponseModel { get; init; }
    public long? GenAiInputTokens { get; init; } // BIGINT
    public long? GenAiOutputTokens { get; init; } // BIGINT
    public double? GenAiTemperature { get; init; } // DOUBLE
    public string? GenAiStopReason { get; init; }
    public string? GenAiToolName { get; init; }
    public string? GenAiToolCallId { get; init; }
    public double? GenAiCostUsd { get; init; } // DOUBLE

    // Flexible storage (JSON columns)
    public string? AttributesJson { get; init; }
    public string? ResourceJson { get; init; }

    // W3C Baggage passthrough (OTel context propagation)
    public string? BaggageJson { get; init; }

    // OTel schema URL tracking
    public string? SchemaUrl { get; init; }

    // Metadata (auto-generated by DB, exclude from INSERT)
    [DuckDbColumn(ExcludeFromInsert = true)]
    public DateTimeOffset? CreatedAt { get; init; }
}

/// <summary>
///     Storage statistics for monitoring.
/// </summary>
public sealed record StorageStats
{
    public long SpanCount { get; init; }
    public long SessionCount { get; init; }
    public long LogCount { get; init; }
    public ulong? OldestSpanTime { get; init; } // UnixNano
    public ulong? NewestSpanTime { get; init; } // UnixNano
}

/// <summary>
///     DuckDB storage row for logs. Maps to OTLP log records.
///     Owner: Qyl.Collector | For external API use LogRecord from protocol.
/// </summary>
public sealed record LogStorageRow
{
    public required string LogId { get; init; }
    public string? TraceId { get; init; }
    public string? SpanId { get; init; }
    public string? SessionId { get; init; }

    public required ulong TimeUnixNano { get; init; } // UBIGINT
    public ulong? ObservedTimeUnixNano { get; init; } // UBIGINT

    public required byte SeverityNumber { get; init; } // TINYINT
    public string? SeverityText { get; init; }
    public string? Body { get; init; }

    public string? ServiceName { get; init; }
    public string? AttributesJson { get; init; }
    public string? ResourceJson { get; init; }
    public string? SourceFile { get; init; }
    public int? SourceLine { get; init; }
    public int? SourceColumn { get; init; }
    public string? SourceMethod { get; init; }
    public DateTimeOffset? CreatedAt { get; init; }
}

// =============================================================================
// SSE Broadcasting - Telemetry streaming infrastructure
// =============================================================================

public interface ITelemetrySseBroadcaster : IAsyncDisposable
{
    int ClientCount { get; }
    ChannelReader<TelemetryMessage> Subscribe(Guid clientId);
    void Unsubscribe(Guid clientId);
    void Publish(TelemetryMessage item);
    void PublishSpans(SpanBatch batch);
}

public sealed class TelemetrySseBroadcaster : ITelemetrySseBroadcaster
{
    private readonly ConcurrentDictionary<Guid, Channel<TelemetryMessage>> _channels = new();
    private volatile bool _disposed;

    public int ClientCount => _channels.Count;

    public ChannelReader<TelemetryMessage> Subscribe(Guid clientId)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);

        var channel = Channel.CreateBounded<TelemetryMessage>(new BoundedChannelOptions(1000)
        {
            FullMode = BoundedChannelFullMode.DropOldest, SingleWriter = false, SingleReader = true
        });

        _channels[clientId] = channel;
        return channel.Reader;
    }

    public void Unsubscribe(Guid clientId)
    {
        if (_channels.TryRemove(clientId, out var channel))
            channel.Writer.TryComplete();
    }

    public void Publish(TelemetryMessage item)
    {
        if (_disposed) return;

        foreach (var channel in _channels.Values)
            channel.Writer.TryWrite(item);
    }

    public void PublishSpans(SpanBatch batch)
    {
        var message = new TelemetryMessage(TelemetrySignal.Spans, batch, TimeProvider.System.GetUtcNow());
        Publish(message);
    }

    public ValueTask DisposeAsync()
    {
        if (_disposed) return ValueTask.CompletedTask;
        _disposed = true;

        foreach (var channel in _channels.Values)
            channel.Writer.TryComplete();

        _channels.Clear();
        return ValueTask.CompletedTask;
    }
}

public enum TelemetrySignal : byte
{
    Connected = 0,
    Spans = 1,
    Metrics = 2,
    Logs = 3,
    Heartbeat = 4
}

public sealed record TelemetryMessage(
    TelemetrySignal Signal,
    object? Data,
    DateTimeOffset Timestamp);

public sealed record TelemetryEventDto(
    string EventType,
    object? Data,
    DateTimeOffset Timestamp);
