// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@7fe537301d17919af7d7eb65b32e9be35da2c497
// Schema: https://opentelemetry.io/schemas/1.40.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Azure;

/// <summary>Azure Attributes (incubating).</summary>
public static class AzureAttributes
{
    /// <summary>The unique identifier of the client instance..</summary>
    public const string ClientId = "azure.client.id";

    /// <summary>Cosmos client connection mode..</summary>
    public const string CosmosdbConnectionMode = "azure.cosmosdb.connection.mode";

    /// <summary>Values for <see cref="CosmosdbConnectionMode"/>.</summary>
    public static class CosmosdbConnectionModeValues
    {
        /// <summary>Direct connection..</summary>
        public const string Direct = "direct";
        /// <summary>Gateway (HTTP) connection..</summary>
        public const string Gateway = "gateway";
    }

    /// <summary>Account or request [consistency level](https://learn.microsoft.com/azure/cosmos-db/consistency-levels)..</summary>
    public const string CosmosdbConsistencyLevel = "azure.cosmosdb.consistency.level";

    /// <summary>Values for <see cref="CosmosdbConsistencyLevel"/>.</summary>
    public static class CosmosdbConsistencyLevelValues
    {
        /// <summary>Bounded Staleness.</summary>
        public const string BoundedStaleness = "BoundedStaleness";
        /// <summary>Consistent Prefix.</summary>
        public const string ConsistentPrefix = "ConsistentPrefix";
        /// <summary>Eventual.</summary>
        public const string Eventual = "Eventual";
        /// <summary>Session.</summary>
        public const string Session = "Session";
        /// <summary>Strong.</summary>
        public const string Strong = "Strong";
    }

    /// <summary>List of regions contacted during operation in the order that they were contacted. If there is more than one region listed, it indicates that the operation was performed on multiple regions i.e. cross-regional call..</summary>
    /// <remarks>Region name matches the format of `displayName` in [Azure Location API](https://learn.microsoft.com/rest/api/resources/subscriptions/list-locations)</remarks>
    public const string CosmosdbOperationContactedRegions = "azure.cosmosdb.operation.contacted_regions";

    /// <summary>The number of request units consumed by the operation..</summary>
    public const string CosmosdbOperationRequestCharge = "azure.cosmosdb.operation.request_charge";

    /// <summary>Request payload size in bytes..</summary>
    public const string CosmosdbRequestBodySize = "azure.cosmosdb.request.body.size";

    /// <summary>Cosmos DB sub status code..</summary>
    public const string CosmosdbResponseSubStatusCode = "azure.cosmosdb.response.sub_status_code";

    /// <summary>[Azure Resource Provider Namespace](https://learn.microsoft.com/azure/azure-resource-manager/management/azure-services-resource-providers) as recognized by the client..</summary>
    public const string ResourceProviderNamespace = "azure.resource_provider.namespace";

    /// <summary>The unique identifier of the service request. It's generated by the Azure service and returned with the response..</summary>
    public const string ServiceRequestId = "azure.service.request.id";

}