// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@7fe537301d17919af7d7eb65b32e9be35da2c497
// Schema: https://opentelemetry.io/schemas/1.40.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Vcs;

/// <summary>Vcs Attributes (incubating).</summary>
public static class VcsAttributes
{
    /// <summary>The ID of the change (pull request/merge request/changelist) if applicable. This is usually a unique (within repository) identifier generated by the VCS system..</summary>
    public const string ChangeId = "vcs.change.id";

    /// <summary>The state of the change (pull request/merge request/changelist)..</summary>
    public const string ChangeState = "vcs.change.state";

    /// <summary>Values for the <c>ChangeState</c> attribute.</summary>
    public static class ChangeStateValues
    {
        /// <summary>Closed means the merge request has been closed without merging. This can happen for various reasons, such as the changes being deemed unnecessary, the issue being resolved in another way, or the author deciding to withdraw the request..</summary>
        public const string Closed = "closed";
        /// <summary>Merged indicates that the change has been successfully integrated into the target codebase..</summary>
        public const string Merged = "merged";
        /// <summary>Open means the change is currently active and under review. It hasn't been merged into the target branch yet, and it's still possible to make changes or add comments..</summary>
        public const string Open = "open";
        /// <summary>WIP (work-in-progress, draft) means the change is still in progress and not yet ready for a full review. It might still undergo significant changes..</summary>
        public const string Wip = "wip";
    }

    /// <summary>The human readable title of the change (pull request/merge request/changelist). This title is often a brief summary of the change and may get merged in to a ref as the commit summary..</summary>
    public const string ChangeTitle = "vcs.change.title";

    /// <summary>The type of line change being measured on a branch or change..</summary>
    public const string LineChangeType = "vcs.line_change.type";

    /// <summary>Values for the <c>LineChangeType</c> attribute.</summary>
    public static class LineChangeTypeValues
    {
        /// <summary>How many lines were added..</summary>
        public const string Added = "added";
        /// <summary>How many lines were removed..</summary>
        public const string Removed = "removed";
    }

    /// <summary>The group owner within the version control system..</summary>
    public const string OwnerName = "vcs.owner.name";

    /// <summary>The name of the version control system provider..</summary>
    public const string ProviderName = "vcs.provider.name";

    /// <summary>Values for the <c>ProviderName</c> attribute.</summary>
    public static class ProviderNameValues
    {
        /// <summary>[Bitbucket](https://bitbucket.org).</summary>
        public const string Bitbucket = "bitbucket";
        /// <summary>[Gitea](https://gitea.io).</summary>
        public const string Gitea = "gitea";
        /// <summary>[GitHub](https://github.com).</summary>
        public const string Github = "github";
        /// <summary>[GitLab](https://gitlab.com).</summary>
        public const string Gitlab = "gitlab";
        /// <summary>Deprecated, use `gitea` instead..</summary>
        [global::System.Obsolete("{\"note\": \"Replaced by `gitea`.\", \"reason\": \"renamed\", \"renamed_to\": \"gitea\"}", false)]
        public const string Gittea = "gittea";
    }

    /// <summary>The name of the [reference](https://git-scm.com/docs/gitglossary#def_ref) such as **branch** or **tag** in the repository..</summary>
    /// <remarks>`base` refers to the starting point of a change. For example, `main` would be the base reference of type branch if you've created a new reference of type branch from it and created new commits.</remarks>
    public const string RefBaseName = "vcs.ref.base.name";

    /// <summary>The revision, literally [revised version](https://www.merriam-webster.com/dictionary/revision), The revision most often refers to a commit object in Git, or a revision number in SVN..</summary>
    /// <remarks>`base` refers to the starting point of a change. For example, `main` would be the base reference of type branch if you've created a new reference of type branch from it and created new commits. The revision can be a full [hash value (see glossary)](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf), of the recorded change to a ref within a repository pointing to a commit [commit](https://git-scm.com/docs/git-commit) object. It does not necessarily have to be a hash; it can simply define a [revision number](https://svnbook.red-bean.com/en/1.7/svn.tour.revs.specifiers.html) which is an integer that is monotonically increasing. In cases where it is identical to the `ref.base.name`, it SHOULD still be included. It is up to the implementer to decide which value to set as the revision based on the VCS system and situational context.</remarks>
    public const string RefBaseRevision = "vcs.ref.base.revision";

    /// <summary>The type of the [reference](https://git-scm.com/docs/gitglossary#def_ref) in the repository..</summary>
    /// <remarks>`base` refers to the starting point of a change. For example, `main` would be the base reference of type branch if you've created a new reference of type branch from it and created new commits.</remarks>
    public const string RefBaseType = "vcs.ref.base.type";

    /// <summary>Values for the <c>RefBaseType</c> attribute.</summary>
    public static class RefBaseTypeValues
    {
        /// <summary>[branch](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefbranchabranch).</summary>
        public const string Branch = "branch";
        /// <summary>[tag](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftagatag).</summary>
        public const string Tag = "tag";
    }

    /// <summary>The name of the [reference](https://git-scm.com/docs/gitglossary#def_ref) such as **branch** or **tag** in the repository..</summary>
    /// <remarks>`head` refers to where you are right now; the current reference at a given time.</remarks>
    public const string RefHeadName = "vcs.ref.head.name";

    /// <summary>The revision, literally [revised version](https://www.merriam-webster.com/dictionary/revision), The revision most often refers to a commit object in Git, or a revision number in SVN..</summary>
    /// <remarks>`head` refers to where you are right now; the current reference at a given time.The revision can be a full [hash value (see glossary)](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf), of the recorded change to a ref within a repository pointing to a commit [commit](https://git-scm.com/docs/git-commit) object. It does not necessarily have to be a hash; it can simply define a [revision number](https://svnbook.red-bean.com/en/1.7/svn.tour.revs.specifiers.html) which is an integer that is monotonically increasing. In cases where it is identical to the `ref.head.name`, it SHOULD still be included. It is up to the implementer to decide which value to set as the revision based on the VCS system and situational context.</remarks>
    public const string RefHeadRevision = "vcs.ref.head.revision";

    /// <summary>The type of the [reference](https://git-scm.com/docs/gitglossary#def_ref) in the repository..</summary>
    /// <remarks>`head` refers to where you are right now; the current reference at a given time.</remarks>
    public const string RefHeadType = "vcs.ref.head.type";

    /// <summary>Values for the <c>RefHeadType</c> attribute.</summary>
    public static class RefHeadTypeValues
    {
        /// <summary>[branch](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefbranchabranch).</summary>
        public const string Branch = "branch";
        /// <summary>[tag](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftagatag).</summary>
        public const string Tag = "tag";
    }

    /// <summary>The type of the [reference](https://git-scm.com/docs/gitglossary#def_ref) in the repository..</summary>
    public const string RefType = "vcs.ref.type";

    /// <summary>Values for the <c>RefType</c> attribute.</summary>
    public static class RefTypeValues
    {
        /// <summary>[branch](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefbranchabranch).</summary>
        public const string Branch = "branch";
        /// <summary>[tag](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftagatag).</summary>
        public const string Tag = "tag";
    }

    /// <summary>Deprecated, use `vcs.change.id` instead..</summary>
    [global::System.Obsolete("Replaced by vcs.change.id.", false)]
    public const string RepositoryChangeId = "vcs.repository.change.id";

    /// <summary>Deprecated, use `vcs.change.title` instead..</summary>
    [global::System.Obsolete("Replaced by vcs.change.title.", false)]
    public const string RepositoryChangeTitle = "vcs.repository.change.title";

    /// <summary>The human readable name of the repository. It SHOULD NOT include any additional identifier like Group/SubGroup in GitLab or organization in GitHub..</summary>
    /// <remarks>Due to it only being the name, it can clash with forks of the same repository if collecting telemetry across multiple orgs or groups in the same backends.</remarks>
    public const string RepositoryName = "vcs.repository.name";

    /// <summary>Deprecated, use `vcs.ref.head.name` instead..</summary>
    [global::System.Obsolete("Replaced by vcs.ref.head.name.", false)]
    public const string RepositoryRefName = "vcs.repository.ref.name";

    /// <summary>Deprecated, use `vcs.ref.head.revision` instead..</summary>
    [global::System.Obsolete("Replaced by vcs.ref.head.revision.", false)]
    public const string RepositoryRefRevision = "vcs.repository.ref.revision";

    /// <summary>Deprecated, use `vcs.ref.head.type` instead..</summary>
    [global::System.Obsolete("Replaced by vcs.ref.head.type.", false)]
    public const string RepositoryRefType = "vcs.repository.ref.type";

    /// <summary>Values for the <c>RepositoryRefType</c> attribute.</summary>
    public static class RepositoryRefTypeValues
    {
        /// <summary>[branch](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefbranchabranch).</summary>
        public const string Branch = "branch";
        /// <summary>[tag](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftagatag).</summary>
        public const string Tag = "tag";
    }

    /// <summary>The [canonical URL](https://support.google.com/webmasters/answer/10347851) of the repository providing the complete HTTP(S) address in order to locate and identify the repository through a browser..</summary>
    /// <remarks>In Git Version Control Systems, the canonical URL SHOULD NOT include the `.git` extension.</remarks>
    public const string RepositoryUrlFull = "vcs.repository.url.full";

    /// <summary>The type of revision comparison..</summary>
    public const string RevisionDeltaDirection = "vcs.revision_delta.direction";

    /// <summary>Values for the <c>RevisionDeltaDirection</c> attribute.</summary>
    public static class RevisionDeltaDirectionValues
    {
        /// <summary>How many revisions the change is ahead of the target ref..</summary>
        public const string Ahead = "ahead";
        /// <summary>How many revisions the change is behind the target ref..</summary>
        public const string Behind = "behind";
    }

}