// Copyright (c) 2025-2026 ancplua

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Qyl.Instrumentation.Generators.CallSites;
using Qyl.Instrumentation.Generators.Emitters;

namespace Qyl.Instrumentation.Generators;

/// <summary>
///     Per-concern generator that emits <c>QylGeneratedRegistry.g.cs</c> — the single
///     compile-time registry class that the intercepted <c>builder.Build()</c> site calls
///     to auto-wire consumer code tagged with any of:
///     <list type="bullet">
///         <item><c>[QylHostedService]</c> → <c>RegisterQylHostedServices</c>.</item>
///         <item><c>[QylService]</c> → <c>RegisterQylServices</c>.</item>
///         <item><c>[QylHealthCheck]</c> → <c>RegisterQylHealthChecks</c>.</item>
///         <item><c>[QylMapEndpoints]</c> → <c>MapQylGeneratedEndpoints</c> (consumer-invoked).</item>
///     </list>
/// </summary>
/// <remarks>
///     The registry class is always emitted when the Qyl runtime is referenced — even when
///     no consumer attribute sites exist — because the builder interceptor generated by
///     <see cref="ServiceDefaultsSourceGenerator" /> unconditionally calls its three
///     <c>RegisterQyl*</c> methods.
/// </remarks>
[Generator]
public sealed class RegistryGenerator : IIncrementalGenerator
{
    private const string GeneratedFileName = "QylGeneratedRegistry.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var runtimeAvailable = context.CompilationProvider
            .Select(GeneratorPipelineHelpers.IsQylRuntimeReferenced);

        var hostedServices = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                HostedServiceAnalyzer.HostedServiceAttributeMetadataName,
                HostedServiceAnalyzer.CouldBeHostedServiceClass,
                HostedServiceAnalyzer.Extract)
            .WhereNotNull()
            .WithTrackingName(nameof(RegistryGenerator) + ".HostedServices");

        var mapEndpoints = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                MapEndpointsAnalyzer.MapEndpointsAttributeMetadataName,
                MapEndpointsAnalyzer.CouldBeMapEndpointsMethod,
                MapEndpointsAnalyzer.Extract)
            .WhereNotNull()
            .WithTrackingName(nameof(RegistryGenerator) + ".MapEndpoints");

        var services = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                QylServiceAnalyzer.QylServiceAttributeMetadataName,
                QylServiceAnalyzer.CouldBeQylServiceClass,
                QylServiceAnalyzer.Extract)
            .WhereNotNull()
            .WithTrackingName(nameof(RegistryGenerator) + ".Services");

        var healthChecks = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                QylHealthCheckAnalyzer.QylHealthCheckAttributeMetadataName,
                QylHealthCheckAnalyzer.CouldBeHealthCheckClass,
                QylHealthCheckAnalyzer.Extract)
            .WhereNotNull()
            .WithTrackingName(nameof(RegistryGenerator) + ".HealthChecks");

        var combined = hostedServices.CollectAsEquatableArray()
            .Combine(mapEndpoints.CollectAsEquatableArray())
            .Combine(services.CollectAsEquatableArray())
            .Combine(healthChecks.CollectAsEquatableArray())
            .Combine(runtimeAvailable);

        context.RegisterSourceOutput(
            combined,
            static (spc, input) =>
            {
                var ((((hosted, endpoints), svcs), health), runtime) = input;
                if (!runtime) return;

                var source = HostedServiceEmitter.Emit(
                    hosted.IsDefaultOrEmpty ? [] : hosted.AsImmutableArray(),
                    endpoints.IsDefaultOrEmpty ? [] : endpoints.AsImmutableArray(),
                    svcs.IsDefaultOrEmpty ? [] : svcs.AsImmutableArray(),
                    health.IsDefaultOrEmpty ? [] : health.AsImmutableArray());

                spc.AddSource(GeneratedFileName, SourceText.From(source, Encoding.UTF8));
            });
    }
}
