
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;
using Qyl.Instrumentation.Generators.Models;

namespace Qyl.Instrumentation.Generators;

[Generator]
public sealed class ServiceDefaultsSourceGenerator : IIncrementalGenerator
{
    private const string BuilderInterceptorsFile = "Intercepts.g.cs";

    private const string InterceptsLocationAttributeDeclaration = """
                                                                  using Qyl.Instrumentation;

                                                                  namespace System.Runtime.CompilerServices
                                                                  {
                                                                      [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                                                                      file sealed class InterceptsLocationAttribute(int version, string data) : global::System.Attribute
                                                                      {
                                                                          public int Version { get; } = version;
                                                                          public string Data { get; } = data;
                                                                      }
                                                                  }
                                                                  """;

    private const string InterceptorsNamespaceOpen = """
                                                     namespace Qyl.Instrumentation.Generators
                                                     {
                                                         file static partial class Interceptors
                                                         {
                                                     """;

    private const string InterceptorsNamespaceClose = """
                                                          }
                                                      }
                                                      """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var builderCallSites = context.SyntaxProvider
            .CreateSyntaxProvider(CouldBeBuildInvocation, ExtractBuilderCallSite)
            .WhereNotNull()
            .WithTrackingName(PipelineStage.BuilderCallSitesDiscovered);

        context.RegisterSourceOutput(builderCallSites.CollectAsEquatableArray(), EmitBuilderInterceptors);
    }


    private static bool CouldBeBuildInvocation(SyntaxNode node, CancellationToken _) =>
        string.Equals(IncrementalPipelineHelpers.GetInvokedMethodName(node), "Build", StringComparison.Ordinal);

    private static BuilderCallSite? ExtractBuilderCallSite(
        GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        if (!IncrementalPipelineHelpers.TryGetInvocationOperation(context, cancellationToken, out var invocation))
            return null;

        if (!IsWebApplicationBuilderBuildCall(invocation, context.SemanticModel.Compilation))
            return null;

        if (IncrementalPipelineHelpers.IsAlreadyIntercepted(context, cancellationToken))
            return null;

        var location = context.SemanticModel.GetInterceptableLocation(
            (InvocationExpressionSyntax)context.Node, cancellationToken);

        return location is null
            ? null
            : new BuilderCallSite(
                IncrementalPipelineHelpers.FormatSortKey(context.Node),
                location);
    }

    private static bool IsWebApplicationBuilderBuildCall(IInvocationOperation invocation, Compilation compilation) =>
        invocation.IsMethodNamed(
            compilation.GetTypeByMetadataName(GeneratorPipelineHelpers.WebApplicationBuilderTypeName),
            "Build");


    private static void EmitBuilderInterceptors(
        SourceProductionContext context,
        EquatableArray<BuilderCallSite> input)
    {
        var callSites = input.AsImmutableArray();
        if (callSites.IsEmpty)
            return;

        var source = GenerateBuilderInterceptorSource(callSites);
        context.AddSource(BuilderInterceptorsFile, SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateBuilderInterceptorSource(ImmutableArray<BuilderCallSite> callSites)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine(GeneratedCodeHelpers.NullableEnable);
        sb.AppendLine();
        sb.AppendLine(InterceptsLocationAttributeDeclaration);
        sb.AppendLine(InterceptorsNamespaceOpen);

        var index = 0;
        foreach (var callSite in callSites.OrderBy(static c => c.SortKey, StringComparer.Ordinal))
        {
            AppendBuildInterceptorMethod(sb, callSite, index);
            index++;
        }

        sb.AppendLine(InterceptorsNamespaceClose);
        return sb.ToString();
    }

    private static void AppendBuildInterceptorMethod(
        StringBuilder sb,
        BuilderCallSite callSite,
        int index)
    {
        var displayLocation = callSite.Location.GetDisplayLocation();
        var interceptAttribute = callSite.Location.GetInterceptsLocationAttributeSyntax();

        // Keep ASP.NET Core instrumentation registration independent; composing it into this
        // Build() interceptor collides with OpenTelemetry's interceptor (CS9153).
        sb.AppendLine($$"""
                                // Intercepted call at {{displayLocation}}
                                {{interceptAttribute}}
                                public static global::{{GeneratorPipelineHelpers.WebApplicationTypeName}} Intercept_Build{{index}}(
                                    this global::{{GeneratorPipelineHelpers.WebApplicationBuilderTypeName}} builder)
                                {
                                    builder.TryUseQylConventions();
                                    var app = builder.Build();
                                    app.MapQylDefaultEndpoints();
                                    return app;
                                }
                        """);
    }

    private static class PipelineStage
    {
        public const string BuilderCallSitesDiscovered = nameof(BuilderCallSitesDiscovered);
    }
}
