// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@7fe537301d17919af7d7eb65b32e9be35da2c497
// Schema: https://opentelemetry.io/schemas/1.40.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Attributes.Otel;

/// <summary>Otel Attributes.</summary>
public static class OtelAttributes
{
    /// <summary>The name of the instrumentation scope - (`InstrumentationScope.Name` in OTLP)..</summary>
    public const string ScopeName = "otel.scope.name";

    /// <summary>The version of the instrumentation scope - (`InstrumentationScope.Version` in OTLP)..</summary>
    public const string ScopeVersion = "otel.scope.version";

    /// <summary>Name of the code, either "OK" or "ERROR". MUST NOT be set if the status code is UNSET..</summary>
    public const string StatusCode = "otel.status_code";

    /// <summary>Values for the <c>StatusCode</c> attribute.</summary>
    public static class StatusCodeValues
    {
        /// <summary>The operation contains an error..</summary>
        public const string Error = "ERROR";
        /// <summary>The operation has been validated by an Application developer or Operator to have completed successfully..</summary>
        public const string Ok = "OK";
    }

    /// <summary>Description of the Status if it has a value, otherwise not set..</summary>
    public const string StatusDescription = "otel.status_description";

}