import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { dirname } from "node:path";
import type { EmitContext, Model, ModelProperty, Program } from "@typespec/compiler";
import { emitFile, navigateProgram } from "@typespec/compiler";
import {
  getColumnTypeOverride,
  getIndexes,
  getTableName,
  isPrimaryKey,
} from "./decorators.js";
import { reportDiagnostic } from "./lib.js";
import { mapType } from "./type-map.js";

const HEADER = "﻿// <auto-generated/>\n// Copyright (c) 2025-2026 ancplua\n#nullable enable\n";

interface Column {
  name: string;
  type: string;
  notNull: boolean;
  primaryKey: boolean;
}

interface Table {
  name: string;
  model: Model;
  columns: Column[];
  indexes: { name: string; column: string }[];
}

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  if (program.compilerOptions.noEmit) return;

  const tables: Table[] = [];
  navigateProgram(program, {
    model: (m) => {
      const name = getTableName(program, m);
      if (!name) return;
      tables.push(collectTable(program, m, name));
    },
  });

  if (tables.length === 0) return;

  for (const t of tables) {
    if (!t.columns.some((c) => c.primaryKey)) {
      reportDiagnostic(program, {
        code: "missing-primary-key",
        target: t.model,
        format: { name: t.name },
      });
    }
  }

  const ddl = renderFullDdl(tables);
  const version = hashVersion(ddl);
  const content = renderClass(tables, version);
  const path = `${context.emitterOutputDir}/DuckDbSchema.g.cs`;

  const prior = readPrior(path);
  if (prior && prior.version !== version) {
    const migration = diffMigration(prior.tables, tables);
    if (migration.length > 0) {
      const migPath = `${dirname(path)}/Migrations/${prior.version}-to-${version}.sql`;
      await emitFile(program, { path: migPath, content: migration.join("\n") + "\n" });
    }
  }

  await emitFile(program, { path, content });
}

function collectTable(program: Program, model: Model, name: string): Table {
  const columns: Column[] = [];
  const indexes: { name: string; column: string }[] = [];
  for (const [, prop] of model.properties) {
    const override = getColumnTypeOverride(program, prop);
    const type = override ?? mapType(program, prop.type);
    columns.push({
      name: prop.name,
      type,
      notNull: !prop.optional,
      primaryKey: isPrimaryKey(program, prop),
    });
    for (const idx of getIndexes(program, prop)) {
      indexes.push({ name: idx, column: prop.name });
    }
  }
  return { name, model, columns, indexes };
}

function renderFullDdl(tables: Table[]): string {
  return tables.map(renderTableDdl).join("\n\n");
}

function renderTableDdl(t: Table): string {
  const cols = t.columns.map((c) => {
    const parts = [`  ${c.name} ${c.type}`];
    if (c.notNull) parts[0] += " NOT NULL";
    if (c.primaryKey) parts[0] += " PRIMARY KEY";
    return parts[0];
  });
  const body = cols.join(",\n");
  const indexDdl = t.indexes
    .map((i) => `CREATE INDEX IF NOT EXISTS ${i.name} ON ${t.name} (${i.column});`)
    .join("\n");
  const base = `CREATE TABLE IF NOT EXISTS ${t.name} (\n${body}\n);`;
  return indexDdl.length ? `${base}\n${indexDdl}` : base;
}

function renderClass(tables: Table[], version: number): string {
  const out: string[] = [HEADER];
  out.push("namespace Qyl.Collector.Storage;\n");
  out.push("public static class DuckDbSchema");
  out.push("{");
  out.push(`    public const int Version = ${version};\n`);
  for (const t of tables) {
    const ddl = renderTableDdl(t).replace(/"/g, '""');
    const propName = pascal(t.name);
    out.push(`    public const string ${propName}Ddl = @"${ddl}";\n`);
  }
  out.push("    public static string GetSchemaDdl() => string.Join(\"\\n\\n\", new[]");
  out.push("    {");
  for (const t of tables) {
    out.push(`        ${pascal(t.name)}Ddl,`);
  }
  out.push("    });");
  out.push("}");
  return out.join("\n") + "\n";
}

function pascal(s: string): string {
  return s
    .split(/[_\s]/)
    .filter((x) => x.length > 0)
    .map((x) => x[0].toUpperCase() + x.slice(1))
    .join("");
}

function hashVersion(ddl: string): number {
  const hex = createHash("sha256").update(ddl).digest("hex").slice(0, 8);
  const n = parseInt(hex, 16);
  // Clamp to positive int32 (DuckDB Version is int in C#)
  return n > 0x7fffffff ? n - 0x80000000 : n;
}

function readPrior(path: string): { version: number; tables: Map<string, Column[]> } | undefined {
  if (!existsSync(path)) return undefined;
  const content = readFileSync(path, "utf-8");
  const versionMatch = content.match(/public const int Version = (-?\d+);/);
  if (!versionMatch) return undefined;
  const version = parseInt(versionMatch[1], 10);
  const tables = new Map<string, Column[]>();
  const re = /public const string (\w+)Ddl = @"([\s\S]*?)";/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(content)) !== null) {
    const cols = parseDdlColumns(m[2]);
    tables.set(unPascal(m[1]), cols);
  }
  return { version, tables };
}

function parseDdlColumns(ddl: string): Column[] {
  const colBlock = ddl.match(/\(([\s\S]*?)\);/);
  if (!colBlock) return [];
  return colBlock[1]
    .split(",")
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.toUpperCase().startsWith("CREATE INDEX"))
    .map<Column>((line) => {
      const parts = line.split(/\s+/);
      return {
        name: parts[0],
        type: parts[1] ?? "VARCHAR",
        notNull: /NOT NULL/i.test(line),
        primaryKey: /PRIMARY KEY/i.test(line),
      };
    });
}

function unPascal(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, "$1_$2").toLowerCase();
}

function diffMigration(prior: Map<string, Column[]>, current: Table[]): string[] {
  const out: string[] = [];
  const currentMap = new Map(current.map((t) => [t.name, t] as const));
  for (const [name, t] of currentMap) {
    const before = prior.get(name);
    if (!before) {
      out.push(renderTableDdl(t));
      continue;
    }
    const beforeByName = new Map(before.map((c) => [c.name, c] as const));
    for (const col of t.columns) {
      const priorCol = beforeByName.get(col.name);
      if (!priorCol) {
        const nn = col.notNull ? " NOT NULL" : "";
        out.push(`ALTER TABLE ${name} ADD COLUMN ${col.name} ${col.type}${nn};`);
      } else if (priorCol.type.toUpperCase() !== col.type.toUpperCase()) {
        out.push(`ALTER TABLE ${name} ALTER ${col.name} TYPE ${col.type};`);
      }
    }
    for (const priorCol of before) {
      if (!t.columns.some((c) => c.name === priorCol.name)) {
        out.push(`ALTER TABLE ${name} DROP COLUMN ${priorCol.name};`);
      }
    }
  }
  for (const [name] of prior) {
    if (!currentMap.has(name)) {
      out.push(`DROP TABLE ${name};`);
    }
  }
  return out;
}

export function _internal_getProps(model: Model): ModelProperty[] {
  return [...model.properties.values()];
}
