// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Db;

/// <summary>Db Attributes (incubating).</summary>
public static class DbAttributes
{
    /// <summary>
    /// Deprecated, use <c>cassandra.consistency.level</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by cassandra.consistency.level.", false)]
    public const string CassandraConsistencyLevel = "db.cassandra.consistency_level";

    /// <summary>
    /// Values for the <c>CassandraConsistencyLevel</c> attribute.
    /// </summary>
    public static class CassandraConsistencyLevelValues
    {
        /// <summary>
        /// all.
        /// </summary>
        public const string All = "all";

        /// <summary>
        /// any.
        /// </summary>
        public const string Any = "any";

        /// <summary>
        /// each_quorum.
        /// </summary>
        public const string EachQuorum = "each_quorum";

        /// <summary>
        /// local_one.
        /// </summary>
        public const string LocalOne = "local_one";

        /// <summary>
        /// local_quorum.
        /// </summary>
        public const string LocalQuorum = "local_quorum";

        /// <summary>
        /// local_serial.
        /// </summary>
        public const string LocalSerial = "local_serial";

        /// <summary>
        /// one.
        /// </summary>
        public const string One = "one";

        /// <summary>
        /// quorum.
        /// </summary>
        public const string Quorum = "quorum";

        /// <summary>
        /// serial.
        /// </summary>
        public const string Serial = "serial";

        /// <summary>
        /// three.
        /// </summary>
        public const string Three = "three";

        /// <summary>
        /// two.
        /// </summary>
        public const string Two = "two";
    }

    /// <summary>
    /// Deprecated, use <c>cassandra.coordinator.dc</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by cassandra.coordinator.dc.", false)]
    public const string CassandraCoordinatorDc = "db.cassandra.coordinator.dc";

    /// <summary>
    /// Deprecated, use <c>cassandra.coordinator.id</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by cassandra.coordinator.id.", false)]
    public const string CassandraCoordinatorId = "db.cassandra.coordinator.id";

    /// <summary>
    /// Deprecated, use <c>cassandra.query.idempotent</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by cassandra.query.idempotent.", false)]
    public const string CassandraIdempotence = "db.cassandra.idempotence";

    /// <summary>
    /// Deprecated, use <c>cassandra.page.size</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by cassandra.page.size.", false)]
    public const string CassandraPageSize = "db.cassandra.page_size";

    /// <summary>
    /// Deprecated, use <c>cassandra.speculative_execution.count</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by cassandra.speculative_execution.count.", false)]
    public const string CassandraSpeculativeExecutionCount = "db.cassandra.speculative_execution_count";

    /// <summary>
    /// Deprecated, use <c>db.collection.name</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by db.collection.name.", false)]
    public const string CassandraTable = "db.cassandra.table";

    /// <summary>
    /// The name of the connection pool; unique within the instrumented application. In case the connection pool implementation doesn't provide a name, instrumentation SHOULD use a combination of parameters that would make the name unique, for example, combining attributes <c>server.address</c>, <c>server.port</c>, and <c>db.namespace</c>, formatted as <c>server.address:server.port/db.namespace</c>. Instrumentations that generate connection pool name following different patterns SHOULD document it.
    /// </summary>
    public const string ClientConnectionPoolName = "db.client.connection.pool.name";

    /// <summary>
    /// The state of a connection in the pool.
    /// </summary>
    public const string ClientConnectionState = "db.client.connection.state";

    /// <summary>
    /// Values for the <c>ClientConnectionState</c> attribute.
    /// </summary>
    public static class ClientConnectionStateValues
    {
        /// <summary>
        /// idle.
        /// </summary>
        public const string Idle = "idle";

        /// <summary>
        /// used.
        /// </summary>
        public const string Used = "used";
    }

    /// <summary>
    /// Deprecated, use <c>db.client.connection.pool.name</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by db.client.connection.pool.name.", false)]
    public const string ClientConnectionsPoolName = "db.client.connections.pool.name";

    /// <summary>
    /// Deprecated, use <c>db.client.connection.state</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by db.client.connection.state.", false)]
    public const string ClientConnectionsState = "db.client.connections.state";

    /// <summary>
    /// Values for the <c>ClientConnectionsState</c> attribute.
    /// </summary>
    public static class ClientConnectionsStateValues
    {
        /// <summary>
        /// idle.
        /// </summary>
        public const string Idle = "idle";

        /// <summary>
        /// used.
        /// </summary>
        public const string Used = "used";
    }

    /// <summary>
    /// Deprecated, use <c>server.address</c>, <c>server.port</c> attributes instead.
    /// </summary>
    [global::System.Obsolete("Replaced by `server.address` and `server.port`.", false)]
    public const string ConnectionString = "db.connection_string";

    /// <summary>
    /// Deprecated, use <c>azure.client.id</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by azure.client.id.", false)]
    public const string CosmosdbClientId = "db.cosmosdb.client_id";

    /// <summary>
    /// Deprecated, use <c>azure.cosmosdb.connection.mode</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by azure.cosmosdb.connection.mode.", false)]
    public const string CosmosdbConnectionMode = "db.cosmosdb.connection_mode";

    /// <summary>
    /// Values for the <c>CosmosdbConnectionMode</c> attribute.
    /// </summary>
    public static class CosmosdbConnectionModeValues
    {
        /// <summary>
        /// Direct connection.
        /// </summary>
        public const string Direct = "direct";

        /// <summary>
        /// Gateway (HTTP) connection.
        /// </summary>
        public const string Gateway = "gateway";
    }

    /// <summary>
    /// Deprecated, use <c>cosmosdb.consistency.level</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by azure.cosmosdb.consistency.level.", false)]
    public const string CosmosdbConsistencyLevel = "db.cosmosdb.consistency_level";

    /// <summary>
    /// Values for the <c>CosmosdbConsistencyLevel</c> attribute.
    /// </summary>
    public static class CosmosdbConsistencyLevelValues
    {
        /// <summary>
        /// bounded_staleness.
        /// </summary>
        public const string BoundedStaleness = "BoundedStaleness";

        /// <summary>
        /// consistent_prefix.
        /// </summary>
        public const string ConsistentPrefix = "ConsistentPrefix";

        /// <summary>
        /// eventual.
        /// </summary>
        public const string Eventual = "Eventual";

        /// <summary>
        /// session.
        /// </summary>
        public const string Session = "Session";

        /// <summary>
        /// strong.
        /// </summary>
        public const string Strong = "Strong";
    }

    /// <summary>
    /// Deprecated, use <c>db.collection.name</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by db.collection.name.", false)]
    public const string CosmosdbContainer = "db.cosmosdb.container";

    /// <summary>
    /// Deprecated, no replacement at this time.
    /// </summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string CosmosdbOperationType = "db.cosmosdb.operation_type";

    /// <summary>
    /// Values for the <c>CosmosdbOperationType</c> attribute.
    /// </summary>
    public static class CosmosdbOperationTypeValues
    {
        /// <summary>
        /// batch.
        /// </summary>
        public const string Batch = "batch";

        /// <summary>
        /// create.
        /// </summary>
        public const string Create = "create";

        /// <summary>
        /// delete.
        /// </summary>
        public const string Delete = "delete";

        /// <summary>
        /// execute.
        /// </summary>
        public const string Execute = "execute";

        /// <summary>
        /// execute_javascript.
        /// </summary>
        public const string ExecuteJavascript = "execute_javascript";

        /// <summary>
        /// head.
        /// </summary>
        public const string Head = "head";

        /// <summary>
        /// head_feed.
        /// </summary>
        public const string HeadFeed = "head_feed";

        /// <summary>
        /// invalid.
        /// </summary>
        public const string Invalid = "invalid";

        /// <summary>
        /// patch.
        /// </summary>
        public const string Patch = "patch";

        /// <summary>
        /// query.
        /// </summary>
        public const string Query = "query";

        /// <summary>
        /// query_plan.
        /// </summary>
        public const string QueryPlan = "query_plan";

        /// <summary>
        /// read.
        /// </summary>
        public const string Read = "read";

        /// <summary>
        /// read_feed.
        /// </summary>
        public const string ReadFeed = "read_feed";

        /// <summary>
        /// replace.
        /// </summary>
        public const string Replace = "replace";

        /// <summary>
        /// upsert.
        /// </summary>
        public const string Upsert = "upsert";
    }

    /// <summary>
    /// Deprecated, use <c>azure.cosmosdb.operation.contacted_regions</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by azure.cosmosdb.operation.contacted_regions.", false)]
    public const string CosmosdbRegionsContacted = "db.cosmosdb.regions_contacted";

    /// <summary>
    /// Deprecated, use <c>azure.cosmosdb.operation.request_charge</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by azure.cosmosdb.operation.request_charge.", false)]
    public const string CosmosdbRequestCharge = "db.cosmosdb.request_charge";

    /// <summary>
    /// Deprecated, use <c>azure.cosmosdb.request.body.size</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by azure.cosmosdb.request.body.size.", false)]
    public const string CosmosdbRequestContentLength = "db.cosmosdb.request_content_length";

    /// <summary>
    /// Deprecated, use <c>db.response.status_code</c> instead.
    /// </summary>
    [global::System.Obsolete("Use `db.response.status_code` instead.", false)]
    public const string CosmosdbStatusCode = "db.cosmosdb.status_code";

    /// <summary>
    /// Deprecated, use <c>azure.cosmosdb.response.sub_status_code</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by azure.cosmosdb.response.sub_status_code.", false)]
    public const string CosmosdbSubStatusCode = "db.cosmosdb.sub_status_code";

    /// <summary>
    /// Deprecated, use <c>db.namespace</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by db.namespace.", false)]
    public const string ElasticsearchClusterName = "db.elasticsearch.cluster.name";

    /// <summary>
    /// Deprecated, use <c>elasticsearch.node.name</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by elasticsearch.node.name.", false)]
    public const string ElasticsearchNodeName = "db.elasticsearch.node.name";

    /// <summary>
    /// Deprecated, use <c>db.operation.parameter</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by db.operation.parameter.", false)]
    public const string ElasticsearchPathParts = "db.elasticsearch.path_parts";

    /// <summary>
    /// Deprecated, no general replacement at this time. For Elasticsearch, use <c>db.elasticsearch.node.name</c> instead.
    /// </summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string InstanceId = "db.instance.id";

    /// <summary>
    /// Removed, no replacement at this time.
    /// </summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string JdbcDriverClassname = "db.jdbc.driver_classname";

    /// <summary>
    /// Deprecated, use <c>db.collection.name</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by db.collection.name.", false)]
    public const string MongodbCollection = "db.mongodb.collection";

    /// <summary>
    /// Deprecated, SQL Server instance is now populated as a part of <c>db.namespace</c> attribute.
    /// </summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string MssqlInstanceName = "db.mssql.instance_name";

    /// <summary>
    /// Deprecated, use <c>db.namespace</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by db.namespace.", false)]
    public const string Name = "db.name";

    /// <summary>
    /// Deprecated, use <c>db.operation.name</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by db.operation.name.", false)]
    public const string Operation = "db.operation";

    /// <summary>
    /// A database operation parameter, with <c><key></c> being the parameter name, and the attribute value being a string representation of the parameter value.
    /// </summary>
    /// <remarks>
    /// For example, a client-side maximum number of rows to read from the database
    /// MAY be recorded as the <c>db.operation.parameter.max_rows</c> attribute.
    /// <p>
    /// <c>db.query.text</c> parameters SHOULD be captured using <c>db.query.parameter.<key></c>
    /// instead of <c>db.operation.parameter.<key></c>.
    /// </remarks>
    public const string OperationParameter = "db.operation.parameter";

    /// <summary>
    /// A database query parameter, with <c><key></c> being the parameter name, and the attribute value being a string representation of the parameter value.
    /// </summary>
    /// <remarks>
    /// If a query parameter has no name and instead is referenced only by index,
    /// then <c><key></c> SHOULD be the 0-based index.
    /// <p>
    /// <c>db.query.parameter.<key></c> SHOULD match
    /// up with the parameterized placeholders present in <c>db.query.text</c>.
    /// <p>
    /// It is RECOMMENDED to capture the value as provided by the application
    /// without attempting to do any case normalization.
    /// <p>
    /// <c>db.query.parameter.<key></c> SHOULD NOT be captured on batch operations.
    /// <p>
    /// Examples:
    /// <ul>
    ///   <li>For a query <c>SELECT * FROM users where username =  %s</c> with the parameter <c>"jdoe"</c>,
    /// the attribute <c>db.query.parameter.0</c> SHOULD be set to <c>"jdoe"</c>.</li>
    ///   <li>For a query <c>"SELECT * FROM users WHERE username = %(userName)s;</c> with parameter
    /// <c>userName = "jdoe"</c>, the attribute <c>db.query.parameter.userName</c> SHOULD be set to <c>"jdoe"</c>.</li>
    /// </ul>
    /// </remarks>
    public const string QueryParameter = "db.query.parameter";

    /// <summary>
    /// Deprecated, use <c>db.namespace</c> instead.
    /// </summary>
    [global::System.Obsolete("Uncategorized.", false)]
    public const string RedisDatabaseIndex = "db.redis.database_index";

    /// <summary>
    /// Number of rows returned by the operation.
    /// </summary>
    public const string ResponseReturnedRows = "db.response.returned_rows";

    /// <summary>
    /// Deprecated, use <c>db.collection.name</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by `db.collection.name`, but only if not extracting the value from `db.query.text`.", false)]
    public const string SqlTable = "db.sql.table";

    /// <summary>
    /// The database statement being executed.
    /// </summary>
    [global::System.Obsolete("Replaced by db.query.text.", false)]
    public const string Statement = "db.statement";

    /// <summary>
    /// Deprecated, use <c>db.system.name</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by db.system.name.", false)]
    public const string System = "db.system";

    /// <summary>
    /// Values for the <c>System</c> attribute.
    /// </summary>
    public static class SystemValues
    {
        /// <summary>
        /// Adabas (Adaptable Database System).
        /// </summary>
        public const string Adabas = "adabas";

        /// <summary>
        /// Deprecated, use <c>intersystems_cache</c> instead.
        /// </summary>
        [global::System.Obsolete("{\"note\": \"Replaced by `intersystems_cache`.\", \"reason\": \"renamed\", \"renamed_to\": \"intersystems_cache\"}", false)]
        public const string Cache = "cache";

        /// <summary>
        /// Apache Cassandra.
        /// </summary>
        public const string Cassandra = "cassandra";

        /// <summary>
        /// ClickHouse.
        /// </summary>
        public const string Clickhouse = "clickhouse";

        /// <summary>
        /// Deprecated, use <c>other_sql</c> instead.
        /// </summary>
        [global::System.Obsolete("{\"note\": \"Replaced by `other_sql`.\", \"reason\": \"renamed\", \"renamed_to\": \"other_sql\"}", false)]
        public const string Cloudscape = "cloudscape";

        /// <summary>
        /// CockroachDB.
        /// </summary>
        public const string Cockroachdb = "cockroachdb";

        /// <summary>
        /// Deprecated, no replacement at this time.
        /// </summary>
        [global::System.Obsolete("{\"note\": \"Obsoleted.\", \"reason\": \"obsoleted\"}", false)]
        public const string Coldfusion = "coldfusion";

        /// <summary>
        /// Microsoft Azure Cosmos DB.
        /// </summary>
        public const string Cosmosdb = "cosmosdb";

        /// <summary>
        /// Couchbase.
        /// </summary>
        public const string Couchbase = "couchbase";

        /// <summary>
        /// CouchDB.
        /// </summary>
        public const string Couchdb = "couchdb";

        /// <summary>
        /// IBM Db2.
        /// </summary>
        public const string Db2 = "db2";

        /// <summary>
        /// Apache Derby.
        /// </summary>
        public const string Derby = "derby";

        /// <summary>
        /// Amazon DynamoDB.
        /// </summary>
        public const string Dynamodb = "dynamodb";

        /// <summary>
        /// EnterpriseDB.
        /// </summary>
        public const string Edb = "edb";

        /// <summary>
        /// Elasticsearch.
        /// </summary>
        public const string Elasticsearch = "elasticsearch";

        /// <summary>
        /// FileMaker.
        /// </summary>
        public const string Filemaker = "filemaker";

        /// <summary>
        /// Firebird.
        /// </summary>
        public const string Firebird = "firebird";

        /// <summary>
        /// Deprecated, use <c>other_sql</c> instead.
        /// </summary>
        [global::System.Obsolete("{\"note\": \"Replaced by `other_sql`.\", \"reason\": \"renamed\", \"renamed_to\": \"other_sql\"}", false)]
        public const string Firstsql = "firstsql";

        /// <summary>
        /// Apache Geode.
        /// </summary>
        public const string Geode = "geode";

        /// <summary>
        /// H2.
        /// </summary>
        public const string H2 = "h2";

        /// <summary>
        /// SAP HANA.
        /// </summary>
        public const string Hanadb = "hanadb";

        /// <summary>
        /// Apache HBase.
        /// </summary>
        public const string Hbase = "hbase";

        /// <summary>
        /// Apache Hive.
        /// </summary>
        public const string Hive = "hive";

        /// <summary>
        /// HyperSQL DataBase.
        /// </summary>
        public const string Hsqldb = "hsqldb";

        /// <summary>
        /// InfluxDB.
        /// </summary>
        public const string Influxdb = "influxdb";

        /// <summary>
        /// Informix.
        /// </summary>
        public const string Informix = "informix";

        /// <summary>
        /// Ingres.
        /// </summary>
        public const string Ingres = "ingres";

        /// <summary>
        /// InstantDB.
        /// </summary>
        public const string Instantdb = "instantdb";

        /// <summary>
        /// InterBase.
        /// </summary>
        public const string Interbase = "interbase";

        /// <summary>
        /// InterSystems Caché.
        /// </summary>
        public const string IntersystemsCache = "intersystems_cache";

        /// <summary>
        /// MariaDB.
        /// </summary>
        public const string Mariadb = "mariadb";

        /// <summary>
        /// SAP MaxDB.
        /// </summary>
        public const string Maxdb = "maxdb";

        /// <summary>
        /// Memcached.
        /// </summary>
        public const string Memcached = "memcached";

        /// <summary>
        /// MongoDB.
        /// </summary>
        public const string Mongodb = "mongodb";

        /// <summary>
        /// Microsoft SQL Server.
        /// </summary>
        public const string Mssql = "mssql";

        /// <summary>
        /// Deprecated, Microsoft SQL Server Compact is discontinued.
        /// </summary>
        [global::System.Obsolete("{\"note\": \"Replaced by `other_sql`.\", \"reason\": \"renamed\", \"renamed_to\": \"other_sql\"}", false)]
        public const string Mssqlcompact = "mssqlcompact";

        /// <summary>
        /// MySQL.
        /// </summary>
        public const string Mysql = "mysql";

        /// <summary>
        /// Neo4j.
        /// </summary>
        public const string Neo4j = "neo4j";

        /// <summary>
        /// Netezza.
        /// </summary>
        public const string Netezza = "netezza";

        /// <summary>
        /// OpenSearch.
        /// </summary>
        public const string Opensearch = "opensearch";

        /// <summary>
        /// Oracle Database.
        /// </summary>
        public const string Oracle = "oracle";

        /// <summary>
        /// Some other SQL database. Fallback only. See notes.
        /// </summary>
        public const string OtherSql = "other_sql";

        /// <summary>
        /// Pervasive PSQL.
        /// </summary>
        public const string Pervasive = "pervasive";

        /// <summary>
        /// PointBase.
        /// </summary>
        public const string Pointbase = "pointbase";

        /// <summary>
        /// PostgreSQL.
        /// </summary>
        public const string Postgresql = "postgresql";

        /// <summary>
        /// Progress Database.
        /// </summary>
        public const string Progress = "progress";

        /// <summary>
        /// Redis.
        /// </summary>
        public const string Redis = "redis";

        /// <summary>
        /// Amazon Redshift.
        /// </summary>
        public const string Redshift = "redshift";

        /// <summary>
        /// Cloud Spanner.
        /// </summary>
        public const string Spanner = "spanner";

        /// <summary>
        /// SQLite.
        /// </summary>
        public const string Sqlite = "sqlite";

        /// <summary>
        /// Sybase.
        /// </summary>
        public const string Sybase = "sybase";

        /// <summary>
        /// Teradata.
        /// </summary>
        public const string Teradata = "teradata";

        /// <summary>
        /// Trino.
        /// </summary>
        public const string Trino = "trino";

        /// <summary>
        /// Vertica.
        /// </summary>
        public const string Vertica = "vertica";
    }

    /// <summary>
    /// Deprecated, no replacement at this time.
    /// </summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string User = "db.user";
}
