// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@7fe537301d17919af7d7eb65b32e9be35da2c497
// Schema: https://opentelemetry.io/schemas/1.40.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Telemetry;

/// <summary>Telemetry Attributes (incubating).</summary>
public static class TelemetryAttributes
{
    /// <summary>The name of the auto instrumentation agent or distribution, if used..</summary>
    /// <remarks>Official auto instrumentation agents and distributions SHOULD set the `telemetry.distro.name` attribute to a string starting with `opentelemetry-`, e.g. `opentelemetry-java-instrumentation`.</remarks>
    public const string DistroName = "telemetry.distro.name";

    /// <summary>The version string of the auto instrumentation agent or distribution, if used..</summary>
    public const string DistroVersion = "telemetry.distro.version";

}