// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@7fe537301d17919af7d7eb65b32e9be35da2c497
// Schema: https://opentelemetry.io/schemas/1.40.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Otel;

/// <summary>Otel Attributes (incubating).</summary>
public static class OtelAttributes
{
    /// <summary>A name uniquely identifying the instance of the OpenTelemetry component within its containing SDK instance..</summary>
    /// <remarks>Implementations SHOULD ensure a low cardinality for this attribute, even across application or SDK restarts. E.g. implementations MUST NOT use UUIDs as values for this attribute.  Implementations MAY achieve these goals by following a `&lt;otel.component.type&gt;/&lt;instance-counter&gt;` pattern, e.g. `batching_span_processor/0`. Hereby `otel.component.type` refers to the corresponding attribute value of the component.  The value of `instance-counter` MAY be automatically assigned by the component and uniqueness within the enclosing SDK instance MUST be guaranteed. For example, `&lt;instance-counter&gt;` MAY be implemented by using a monotonically increasing counter (starting with `0`), which is incremented every time an instance of the given component type is started.  With this implementation, for example the first Batching Span Processor would have `batching_span_processor/0` as `otel.component.name`, the second one `batching_span_processor/1` and so on. These values will therefore be reused in the case of an application restart.</remarks>
    public const string ComponentName = "otel.component.name";

    /// <summary>A name identifying the type of the OpenTelemetry component..</summary>
    /// <remarks>If none of the standardized values apply, implementations SHOULD use the language-defined name of the type. E.g. for Java the fully qualified classname SHOULD be used in this case.</remarks>
    public const string ComponentType = "otel.component.type";

    /// <summary>Values for the <c>ComponentType</c> attribute.</summary>
    public static class ComponentTypeValues
    {
        /// <summary>The builtin SDK batching log record processor.</summary>
        public const string BatchingLogProcessor = "batching_log_processor";
        /// <summary>The builtin SDK batching span processor.</summary>
        public const string BatchingSpanProcessor = "batching_span_processor";
        /// <summary>OTLP log record exporter over gRPC with protobuf serialization.</summary>
        public const string OtlpGrpcLogExporter = "otlp_grpc_log_exporter";
        /// <summary>OTLP metric exporter over gRPC with protobuf serialization.</summary>
        public const string OtlpGrpcMetricExporter = "otlp_grpc_metric_exporter";
        /// <summary>OTLP span exporter over gRPC with protobuf serialization.</summary>
        public const string OtlpGrpcSpanExporter = "otlp_grpc_span_exporter";
        /// <summary>OTLP log record exporter over HTTP with JSON serialization.</summary>
        public const string OtlpHttpJsonLogExporter = "otlp_http_json_log_exporter";
        /// <summary>OTLP metric exporter over HTTP with JSON serialization.</summary>
        public const string OtlpHttpJsonMetricExporter = "otlp_http_json_metric_exporter";
        /// <summary>OTLP span exporter over HTTP with JSON serialization.</summary>
        public const string OtlpHttpJsonSpanExporter = "otlp_http_json_span_exporter";
        /// <summary>OTLP log record exporter over HTTP with protobuf serialization.</summary>
        public const string OtlpHttpLogExporter = "otlp_http_log_exporter";
        /// <summary>OTLP metric exporter over HTTP with protobuf serialization.</summary>
        public const string OtlpHttpMetricExporter = "otlp_http_metric_exporter";
        /// <summary>OTLP span exporter over HTTP with protobuf serialization.</summary>
        public const string OtlpHttpSpanExporter = "otlp_http_span_exporter";
        /// <summary>The builtin SDK periodically exporting metric reader.</summary>
        public const string PeriodicMetricReader = "periodic_metric_reader";
        /// <summary>Prometheus metric exporter over HTTP with the default text-based format.</summary>
        public const string PrometheusHttpTextMetricExporter = "prometheus_http_text_metric_exporter";
        /// <summary>The builtin SDK simple log record processor.</summary>
        public const string SimpleLogProcessor = "simple_log_processor";
        /// <summary>The builtin SDK simple span processor.</summary>
        public const string SimpleSpanProcessor = "simple_span_processor";
        /// <summary>Zipkin span exporter over HTTP.</summary>
        public const string ZipkinHttpSpanExporter = "zipkin_http_span_exporter";
    }

    /// <summary>Identifies the class / type of event..</summary>
    /// <remarks>This attribute SHOULD be used by non-OTLP exporters when destination does not support `EventName` or equivalent field. This attribute MAY be used by applications using existing logging libraries so that it can be used to set the `EventName` field by Collector or SDK components.</remarks>
    public const string EventName = "otel.event.name";

    /// <summary>Deprecated. Use the `otel.scope.name` attribute.</summary>
    [global::System.Obsolete("Replaced by otel.scope.name.", false)]
    public const string LibraryName = "otel.library.name";

    /// <summary>Deprecated. Use the `otel.scope.version` attribute..</summary>
    [global::System.Obsolete("Replaced by otel.scope.version.", false)]
    public const string LibraryVersion = "otel.library.version";

    /// <summary>The schema URL of the instrumentation scope..</summary>
    public const string ScopeSchemaUrl = "otel.scope.schema_url";

    /// <summary>Determines whether the span has a parent span, and if so, [whether it is a remote parent](https://opentelemetry.io/docs/specs/otel/trace/api/#isremote).</summary>
    public const string SpanParentOrigin = "otel.span.parent.origin";

    /// <summary>Values for the <c>SpanParentOrigin</c> attribute.</summary>
    public static class SpanParentOriginValues
    {
        /// <summary>The span has a parent and the parent's span context [isRemote()](https://opentelemetry.io/docs/specs/otel/trace/api/#isremote) is false.</summary>
        public const string Local = "local";
        /// <summary>The span does not have a parent, it is a root span.</summary>
        public const string None = "none";
        /// <summary>The span has a parent and the parent's span context [isRemote()](https://opentelemetry.io/docs/specs/otel/trace/api/#isremote) is true.</summary>
        public const string Remote = "remote";
    }

    /// <summary>The result value of the sampler for this span.</summary>
    public const string SpanSamplingResult = "otel.span.sampling_result";

    /// <summary>Values for the <c>SpanSamplingResult</c> attribute.</summary>
    public static class SpanSamplingResultValues
    {
        /// <summary>The span is not sampled and not recording.</summary>
        public const string Drop = "DROP";
        /// <summary>The span is sampled and recording.</summary>
        public const string RecordAndSample = "RECORD_AND_SAMPLE";
        /// <summary>The span is not sampled, but recording.</summary>
        public const string RecordOnly = "RECORD_ONLY";
    }

}