// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// <auto-generated />

#nullable enable

#if !NET7_0_OR_GREATER

namespace System.Diagnostics.CodeAnalysis;

using ComponentModel;

/// <summary>
///     Specifies that the constructor sets all required members for the current type,
///     and callers do not need to set any required members themselves.
/// </summary>
[AttributeUsage(AttributeTargets.Constructor)]
[EditorBrowsable(EditorBrowsableState.Never)]
[ExcludeFromCodeCoverage]
internal sealed class SetsRequiredMembersAttribute : Attribute
{
    /// <summary>
    ///     Initializes a new instance of the <c>SetsRequiredMembersAttribute</c> class.
    /// </summary>
    public SetsRequiredMembersAttribute()
    {
    }
}

#endif
