-- <auto-generated/>
-- Generated from @opentelemetry/semantic-conventions v1.39.0
-- Do not edit manually - run 'npm run generate' in SemconvGenerator
--
-- Promoted columns for fast queries (extracted from attributes_json)
-- Include in CREATE TABLE statements as needed

-- aspnetcore.diagnostics attributes
aspnetcore_diagnostics_exception_result VARCHAR,
aspnetcore_diagnostics_handler_type VARCHAR,

-- aspnetcore.rate_limiting attributes
aspnetcore_rate_limiting_policy VARCHAR,
aspnetcore_rate_limiting_result VARCHAR,

-- aspnetcore.request attributes
aspnetcore_request_is_unhandled VARCHAR,

-- aspnetcore.routing attributes
aspnetcore_routing_is_fallback VARCHAR,
aspnetcore_routing_match_status VARCHAR,

-- aspnetcore.user attributes
aspnetcore_user_is_authenticated VARCHAR,

-- client.address attributes
client_address VARCHAR,

-- client.port attributes
client_port VARCHAR,

-- code.column attributes
code_column_number VARCHAR,
code_column VARCHAR,

-- code.file attributes
code_file_path VARCHAR,

-- code.function attributes
code_function_name VARCHAR,
code_function VARCHAR,

-- code.line attributes
code_line_number VARCHAR,

-- code.stacktrace attributes
code_stacktrace VARCHAR,

-- db.collection attributes
db_collection_name VARCHAR,

-- db.namespace attributes
db_namespace VARCHAR,

-- db.operation attributes
db_operation_batch_size VARCHAR,
db_operation_name VARCHAR,
db_operation VARCHAR,

-- db.query attributes
db_query_summary VARCHAR,
db_query_text VARCHAR,

-- db.response attributes
db_response_status_code VARCHAR,
db_response_returned_rows VARCHAR,

-- db.stored_procedure attributes
db_stored_procedure_name VARCHAR,

-- db.system attributes
db_system_name VARCHAR,
db_system VARCHAR,

-- dotnet.gc attributes
dotnet_gc_heap_generation VARCHAR,

-- error.type attributes
error_type VARCHAR,

-- exception.escaped attributes
exception_escaped VARCHAR,

-- exception.message attributes
exception_message VARCHAR,

-- exception.stacktrace attributes
exception_stacktrace VARCHAR,

-- exception.type attributes
exception_type VARCHAR,

-- http.request attributes
http_request_method VARCHAR,
http_request_method_original VARCHAR,
http_request_resend_count BIGINT,
http_request_body_size VARCHAR,
http_request_size VARCHAR,

-- http.response attributes
http_response_status_code VARCHAR,
http_response_body_size VARCHAR,
http_response_size VARCHAR,

-- http.route attributes
http_route VARCHAR,

-- network.local attributes
network_local_address VARCHAR,
network_local_port VARCHAR,

-- network.peer attributes
network_peer_address VARCHAR,
network_peer_port VARCHAR,

-- network.protocol attributes
network_protocol_name VARCHAR,
network_protocol_version VARCHAR,

-- network.transport attributes
network_transport VARCHAR,

-- network.type attributes
network_type VARCHAR,

-- otel.scope attributes
otel_scope_name VARCHAR,
otel_scope_version VARCHAR,
otel_scope_schema_url VARCHAR,

-- otel.status_code attributes
otel_status_code VARCHAR,

-- otel.status_description attributes
otel_status_description VARCHAR,

-- signalr.connection attributes
signalr_connection_status VARCHAR,

-- signalr.transport attributes
signalr_transport VARCHAR,

-- url.fragment attributes
url_fragment VARCHAR,

-- url.full attributes
url_full VARCHAR,

-- url.path attributes
url_path VARCHAR,

-- url.query attributes
url_query VARCHAR,

-- url.scheme attributes
url_scheme VARCHAR,

-- user_agent.original attributes
user_agent_original VARCHAR,

-- artifact.attestation attributes
artifact_attestation_filename VARCHAR,
artifact_attestation_hash VARCHAR,
artifact_attestation_id VARCHAR,

-- artifact.filename attributes
artifact_filename VARCHAR,

-- artifact.hash attributes
artifact_hash VARCHAR,

-- artifact.purl attributes
artifact_purl VARCHAR,

-- artifact.version attributes
artifact_version VARCHAR,

-- aspnetcore.authentication attributes
aspnetcore_authentication_result VARCHAR,
aspnetcore_authentication_scheme VARCHAR,

-- aspnetcore.authorization attributes
aspnetcore_authorization_policy VARCHAR,
aspnetcore_authorization_result VARCHAR,

-- aspnetcore.identity attributes
aspnetcore_identity_error_code VARCHAR,
aspnetcore_identity_password_check_result VARCHAR,
aspnetcore_identity_result VARCHAR,
aspnetcore_identity_sign_in_result VARCHAR,
aspnetcore_identity_sign_in_type VARCHAR,
aspnetcore_identity_token_purpose VARCHAR,
aspnetcore_identity_token_verified VARCHAR,
aspnetcore_identity_user_update_type VARCHAR,
aspnetcore_identity_user_type VARCHAR,

-- aspnetcore.memory_pool attributes
aspnetcore_memory_pool_owner VARCHAR,

-- aspnetcore.sign_in attributes
aspnetcore_sign_in_is_persistent VARCHAR,

-- browser.brands attributes
browser_brands VARCHAR,

-- browser.language attributes
browser_language VARCHAR,

-- browser.mobile attributes
browser_mobile VARCHAR,

-- browser.platform attributes
browser_platform VARCHAR,

-- cicd.pipeline attributes
cicd_pipeline_action_name VARCHAR,
cicd_pipeline_name VARCHAR,
cicd_pipeline_result VARCHAR,
cicd_pipeline_run_id VARCHAR,
cicd_pipeline_run_state VARCHAR,
cicd_pipeline_run_url_full VARCHAR,
cicd_pipeline_task_name VARCHAR,
cicd_pipeline_task_run_id VARCHAR,
cicd_pipeline_task_run_result VARCHAR,
cicd_pipeline_task_run_url_full VARCHAR,
cicd_pipeline_task_type VARCHAR,

-- cicd.system attributes
cicd_system_component VARCHAR,

-- cicd.worker attributes
cicd_worker_id VARCHAR,
cicd_worker_name VARCHAR,
cicd_worker_state VARCHAR,
cicd_worker_url_full VARCHAR,

-- cloud.account attributes
cloud_account_id VARCHAR,

-- cloud.availability_zone attributes
cloud_availability_zone VARCHAR,

-- cloud.platform attributes
cloud_platform VARCHAR,

-- cloud.provider attributes
cloud_provider VARCHAR,

-- cloud.region attributes
cloud_region VARCHAR,

-- cloud.resource_id attributes
cloud_resource_id VARCHAR,

-- cloudevents.event_id attributes
cloudevents_event_id VARCHAR,

-- cloudevents.event_source attributes
cloudevents_event_source VARCHAR,

-- cloudevents.event_spec_version attributes
cloudevents_event_spec_version VARCHAR,

-- cloudevents.event_subject attributes
cloudevents_event_subject VARCHAR,

-- cloudevents.event_type attributes
cloudevents_event_type VARCHAR,

-- cloudfoundry.app attributes
cloudfoundry_app_id VARCHAR,
cloudfoundry_app_instance_id VARCHAR,
cloudfoundry_app_name VARCHAR,

-- cloudfoundry.org attributes
cloudfoundry_org_id VARCHAR,
cloudfoundry_org_name VARCHAR,

-- cloudfoundry.process attributes
cloudfoundry_process_id VARCHAR,
cloudfoundry_process_type VARCHAR,

-- cloudfoundry.space attributes
cloudfoundry_space_id VARCHAR,
cloudfoundry_space_name VARCHAR,

-- cloudfoundry.system attributes
cloudfoundry_system_id VARCHAR,
cloudfoundry_system_instance_id VARCHAR,

-- code.filepath attributes
code_filepath VARCHAR,

-- code.lineno attributes
code_lineno VARCHAR,

-- code.namespace attributes
code_namespace VARCHAR,

-- container.command attributes
container_command VARCHAR,

-- container.command_args attributes
container_command_args VARCHAR,

-- container.command_line attributes
container_command_line VARCHAR,

-- container.cpu attributes
container_cpu_state VARCHAR,

-- container.csi attributes
container_csi_plugin_name VARCHAR,
container_csi_volume_id VARCHAR,

-- container.id attributes
container_id VARCHAR,

-- container.image attributes
container_image_id VARCHAR,
container_image_name VARCHAR,
container_image_repo_digests VARCHAR,
container_image_tags VARCHAR,

-- container.name attributes
container_name VARCHAR,

-- container.runtime attributes
container_runtime VARCHAR,
container_runtime_description VARCHAR,
container_runtime_name VARCHAR,
container_runtime_version VARCHAR,

-- db.cassandra attributes
db_cassandra_consistency_level VARCHAR,
db_cassandra_coordinator_dc VARCHAR,
db_cassandra_coordinator_id VARCHAR,
db_cassandra_idempotence VARCHAR,
db_cassandra_page_size BIGINT,
db_cassandra_speculative_execution_count BIGINT,
db_cassandra_table VARCHAR,

-- db.client attributes
db_client_connection_pool_name VARCHAR,
db_client_connection_state VARCHAR,
db_client_connections_pool_name VARCHAR,
db_client_connections_state VARCHAR,

-- db.connection_string attributes
db_connection_string VARCHAR,

-- db.cosmosdb attributes
db_cosmosdb_client_id VARCHAR,
db_cosmosdb_connection_mode VARCHAR,
db_cosmosdb_consistency_level VARCHAR,
db_cosmosdb_container VARCHAR,
db_cosmosdb_operation_type VARCHAR,
db_cosmosdb_regions_contacted VARCHAR,
db_cosmosdb_request_charge VARCHAR,
db_cosmosdb_request_content_length VARCHAR,
db_cosmosdb_status_code VARCHAR,
db_cosmosdb_sub_status_code VARCHAR,

-- db.elasticsearch attributes
db_elasticsearch_cluster_name VARCHAR,
db_elasticsearch_node_name VARCHAR,

-- db.instance attributes
db_instance_id VARCHAR,

-- db.jdbc attributes
db_jdbc_driver_classname VARCHAR,

-- db.mongodb attributes
db_mongodb_collection VARCHAR,

-- db.mssql attributes
db_mssql_instance_name VARCHAR,

-- db.name attributes
db_name VARCHAR,

-- db.redis attributes
db_redis_database_index VARCHAR,

-- db.sql attributes
db_sql_table VARCHAR,

-- db.statement attributes
db_statement VARCHAR,

-- db.user attributes
db_user VARCHAR,

-- deployment.environment attributes
deployment_environment VARCHAR,
deployment_environment_name VARCHAR,

-- deployment.id attributes
deployment_id VARCHAR,

-- deployment.name attributes
deployment_name VARCHAR,

-- deployment.status attributes
deployment_status VARCHAR,

-- dns.answers attributes
dns_answers VARCHAR,

-- dns.question attributes
dns_question_name VARCHAR,

-- elasticsearch.node attributes
elasticsearch_node_name VARCHAR,

-- enduser.id attributes
enduser_id VARCHAR,

-- enduser.pseudo attributes
enduser_pseudo_id VARCHAR,

-- enduser.role attributes
enduser_role VARCHAR,

-- enduser.scope attributes
enduser_scope VARCHAR,

-- error.message attributes
error_message VARCHAR,

-- faas.coldstart attributes
faas_coldstart VARCHAR,

-- faas.cron attributes
faas_cron VARCHAR,

-- faas.document attributes
faas_document_collection VARCHAR,
faas_document_name VARCHAR,
faas_document_operation VARCHAR,
faas_document_time VARCHAR,

-- faas.instance attributes
faas_instance VARCHAR,

-- faas.invocation_id attributes
faas_invocation_id VARCHAR,

-- faas.invoked_name attributes
faas_invoked_name VARCHAR,

-- faas.invoked_provider attributes
faas_invoked_provider VARCHAR,

-- faas.invoked_region attributes
faas_invoked_region VARCHAR,

-- faas.max_memory attributes
faas_max_memory VARCHAR,

-- faas.name attributes
faas_name VARCHAR,

-- faas.time attributes
faas_time VARCHAR,

-- faas.trigger attributes
faas_trigger VARCHAR,

-- faas.version attributes
faas_version VARCHAR,

-- feature_flag.context attributes
feature_flag_context_id VARCHAR,

-- feature_flag.evaluation attributes
feature_flag_evaluation_error_message VARCHAR,
feature_flag_evaluation_reason VARCHAR,

-- feature_flag.key attributes
feature_flag_key VARCHAR,

-- feature_flag.provider attributes
feature_flag_provider_name VARCHAR,

-- feature_flag.result attributes
feature_flag_result_reason VARCHAR,
feature_flag_result_value VARCHAR,
feature_flag_result_variant VARCHAR,

-- feature_flag.set attributes
feature_flag_set_id VARCHAR,

-- feature_flag.variant attributes
feature_flag_variant VARCHAR,

-- feature_flag.version attributes
feature_flag_version VARCHAR,

-- file.accessed attributes
file_accessed VARCHAR,

-- file.attributes attributes
file_attributes VARCHAR,

-- file.changed attributes
file_changed VARCHAR,

-- file.created attributes
file_created VARCHAR,

-- file.directory attributes
file_directory VARCHAR,

-- file.extension attributes
file_extension VARCHAR,

-- file.fork_name attributes
file_fork_name VARCHAR,

-- file.group attributes
file_group_id VARCHAR,
file_group_name VARCHAR,

-- file.inode attributes
file_inode VARCHAR,

-- file.mode attributes
file_mode VARCHAR,

-- file.modified attributes
file_modified VARCHAR,

-- file.name attributes
file_name VARCHAR,

-- file.owner attributes
file_owner_id VARCHAR,
file_owner_name VARCHAR,

-- file.path attributes
file_path VARCHAR,

-- file.size attributes
file_size VARCHAR,

-- file.symbolic_link attributes
file_symbolic_link_target_path VARCHAR,

-- gen_ai.agent attributes
gen_ai_agent_description VARCHAR,
gen_ai_agent_id VARCHAR,
gen_ai_agent_name VARCHAR,

-- gen_ai.completion attributes
gen_ai_completion VARCHAR,

-- gen_ai.conversation attributes
gen_ai_conversation_id VARCHAR,

-- gen_ai.data_source attributes
gen_ai_data_source_id VARCHAR,

-- gen_ai.embeddings attributes
gen_ai_embeddings_dimension_count VARCHAR,

-- gen_ai.evaluation attributes
gen_ai_evaluation_explanation VARCHAR,
gen_ai_evaluation_name VARCHAR,
gen_ai_evaluation_score_label VARCHAR,
gen_ai_evaluation_score_value VARCHAR,

-- gen_ai.input attributes
gen_ai_input_messages VARCHAR,

-- gen_ai.openai attributes
gen_ai_openai_request_response_format VARCHAR,
gen_ai_openai_request_seed VARCHAR,
gen_ai_openai_request_service_tier VARCHAR,
gen_ai_openai_response_service_tier VARCHAR,
gen_ai_openai_response_system_fingerprint VARCHAR,

-- gen_ai.operation attributes
gen_ai_operation_name VARCHAR,

-- gen_ai.output attributes
gen_ai_output_messages VARCHAR,
gen_ai_output_type VARCHAR,

-- gen_ai.prompt attributes
gen_ai_prompt VARCHAR,
gen_ai_prompt_name VARCHAR,

-- gen_ai.provider attributes
gen_ai_provider_name VARCHAR,

-- gen_ai.request attributes
gen_ai_request_choice_count VARCHAR,
gen_ai_request_encoding_formats VARCHAR,
gen_ai_request_frequency_penalty VARCHAR,
gen_ai_request_max_tokens BIGINT,
gen_ai_request_model VARCHAR,
gen_ai_request_presence_penalty VARCHAR,
gen_ai_request_seed VARCHAR,
gen_ai_request_stop_sequences VARCHAR,
gen_ai_request_temperature VARCHAR,
gen_ai_request_top_k VARCHAR,
gen_ai_request_top_p VARCHAR,

-- gen_ai.response attributes
gen_ai_response_finish_reasons VARCHAR,
gen_ai_response_id VARCHAR,
gen_ai_response_model VARCHAR,

-- gen_ai.system attributes
gen_ai_system VARCHAR,

-- gen_ai.system_instructions attributes
gen_ai_system_instructions VARCHAR,

-- gen_ai.token attributes
gen_ai_token_type VARCHAR,

-- gen_ai.tool attributes
gen_ai_tool_call_arguments VARCHAR,
gen_ai_tool_call_id VARCHAR,
gen_ai_tool_call_result VARCHAR,
gen_ai_tool_definitions VARCHAR,
gen_ai_tool_description VARCHAR,
gen_ai_tool_name VARCHAR,
gen_ai_tool_type VARCHAR,

-- gen_ai.usage attributes
gen_ai_usage_completion_tokens BIGINT,
gen_ai_usage_input_tokens BIGINT,
gen_ai_usage_output_tokens BIGINT,
gen_ai_usage_prompt_tokens BIGINT,

-- geo.continent attributes
geo_continent_code VARCHAR,

-- geo.country attributes
geo_country_iso_code VARCHAR,

-- geo.locality attributes
geo_locality_name VARCHAR,

-- geo.location attributes
geo_location_lat VARCHAR,
geo_location_lon VARCHAR,

-- geo.postal_code attributes
geo_postal_code VARCHAR,

-- geo.region attributes
geo_region_iso_code VARCHAR,

-- host.arch attributes
host_arch VARCHAR,

-- host.cpu attributes
host_cpu_cache_l2_size VARCHAR,
host_cpu_family VARCHAR,
host_cpu_model_id VARCHAR,
host_cpu_model_name VARCHAR,
host_cpu_stepping VARCHAR,
host_cpu_vendor_id VARCHAR,

-- host.id attributes
host_id VARCHAR,

-- host.image attributes
host_image_id VARCHAR,
host_image_name VARCHAR,
host_image_version VARCHAR,

-- host.ip attributes
host_ip VARCHAR,

-- host.mac attributes
host_mac VARCHAR,

-- host.name attributes
host_name VARCHAR,

-- host.type attributes
host_type VARCHAR,

-- http.client_ip attributes
http_client_ip VARCHAR,

-- http.connection attributes
http_connection_state VARCHAR,

-- http.flavor attributes
http_flavor VARCHAR,

-- http.host attributes
http_host VARCHAR,

-- http.method attributes
http_method VARCHAR,

-- http.request_content_length attributes
http_request_content_length VARCHAR,

-- http.request_content_length_uncompressed attributes
http_request_content_length_uncompressed VARCHAR,

-- http.response_content_length attributes
http_response_content_length VARCHAR,

-- http.response_content_length_uncompressed attributes
http_response_content_length_uncompressed VARCHAR,

-- http.scheme attributes
http_scheme VARCHAR,

-- http.server_name attributes
http_server_name VARCHAR,

-- http.status_code attributes
http_status_code VARCHAR,

-- http.target attributes
http_target VARCHAR,

-- http.url attributes
http_url VARCHAR,

-- http.user_agent attributes
http_user_agent VARCHAR,

-- k8s.cluster attributes
k8s_cluster_name VARCHAR,
k8s_cluster_uid VARCHAR,

-- k8s.container attributes
k8s_container_name VARCHAR,
k8s_container_restart_count BIGINT,
k8s_container_status_last_terminated_reason VARCHAR,
k8s_container_status_reason VARCHAR,
k8s_container_status_state VARCHAR,

-- k8s.cronjob attributes
k8s_cronjob_name VARCHAR,
k8s_cronjob_uid VARCHAR,

-- k8s.daemonset attributes
k8s_daemonset_name VARCHAR,
k8s_daemonset_uid VARCHAR,

-- k8s.deployment attributes
k8s_deployment_name VARCHAR,
k8s_deployment_uid VARCHAR,

-- k8s.hpa attributes
k8s_hpa_metric_type VARCHAR,
k8s_hpa_name VARCHAR,
k8s_hpa_scaletargetref_api_version VARCHAR,
k8s_hpa_scaletargetref_kind VARCHAR,
k8s_hpa_scaletargetref_name VARCHAR,
k8s_hpa_uid VARCHAR,

-- k8s.hugepage attributes
k8s_hugepage_size VARCHAR,

-- k8s.job attributes
k8s_job_name VARCHAR,
k8s_job_uid VARCHAR,

-- k8s.namespace attributes
k8s_namespace_name VARCHAR,
k8s_namespace_phase VARCHAR,

-- k8s.node attributes
k8s_node_condition_status VARCHAR,
k8s_node_condition_type VARCHAR,
k8s_node_name VARCHAR,
k8s_node_uid VARCHAR,

-- k8s.pod attributes
k8s_pod_hostname VARCHAR,
k8s_pod_ip VARCHAR,
k8s_pod_name VARCHAR,
k8s_pod_start_time VARCHAR,
k8s_pod_status_phase VARCHAR,
k8s_pod_status_reason VARCHAR,
k8s_pod_uid VARCHAR,

-- k8s.replicaset attributes
k8s_replicaset_name VARCHAR,
k8s_replicaset_uid VARCHAR,

-- k8s.replicationcontroller attributes
k8s_replicationcontroller_name VARCHAR,
k8s_replicationcontroller_uid VARCHAR,

-- k8s.resourcequota attributes
k8s_resourcequota_name VARCHAR,
k8s_resourcequota_resource_name VARCHAR,
k8s_resourcequota_uid VARCHAR,

-- k8s.statefulset attributes
k8s_statefulset_name VARCHAR,
k8s_statefulset_uid VARCHAR,

-- k8s.storageclass attributes
k8s_storageclass_name VARCHAR,

-- k8s.volume attributes
k8s_volume_name VARCHAR,
k8s_volume_type VARCHAR,

-- log.file attributes
log_file_name VARCHAR,
log_file_name_resolved VARCHAR,
log_file_path VARCHAR,
log_file_path_resolved VARCHAR,

-- log.iostream attributes
log_iostream VARCHAR,

-- log.record attributes
log_record_original VARCHAR,
log_record_uid VARCHAR,

-- messaging.batch attributes
messaging_batch_message_count BIGINT,

-- messaging.client attributes
messaging_client_id VARCHAR,

-- messaging.consumer attributes
messaging_consumer_group_name VARCHAR,

-- messaging.destination attributes
messaging_destination_anonymous VARCHAR,
messaging_destination_name VARCHAR,
messaging_destination_partition_id VARCHAR,
messaging_destination_subscription_name VARCHAR,
messaging_destination_template VARCHAR,
messaging_destination_temporary VARCHAR,

-- messaging.destination_publish attributes
messaging_destination_publish_anonymous VARCHAR,
messaging_destination_publish_name VARCHAR,

-- messaging.eventhubs attributes
messaging_eventhubs_consumer_group VARCHAR,
messaging_eventhubs_message_enqueued_time VARCHAR,

-- messaging.gcp_pubsub attributes
messaging_gcp_pubsub_message_ack_deadline VARCHAR,
messaging_gcp_pubsub_message_ack_id VARCHAR,
messaging_gcp_pubsub_message_delivery_attempt VARCHAR,
messaging_gcp_pubsub_message_ordering_key VARCHAR,

-- messaging.kafka attributes
messaging_kafka_consumer_group VARCHAR,
messaging_kafka_destination_partition VARCHAR,
messaging_kafka_message_key VARCHAR,
messaging_kafka_message_offset VARCHAR,
messaging_kafka_message_tombstone VARCHAR,
messaging_kafka_offset VARCHAR,

-- messaging.message attributes
messaging_message_body_size VARCHAR,
messaging_message_conversation_id VARCHAR,
messaging_message_envelope_size VARCHAR,
messaging_message_id VARCHAR,

-- messaging.operation attributes
messaging_operation VARCHAR,
messaging_operation_name VARCHAR,
messaging_operation_type VARCHAR,

-- messaging.rabbitmq attributes
messaging_rabbitmq_destination_routing_key VARCHAR,
messaging_rabbitmq_message_delivery_tag VARCHAR,

-- messaging.rocketmq attributes
messaging_rocketmq_client_group VARCHAR,
messaging_rocketmq_consumption_model VARCHAR,
messaging_rocketmq_message_delay_time_level VARCHAR,
messaging_rocketmq_message_delivery_timestamp VARCHAR,
messaging_rocketmq_message_group VARCHAR,
messaging_rocketmq_message_keys VARCHAR,
messaging_rocketmq_message_tag VARCHAR,
messaging_rocketmq_message_type VARCHAR,
messaging_rocketmq_namespace VARCHAR,

-- messaging.servicebus attributes
messaging_servicebus_destination_subscription_name VARCHAR,
messaging_servicebus_disposition_status VARCHAR,
messaging_servicebus_message_delivery_count BIGINT,
messaging_servicebus_message_enqueued_time VARCHAR,

-- messaging.system attributes
messaging_system VARCHAR,

-- network.carrier attributes
network_carrier_icc VARCHAR,
network_carrier_mcc VARCHAR,
network_carrier_mnc VARCHAR,
network_carrier_name VARCHAR,

-- network.connection attributes
network_connection_state VARCHAR,
network_connection_subtype VARCHAR,
network_connection_type VARCHAR,

-- network.interface attributes
network_interface_name VARCHAR,

-- network.io attributes
network_io_direction VARCHAR,

-- os.build_id attributes
os_build_id VARCHAR,

-- os.description attributes
os_description VARCHAR,

-- os.name attributes
os_name VARCHAR,

-- os.type attributes
os_type VARCHAR,

-- os.version attributes
os_version VARCHAR,

-- otel.component attributes
otel_component_name VARCHAR,
otel_component_type VARCHAR,

-- otel.event attributes
otel_event_name VARCHAR,

-- otel.library attributes
otel_library_name VARCHAR,
otel_library_version VARCHAR,

-- otel.span attributes
otel_span_parent_origin VARCHAR,
otel_span_sampling_result VARCHAR,

-- process.args_count attributes
process_args_count BIGINT,

-- process.command attributes
process_command VARCHAR,

-- process.command_args attributes
process_command_args VARCHAR,

-- process.command_line attributes
process_command_line VARCHAR,

-- process.context_switch attributes
process_context_switch_type VARCHAR,

-- process.cpu attributes
process_cpu_state VARCHAR,

-- process.creation attributes
process_creation_time VARCHAR,

-- process.executable attributes
process_executable_build_id_gnu VARCHAR,
process_executable_build_id_go VARCHAR,
process_executable_build_id_htlhash VARCHAR,
process_executable_build_id_profiling VARCHAR,
process_executable_name VARCHAR,
process_executable_path VARCHAR,

-- process.exit attributes
process_exit_code VARCHAR,
process_exit_time VARCHAR,

-- process.group_leader attributes
process_group_leader_pid VARCHAR,

-- process.interactive attributes
process_interactive VARCHAR,

-- process.linux attributes
process_linux_cgroup VARCHAR,

-- process.owner attributes
process_owner VARCHAR,

-- process.paging attributes
process_paging_fault_type VARCHAR,

-- process.parent_pid attributes
process_parent_pid VARCHAR,

-- process.pid attributes
process_pid VARCHAR,

-- process.real_user attributes
process_real_user_id VARCHAR,
process_real_user_name VARCHAR,

-- process.runtime attributes
process_runtime_description VARCHAR,
process_runtime_name VARCHAR,
process_runtime_version VARCHAR,

-- process.saved_user attributes
process_saved_user_id VARCHAR,
process_saved_user_name VARCHAR,

-- process.session_leader attributes
process_session_leader_pid VARCHAR,

-- process.state attributes
process_state VARCHAR,

-- process.title attributes
process_title VARCHAR,

-- process.user attributes
process_user_id VARCHAR,
process_user_name VARCHAR,

-- process.vpid attributes
process_vpid VARCHAR,

-- process.working_directory attributes
process_working_directory VARCHAR,

-- rpc.connect_rpc attributes
rpc_connect_rpc_error_code VARCHAR,

-- rpc.grpc attributes
rpc_grpc_status_code VARCHAR,

-- rpc.jsonrpc attributes
rpc_jsonrpc_error_code VARCHAR,
rpc_jsonrpc_error_message VARCHAR,
rpc_jsonrpc_request_id VARCHAR,
rpc_jsonrpc_version VARCHAR,

-- rpc.message attributes
rpc_message_compressed_size BIGINT,
rpc_message_id VARCHAR,
rpc_message_type VARCHAR,
rpc_message_uncompressed_size BIGINT,

-- rpc.method attributes
rpc_method VARCHAR,

-- rpc.method_original attributes
rpc_method_original VARCHAR,

-- rpc.response attributes
rpc_response_status_code VARCHAR,

-- rpc.service attributes
rpc_service VARCHAR,

-- rpc.system attributes
rpc_system VARCHAR,
rpc_system_name VARCHAR,

-- session.id attributes
session_id VARCHAR,

-- session.previous_id attributes
session_previous_id VARCHAR,

-- system.cpu attributes
system_cpu_logical_number VARCHAR,
system_cpu_state VARCHAR,

-- system.device attributes
system_device VARCHAR,

-- system.filesystem attributes
system_filesystem_mode VARCHAR,
system_filesystem_mountpoint VARCHAR,
system_filesystem_state VARCHAR,
system_filesystem_type VARCHAR,

-- system.memory attributes
system_memory_linux_slab_state VARCHAR,
system_memory_state VARCHAR,

-- system.network attributes
system_network_state VARCHAR,

-- system.paging attributes
system_paging_direction VARCHAR,
system_paging_fault_type VARCHAR,
system_paging_state VARCHAR,
system_paging_type VARCHAR,

-- system.process attributes
system_process_status VARCHAR,

-- system.processes attributes
system_processes_status VARCHAR,

-- test.case attributes
test_case_name VARCHAR,
test_case_result_status VARCHAR,

-- test.suite attributes
test_suite_name VARCHAR,
test_suite_run_status VARCHAR,

-- thread.id attributes
thread_id VARCHAR,

-- thread.name attributes
thread_name VARCHAR,

-- tls.cipher attributes
tls_cipher VARCHAR,

-- tls.client attributes
tls_client_certificate VARCHAR,
tls_client_certificate_chain VARCHAR,
tls_client_hash_md5 VARCHAR,
tls_client_hash_sha1 VARCHAR,
tls_client_hash_sha256 VARCHAR,
tls_client_issuer VARCHAR,
tls_client_ja3 VARCHAR,
tls_client_not_after VARCHAR,
tls_client_not_before VARCHAR,
tls_client_server_name VARCHAR,
tls_client_subject VARCHAR,
tls_client_supported_ciphers VARCHAR,

-- tls.curve attributes
tls_curve VARCHAR,

-- tls.established attributes
tls_established VARCHAR,

-- tls.next_protocol attributes
tls_next_protocol VARCHAR,

-- tls.protocol attributes
tls_protocol_name VARCHAR,
tls_protocol_version VARCHAR,

-- tls.resumed attributes
tls_resumed VARCHAR,

-- tls.server attributes
tls_server_certificate VARCHAR,
tls_server_certificate_chain VARCHAR,
tls_server_hash_md5 VARCHAR,
tls_server_hash_sha1 VARCHAR,
tls_server_hash_sha256 VARCHAR,
tls_server_issuer VARCHAR,
tls_server_ja3s VARCHAR,
tls_server_not_after VARCHAR,
tls_server_not_before VARCHAR,
tls_server_subject VARCHAR,

-- url.domain attributes
url_domain VARCHAR,

-- url.extension attributes
url_extension VARCHAR,

-- url.original attributes
url_original VARCHAR,

-- url.port attributes
url_port VARCHAR,

-- url.registered_domain attributes
url_registered_domain VARCHAR,

-- url.subdomain attributes
url_subdomain VARCHAR,

-- url.template attributes
url_template VARCHAR,

-- url.top_level_domain attributes
url_top_level_domain VARCHAR,

-- user.email attributes
user_email VARCHAR,

-- user.full_name attributes
user_full_name VARCHAR,

-- user.hash attributes
user_hash VARCHAR,

-- user.id attributes
user_id VARCHAR,

-- user.name attributes
user_name VARCHAR,

-- user.roles attributes
user_roles VARCHAR,

-- user_agent.name attributes
user_agent_name VARCHAR,

-- user_agent.os attributes
user_agent_os_name VARCHAR,
user_agent_os_version VARCHAR,

-- user_agent.synthetic attributes
user_agent_synthetic_type VARCHAR,

-- user_agent.version attributes
user_agent_version VARCHAR,

-- vcs.change attributes
vcs_change_id VARCHAR,
vcs_change_state VARCHAR,
vcs_change_title VARCHAR,

-- vcs.line_change attributes
vcs_line_change_type VARCHAR,

-- vcs.owner attributes
vcs_owner_name VARCHAR,

-- vcs.provider attributes
vcs_provider_name VARCHAR,

-- vcs.ref attributes
vcs_ref_base_name VARCHAR,
vcs_ref_base_revision VARCHAR,
vcs_ref_base_type VARCHAR,
vcs_ref_head_name VARCHAR,
vcs_ref_head_revision VARCHAR,
vcs_ref_head_type VARCHAR,
vcs_ref_type VARCHAR,

-- vcs.repository attributes
vcs_repository_change_id VARCHAR,
vcs_repository_change_title VARCHAR,
vcs_repository_name VARCHAR,
vcs_repository_ref_name VARCHAR,
vcs_repository_ref_revision VARCHAR,
vcs_repository_ref_type VARCHAR,
vcs_repository_url_full VARCHAR,

-- vcs.revision_delta attributes
vcs_revision_delta_direction VARCHAR,

-- webengine.description attributes
webengine_description VARCHAR,

-- webengine.name attributes
webengine_name VARCHAR,

-- webengine.version attributes
webengine_version VARCHAR,
