using qyl.mcp.Skills;

namespace qyl.mcp.Capabilities;

internal sealed record QylCapabilityDescriptor
{
    public required string Id { get; init; }
    public required string Title { get; init; }
    public required string Summary { get; init; }
    public required string Skill { get; init; }
    public QylSkillKind? RequiredSkill { get; init; }
    public IReadOnlyList<string> Tags { get; init; } = [];
    public IReadOnlyList<string> ToolNames { get; init; } = [];
    public IReadOnlyList<string> UseCases { get; init; } = [];
    public IReadOnlyList<string> PrimaryIdentifiers { get; init; } = [];
    public IReadOnlyList<string> StartingTools { get; init; } = [];
    public IReadOnlyList<string> FollowUpTools { get; init; } = [];
    public IReadOnlyList<string> ScopingHints { get; init; } = [];
    public IReadOnlyList<string> EvidenceHints { get; init; } = [];
    public IReadOnlyList<string> RelatedCapabilityIds { get; init; } = [];
}

internal static class QylCapabilityCatalog
{
    private static readonly IReadOnlyList<QylCapabilityDescriptor> All =
    [
        new() { Id = "server_introspection", Title = "Server Introspection", Summary = "Discover qyl.mcp capabilities, enabled skill families, and the smallest useful tool chain before starting an investigation.", Skill = "core", Tags = ["mcp", "planning", "discovery", "server"], ToolNames = ["qyl.list_capabilities", "qyl.get_capability_guide", "whoami"], UseCases = ["Find the right investigation entrypoint before using a high-cost meta-agent.", "Check which observability domains are currently enabled by QYL_SKILLS."], PrimaryIdentifiers = ["capability_id", "skill", "tag"], StartingTools = ["qyl.list_capabilities", "qyl.get_capability_guide"], FollowUpTools = ["whoami"], ScopingHints = ["Capability discovery is transport-local and does not require collector scoping."], EvidenceHints = ["Use the guide to choose the smallest sufficient tool chain before escalating to qyl.use_qyl."], RelatedCapabilityIds = ["trace_investigation", "agentic_investigation"] },
        new() { Id = "trace_investigation", Title = "Trace Investigation", Summary = "Search traces, inspect span trees, correlate latency and failure boundaries, and escalate to RCA only after evidence is captured.", Skill = "inspect", RequiredSkill = QylSkillKind.Inspect, Tags = ["traces", "spans", "latency", "otel"], ToolNames = ["search_traces", "get_trace_details", "get_span", "get_profile", "qyl.search_spans", "analyze_trace", "qyl.summarize_trace", "qyl.root_cause_analysis"], UseCases = ["Investigate a slow or failing request path.", "Walk from trace-level symptoms down to span-level bottlenecks."], PrimaryIdentifiers = ["trace_id", "span_id", "service_name", "duration_ms", "status"], StartingTools = ["search_traces", "get_trace_details"], FollowUpTools = ["get_span", "qyl.search_spans", "qyl.list_trace_logs", "qyl.root_cause_analysis"], ScopingHints = ["Apply QYL_SERVICE before wide trace searches when the issue is isolated to one service.", "Carry trace_id into logs and session tools whenever correlation is available."], EvidenceHints = ["Compare root-span duration with child-span duration before blaming the root service.", "Treat high latency and error status as separate signals that may diverge."], RelatedCapabilityIds = ["log_investigation", "error_investigation", "agentic_investigation"] },
        new() { Id = "error_investigation", Title = "Error Investigation", Summary = "Move from issue-level symptoms into event details, breadcrumbs, attachments, and timelines before mutating triage state.", Skill = "inspect", RequiredSkill = QylSkillKind.Inspect, Tags = ["errors", "issues", "events", "breadcrumbs"], ToolNames = ["qyl.list_error_issues", "qyl.get_error_issue", "qyl.find_similar_errors", "qyl.get_error_timeline", "get_breadcrumbs", "get_attachments", "get_tag_distribution", "qyl.summarize_error"], UseCases = ["Investigate a recurring application or agent error.", "Distinguish one-off failures from clustered issue families."], PrimaryIdentifiers = ["issue_id", "event_id", "fingerprint", "service_name"], StartingTools = ["qyl.list_error_issues", "qyl.get_error_issue"], FollowUpTools = ["qyl.get_error_timeline", "get_breadcrumbs", "get_tag_distribution", "qyl.find_similar_errors"], ScopingHints = ["Use service scoping first if the issue belongs to a known service boundary.", "Use issue identifiers rather than free-text error messages once the issue is known."], EvidenceHints = ["Breadcrumbs explain the sequence leading to failure, not just the failure point.", "Tag distributions are useful for blast radius estimation across environments, releases, or tenants."], RelatedCapabilityIds = ["trace_investigation", "loom_triage_and_fix"] },
        new() { Id = "log_investigation", Title = "Log Investigation", Summary = "Search logs directly or pivot from a trace to its structured logs to confirm request-level evidence and runtime context.", Skill = "inspect", RequiredSkill = QylSkillKind.Inspect, Tags = ["logs", "structured", "trace-correlation"], ToolNames = ["search_logs", "get_log_details", "qyl.search_logs", "qyl.list_structured_logs", "qyl.list_trace_logs"], UseCases = ["Confirm runtime context around a trace, issue, or session.", "Search for matching log lines across severity and time windows."], PrimaryIdentifiers = ["log_id", "trace_id", "span_id", "session_id", "severity"], StartingTools = ["search_logs", "qyl.list_trace_logs"], FollowUpTools = ["get_log_details", "qyl.search_logs", "get_trace_details"], ScopingHints = ["Trace-correlated log tools are preferable once a trace_id is known.", "Use QYL_SESSION to narrow logs when replay/session context is already established."], EvidenceHints = ["Structured logs often reveal request parameters and dependency outcomes missing from span attributes.", "Severity alone is insufficient; correlate on trace_id or session_id when possible."], RelatedCapabilityIds = ["trace_investigation", "session_investigation"] },
        new() { Id = "session_investigation", Title = "Session Investigation", Summary = "Investigate end-user or agent sessions, replay transcripts, and correlated traces to reconstruct multi-step behavior.", Skill = "inspect", RequiredSkill = QylSkillKind.Inspect, Tags = ["sessions", "replay", "transcript", "journey"], ToolNames = ["search_sessions", "get_session", "qyl.list_sessions", "qyl.get_session_transcript", "qyl.get_trace", "qyl.analyze_session_errors", "analyze_session", "qyl.summarize_session"], UseCases = ["Explain what happened in a specific agent or user session.", "Correlate replay evidence with traces and error surfaces."], PrimaryIdentifiers = ["session_id", "trace_id", "service_name", "status"], StartingTools = ["search_sessions", "get_session"], FollowUpTools = ["qyl.get_session_transcript", "qyl.get_trace", "qyl.analyze_session_errors"], ScopingHints = ["QYL_SESSION should be set whenever repeated drill-down calls stay within a single session.", "Session investigations often narrow log search more effectively than broad time ranges."], EvidenceHints = ["Transcripts explain user-visible flow; traces explain system-visible flow.", "Use both before concluding whether the failure is UX, orchestration, or backend."], RelatedCapabilityIds = ["trace_investigation", "log_investigation", "analytics"] },
        new() { Id = "service_discovery", Title = "Service and Release Discovery", Summary = "List projects and services, inspect service topology, and tie health regressions back to release boundaries.", Skill = "inspect", RequiredSkill = QylSkillKind.Inspect, Tags = ["services", "topology", "release", "projects"], ToolNames = ["list_projects", "list_services", "qyl.list_services", "get_service_map", "get_release_health"], UseCases = ["Understand the service landscape before starting deep investigation.", "Check whether a release boundary lines up with a new failure pattern."], PrimaryIdentifiers = ["project_slug", "service_name", "release"], StartingTools = ["list_projects", "list_services"], FollowUpTools = ["get_service_map", "get_release_health"], ScopingHints = ["Use project_slug to bound multi-tenant or multi-project environments early.", "Service scoping becomes more valuable after topology inspection identifies the blast radius."], EvidenceHints = ["A service map explains dependency direction, not necessarily root cause ownership.", "Release health is strongest when paired with traces or issue spikes around the same window."], RelatedCapabilityIds = ["trace_investigation", "anomaly_detection"] },
        new() { Id = "metrics_analysis", Title = "Metrics Analysis", Summary = "Enumerate metrics, query timeseries, and baseline operational behavior before escalating to anomaly or regression workflows.", Skill = "inspect", RequiredSkill = QylSkillKind.Inspect, Tags = ["metrics", "timeseries", "baseline"], ToolNames = ["list_metrics", "query_metrics"], UseCases = ["Inspect an operational metric directly.", "Build context before anomaly detection or RCA."], PrimaryIdentifiers = ["metric_name", "time_range", "service_name"], StartingTools = ["list_metrics", "query_metrics"], FollowUpTools = ["qyl.detect_anomalies", "qyl.get_metric_baseline"], ScopingHints = ["Use service scoping when the metric is emitted by one service family.", "Keep time windows tight before escalating to expensive downstream workflows."], EvidenceHints = ["Look for slope changes and sustained level shifts, not just single spikes.", "A metric query gives shape; anomaly tools explain deviation strength."], RelatedCapabilityIds = ["anomaly_detection", "trace_investigation"] },
        new() { Id = "genai_observability", Title = "GenAI Observability", Summary = "Track provider, model, token, cost, and latency behavior for agent and LLM workloads, then pivot into traces or sessions when needed.", Skill = "inspect", RequiredSkill = QylSkillKind.Inspect, Tags = ["genai", "tokens", "cost", "latency", "models"], ToolNames = ["qyl.get_genai_stats", "qyl.list_genai_spans", "qyl.list_models", "qyl.get_token_timeseries", "qyl.get_token_usage", "qyl.search_agent_runs", "qyl.get_agent_run", "qyl.get_latency_stats", "qyl.list_errors"], UseCases = ["Compare model or provider behavior over time.", "Investigate token, latency, or cost spikes in agent workloads."], PrimaryIdentifiers = ["provider", "model_name", "run_id", "service_name", "time_range"], StartingTools = ["qyl.get_genai_stats", "qyl.list_genai_spans"], FollowUpTools = ["qyl.get_token_usage", "qyl.get_token_timeseries", "qyl.search_agent_runs", "qyl.get_agent_run"], ScopingHints = ["Service scoping is often the fastest way to isolate one agent pipeline.", "Model and provider filters are more useful than raw trace pivots during early triage."], EvidenceHints = ["Token spikes and latency spikes are related but not equivalent.", "Provider health issues often appear as cross-model latency changes before hard failures."], RelatedCapabilityIds = ["agentic_investigation", "trace_investigation"] },
        new() { Id = "health_and_storage", Title = "Health and Storage", Summary = "Check overall collector/system health and storage posture before concluding an investigation is product-specific.", Skill = "health", RequiredSkill = QylSkillKind.Health, Tags = ["health", "storage", "system"], ToolNames = ["qyl.health_check", "qyl.get_storage_stats", "qyl.get_system_context"], UseCases = ["Rule out platform-level issues early.", "Inspect resource pressure before investigating application-specific symptoms."], PrimaryIdentifiers = ["service_name", "storage_backend", "time_range"], StartingTools = ["qyl.health_check", "qyl.get_system_context"], FollowUpTools = ["qyl.get_storage_stats"], ScopingHints = ["Health tools are usually most useful before service-specific scoping is applied.", "Use system context as the control-plane baseline for later evidence."], EvidenceHints = ["If health is degraded globally, downstream trace or error symptoms may be secondary effects.", "Storage pressure can explain missing or partial observability data."], RelatedCapabilityIds = ["trace_investigation", "genai_observability"] },
        new() { Id = "analytics", Title = "Conversation and User Analytics", Summary = "Inspect conversations, coverage gaps, source analytics, satisfaction, and user journeys to evaluate product behavior over time.", Skill = "analytics", RequiredSkill = QylSkillKind.Analytics, Tags = ["analytics", "conversations", "coverage", "journeys"], ToolNames = ["qyl.list_conversations", "qyl.get_conversation", "qyl.get_coverage_gaps", "qyl.get_top_questions", "qyl.get_source_analytics", "qyl.get_satisfaction", "qyl.list_users", "qyl.get_user_journey"], UseCases = ["Understand what users or agents are asking for most often.", "Find coverage gaps and degraded experience trends."], PrimaryIdentifiers = ["conversation_id", "user_id", "source", "time_range"], StartingTools = ["qyl.list_conversations", "qyl.get_top_questions"], FollowUpTools = ["qyl.get_conversation", "qyl.get_user_journey", "qyl.get_coverage_gaps"], ScopingHints = ["Analytics work is usually time-window driven rather than service-scoped.", "Pivot to user_id or source once you have a pattern worth explaining."], EvidenceHints = ["Top questions explain demand; satisfaction explains outcome quality.", "Coverage gaps should be tied back to traces, errors, or sessions before proposing fixes."], RelatedCapabilityIds = ["session_investigation", "agentic_investigation"] },
        new() { Id = "agentic_investigation", Title = "Agentic Investigation", Summary = "Use qyl's embedded investigation and summarization tools for multi-step reasoning after narrower evidence-oriented tools have established context.", Skill = "agent", RequiredSkill = QylSkillKind.Agent, Tags = ["agent", "rca", "summaries", "reasoning"], ToolNames = ["qyl.use_qyl", "qyl.root_cause_analysis", "qyl.summarize_trace", "qyl.summarize_error", "qyl.summarize_session", "qyl.list_diagnostic_patterns", "qyl.suggest_investigation", "qyl.evaluate_patterns", "qyl.execute_investigation_step", "qyl.explain_causal_chain", "suggest_fix"], UseCases = ["Ask a complex multi-domain question after collecting concrete evidence.", "Summarize or explain causal structure across traces, errors, sessions, and analytics."], PrimaryIdentifiers = ["question", "trace_id", "issue_id", "session_id"], StartingTools = ["qyl.suggest_investigation", "qyl.use_qyl"], FollowUpTools = ["qyl.root_cause_analysis", "qyl.summarize_trace", "qyl.summarize_error", "suggest_fix"], ScopingHints = ["Set QYL_SERVICE or QYL_SESSION before invoking broad agentic tools whenever possible.", "Pass concrete IDs into the question or context so the agent does not waste tool budget rediscovering them."], EvidenceHints = ["Agentic tools are strongest when grounded in previously collected telemetry facts.", "Use summaries as compression layers, not as the first source of truth."], RelatedCapabilityIds = ["trace_investigation", "error_investigation", "loom_triage_and_fix"] },
        new() { Id = "project_and_access_management", Title = "Project and Access Management", Summary = "Manage projects, retention, API keys, teams, and DSNs from the MCP server when operational workflows need bounded write actions.", Skill = "build", RequiredSkill = QylSkillKind.Build, Tags = ["projects", "retention", "access", "dsn", "teams"], ToolNames = ["create_project", "update_project", "configure_retention", "create_api_key", "create_team", "list_teams", "create_dsn", "list_dsns", "whoami"], UseCases = ["Create or update qyl project configuration.", "Manage access material and routing information required by instrumentation."], PrimaryIdentifiers = ["project_slug", "team_id", "dsn", "api_key"], StartingTools = ["list_teams", "whoami"], FollowUpTools = ["create_project", "update_project", "configure_retention", "create_api_key", "create_dsn"], ScopingHints = ["Management tools usually operate on explicit identifiers rather than environment scope injection.", "Establish identity first when access or role uncertainty is part of the workflow."], EvidenceHints = ["These are state-changing tools; use discovery tools first to confirm intent.", "Keep configuration changes narrow and explicit to avoid accidental blast radius."], RelatedCapabilityIds = ["service_discovery", "health_and_storage"] },
        new() { Id = "anomaly_detection", Title = "Anomaly Detection", Summary = "Detect unusual behavior, compare periods, and establish metric baselines before escalating to regression or RCA workflows.", Skill = "anomaly", RequiredSkill = QylSkillKind.Anomaly, Tags = ["anomaly", "baseline", "period-comparison", "metrics"], ToolNames = ["qyl.detect_anomalies", "qyl.get_metric_baseline", "qyl.compare_periods"], UseCases = ["Determine whether current behavior is outside the normal operating envelope.", "Compare one release or time window against another."], PrimaryIdentifiers = ["metric_name", "service_name", "baseline_window", "comparison_window"], StartingTools = ["qyl.detect_anomalies", "qyl.get_metric_baseline"], FollowUpTools = ["qyl.compare_periods", "search_traces", "qyl.check_regressions"], ScopingHints = ["Metric-level anomaly work is usually best scoped by service before comparing windows.", "Keep comparison windows aligned to release or deployment boundaries whenever possible."], EvidenceHints = ["An anomaly score is not a root cause; it is evidence of deviation.", "Always pivot back to traces, errors, or release boundaries after finding deviation."], RelatedCapabilityIds = ["metrics_analysis", "loom_triage_and_fix", "trace_investigation"] },
        new() { Id = "loom_triage_and_fix", Title = "Loom Triage and Fix Pipeline", Summary = "Drive qyl's AI-assisted triage, autofix, regression, code review, and handoff workflows once issue evidence is stable enough for action.", Skill = "loom", RequiredSkill = QylSkillKind.Loom, Tags = ["loom", "triage", "fix", "regression", "github"], ToolNames = ["qyl.get_triage", "qyl.list_triage", "qyl.trigger_triage", "qyl.list_fix_runs", "qyl.get_fix_run", "qyl.get_fix_run_steps", "qyl.approve_fix_run", "qyl.reject_fix_run", "qyl.generate_fix", "qyl.export_for_agent", "qyl.generate_test_from_error", "qyl.assisted_query", "qyl.trigger_code_review", "qyl.get_code_review", "qyl.list_github_events", "qyl.check_regressions", "qyl.list_regressions", "qyl.get_issue_regressions"], UseCases = ["Move from investigation into bounded remediation workflows.", "Inspect or control the state of a fix pipeline tied to an issue or regression."], PrimaryIdentifiers = ["issue_id", "run_id", "triage_id", "pull_request", "regression_event"], StartingTools = ["qyl.get_triage", "qyl.list_fix_runs", "qyl.check_regressions"], FollowUpTools = ["qyl.get_fix_run", "qyl.get_fix_run_steps", "qyl.export_for_agent", "qyl.trigger_code_review", "qyl.approve_fix_run"], ScopingHints = ["Stay issue-centric once a Loom workflow begins; avoid dropping back to broad searches.", "Use regression tools to establish change boundaries before generating fixes."], EvidenceHints = ["Pipeline state is execution truth, not necessarily business truth.", "Fix approval should follow concrete trace, error, and regression evidence."], RelatedCapabilityIds = ["error_investigation", "agentic_investigation", "anomaly_detection"] },
        new() { Id = "mcp_apps", Title = "Interactive MCP Apps", Summary = "Open qyl's interactive app surfaces for traces, errors, and query workflows when a visual or operator-facing experience is better than raw tool chaining.", Skill = "apps", RequiredSkill = QylSkillKind.Apps, Tags = ["apps", "ui", "trace-viewer", "query-studio"], ToolNames = ["qyl.app.trace_viewer", "qyl.app.trace_search", "qyl.app.error_explorer", "qyl.app.query_studio", "qyl.app.execute_query", "qyl.app.query_schema"], UseCases = ["Launch a visual investigation aid from an MCP host.", "Inspect query schema or execute targeted queries through a UI-oriented workflow."], PrimaryIdentifiers = ["trace_id", "issue_id", "query"], StartingTools = ["qyl.app.trace_viewer", "qyl.app.error_explorer", "qyl.app.query_studio"], FollowUpTools = ["qyl.app.trace_search", "qyl.app.execute_query", "qyl.app.query_schema"], ScopingHints = ["App tools are best when a host supports MCP app resources cleanly.", "Use low-level tools first if you only need one fact, not an interactive surface."], EvidenceHints = ["Apps are presentation surfaces over the same telemetry contracts; they do not replace evidence capture.", "Prefer UI flows when human operator inspection is part of the workflow."], RelatedCapabilityIds = ["trace_investigation", "error_investigation", "service_discovery"] },
        new() { Id = "debugger_control", Title = "Debugger Control", Summary = "Proxy into the Rider debugger MCP surface to inspect program state, set breakpoints, and walk execution when telemetry evidence points to live-code debugging.", Skill = "debug", RequiredSkill = QylSkillKind.Debug, Tags = ["debugger", "rider", "breakpoints", "frames"], ToolNames = ["qyl.debug.status", "qyl.debug.list_available_tools", "qyl.debug.list_run_configs", "qyl.debug.start_session", "qyl.debug.stop_session", "qyl.debug.list_sessions", "qyl.debug.session_status", "qyl.debug.set_breakpoint", "qyl.debug.remove_breakpoint", "qyl.debug.list_breakpoints", "qyl.debug.resume", "qyl.debug.pause", "qyl.debug.step_over", "qyl.debug.step_into", "qyl.debug.step_out", "qyl.debug.run_to_line", "qyl.debug.evaluate", "qyl.debug.get_variables", "qyl.debug.set_variable", "qyl.debug.get_stack_trace", "qyl.debug.list_threads", "qyl.debug.select_frame", "qyl.debug.get_source"], UseCases = ["Move from telemetry evidence into a live debugger session.", "Inspect runtime values after traces or errors isolate a suspected code path."], PrimaryIdentifiers = ["session_id", "frame_index", "file_path", "line_number", "breakpoint_id"], StartingTools = ["qyl.debug.status", "qyl.debug.list_run_configs", "qyl.debug.start_session"], FollowUpTools = ["qyl.debug.set_breakpoint", "qyl.debug.get_stack_trace", "qyl.debug.get_variables", "qyl.debug.evaluate"], ScopingHints = ["Debugger workflows are live-state operations and do not use collector service/session injection.", "Keep debugger sessions tied to one hypothesis at a time."], EvidenceHints = ["Use debugger control only after telemetry has already isolated a likely code path.", "Debugger state explains current execution, not historical production evidence."], RelatedCapabilityIds = ["trace_investigation", "error_investigation"] },
    ];

    public static IReadOnlyList<QylCapabilityDescriptor> GetEnabled(SkillConfiguration skills) =>
        [.. All.Where(capability => capability.RequiredSkill is null || skills.IsEnabled(capability.RequiredSkill.Value))
            .OrderBy(capability => capability.Title, StringComparer.Ordinal)];

    public static QylCapabilityDescriptor? FindEnabled(string capabilityId, SkillConfiguration skills) =>
        GetEnabled(skills).FirstOrDefault(capability => capability.Id.EqualsIgnoreCase(capabilityId));
}
