// <auto-generated/>
// Generated from eng/semconv/model/qyl/ via Weaver
// Do not edit manually - run 'nuke GenerateSemconv'
// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace QylAttr;

/// <summary>Attributes for qyl authentication context on spans</summary>
public static class Auth
{
    /// <summary>Serialized Keycloak JWT claims attached to a request span. High-cardinality — only emit when ENABLE_SENSITIVE_DATA is set.</summary>
    public const string KeycloakClaims = "qyl.keycloak.claims";
    /// <summary>Stable instance identifier for log correlation (typically hostname)</summary>
    public const string InstanceId = "qyl.instance_id";
}

/// <summary>Attributes for qyl capability tracking on spans</summary>
public static class Capability
{
    /// <summary>Unique capability identifier declared via [QylCapability] at compile time.</summary>
    public const string Id = "qyl.capability.id";
    /// <summary>Capability kind: Starting or FollowUp</summary>
    public const string Kind = "qyl.capability.kind";
}

/// <summary>Counters for qyl DuckDB write pipeline</summary>
public static class Duckdb
{
    /// <summary>Cumulative count of background write jobs dropped (back-pressure)</summary>
    public const string DroppedJobsTotal = "qyl.duckdb.dropped_jobs_total";
    /// <summary>Cumulative count of span records dropped before persistence</summary>
    public const string DroppedSpansTotal = "qyl.duckdb.dropped_spans_total";
}

/// <summary>Attributes for qyl automated fix runs</summary>
public static class FixRun
{
    /// <summary>Fix run identifier</summary>
    public const string Id = "qyl.fix_run.id";
    /// <summary>Current status of the fix run</summary>
    public const string Status = "qyl.fix_run.status";
    /// <summary>What initiated this fix run</summary>
    public const string Trigger = "qyl.fix_run.trigger";
}

/// <summary>Attributes for qyl error issue tracking</summary>
public static class Issue
{
    /// <summary>Error issue identifier</summary>
    public const string Id = "qyl.issue.id";
    /// <summary>Issue severity level</summary>
    public const string Severity = "qyl.issue.severity";
    /// <summary>Current resolution status</summary>
    public const string Status = "qyl.issue.status";
}

/// <summary>Attributes identifying the qyl project scope</summary>
public static class Project
{
    /// <summary>Project identifier (UUID or slug)</summary>
    public const string Id = "qyl.project.id";
    /// <summary>Human-readable project name</summary>
    public const string Name = "qyl.project.name";
}

/// <summary>Attributes for qyl agent run tracking</summary>
public static class Run
{
    /// <summary>Agent run identifier</summary>
    public const string Id = "qyl.run.id";
    /// <summary>Kind of agent run</summary>
    public const string Kind = "qyl.run.kind";
    /// <summary>Final or current status of the run</summary>
    public const string Status = "qyl.run.status";
}

/// <summary>Attributes for qyl DuckDB storage instrumentation</summary>
public static class Storage
{
    /// <summary>Current DuckDB database file size in bytes</summary>
    public const string Size = "qyl.storage.size";
}

/// <summary>Attributes identifying the owning team</summary>
public static class Team
{
    /// <summary>Team identifier</summary>
    public const string Id = "qyl.team.id";
    /// <summary>Human-readable team name</summary>
    public const string Name = "qyl.team.name";
}

/// <summary>Attributes for qyl automated triage operations</summary>
public static class Triage
{
    /// <summary>Triage record identifier</summary>
    public const string Id = "qyl.triage.id";
    /// <summary>Triage priority score (0.0 = lowest, 1.0 = highest)</summary>
    public const string Score = "qyl.triage.score";
    /// <summary>Classified error category from triage analysis</summary>
    public const string Category = "qyl.triage.category";
}

/// <summary>Attributes for qyl API key tracking (masked for security)</summary>
public static class ApiKey
{
    /// <summary>First 8 characters of the API key hash (sha256[:8]). Never log the full key.</summary>
    public const string Id = "qyl.api_key.id";
}
