// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Thread;

/// <summary>Thread Attributes (incubating).</summary>
public static class ThreadAttributes
{
    /// <summary>Current "managed" thread ID (as opposed to OS thread ID)..</summary>
    /// <remarks>Examples of where the value can be extracted from:  | Language or platform | Source | | --- | --- | | JVM | `Thread.currentThread().threadId()` | | .NET | `Thread.CurrentThread.ManagedThreadId` | | Python | `threading.current_thread().ident` | | Ruby | `Thread.current.object_id` | | C++ | `std::this_thread::get_id()` | | Erlang | `erlang:self()` |</remarks>
    public const string Id = "thread.id";

    /// <summary>Current thread name..</summary>
    /// <remarks>Examples of where the value can be extracted from:  | Language or platform | Source | | --- | --- | | JVM | `Thread.currentThread().getName()` | | .NET | `Thread.CurrentThread.Name` | | Python | `threading.current_thread().name` | | Ruby | `Thread.current.name` | | Erlang | `erlang:process_info(self(), registered_name)` |</remarks>
    public const string Name = "thread.name";

}