// <auto-generated/>
// Generated from @opentelemetry/semantic-conventions v1.39.0
// Domain: cloudfoundry
// Do not edit manually - run 'npm run generate:package' in SemconvGenerator

namespace OTelConventions;

/// <summary>
/// Semantic convention attributes for cloudfoundry.app.*
/// </summary>
public static class CloudfoundryAppAttributes
{
    /// <summary>cloudfoundry.app.id</summary>
    public const string Id = "cloudfoundry.app.id";

    /// <summary>cloudfoundry.app.instance.id</summary>
    public const string InstanceId = "cloudfoundry.app.instance.id";

    /// <summary>cloudfoundry.app.name</summary>
    public const string Name = "cloudfoundry.app.name";

}

/// <summary>
/// Semantic convention attributes for cloudfoundry.org.*
/// </summary>
public static class CloudfoundryOrgAttributes
{
    /// <summary>cloudfoundry.org.id</summary>
    public const string Id = "cloudfoundry.org.id";

    /// <summary>cloudfoundry.org.name</summary>
    public const string Name = "cloudfoundry.org.name";

}

/// <summary>
/// Semantic convention attributes for cloudfoundry.process.*
/// </summary>
public static class CloudfoundryProcessAttributes
{
    /// <summary>cloudfoundry.process.id</summary>
    public const string Id = "cloudfoundry.process.id";

    /// <summary>cloudfoundry.process.type</summary>
    public const string Type = "cloudfoundry.process.type";

}

/// <summary>
/// Semantic convention attributes for cloudfoundry.space.*
/// </summary>
public static class CloudfoundrySpaceAttributes
{
    /// <summary>cloudfoundry.space.id</summary>
    public const string Id = "cloudfoundry.space.id";

    /// <summary>cloudfoundry.space.name</summary>
    public const string Name = "cloudfoundry.space.name";

}

/// <summary>
/// Semantic convention attributes for cloudfoundry.system.*
/// </summary>
public static class CloudfoundrySystemAttributes
{
    /// <summary>cloudfoundry.system.id</summary>
    public const string Id = "cloudfoundry.system.id";

    /// <summary>cloudfoundry.system.instance.id</summary>
    public const string InstanceId = "cloudfoundry.system.instance.id";

}
