// <auto-generated/>
// Generated from @opentelemetry/semantic-conventions v1.39.0
// Domain: code
// Do not edit manually - run 'npm run generate:package' in SemconvGenerator

namespace OTelConventions;

/// <summary>
/// Semantic convention attributes for code.column.*
/// </summary>
public static class CodeColumnAttributes
{
    /// <summary>code.column.number</summary>
    public const string Number = "code.column.number";

    /// <summary>code.column</summary>
    public const string Column = "code.column";

}

/// <summary>
/// Semantic convention attributes for code.file.*
/// </summary>
public static class CodeFileAttributes
{
    /// <summary>code.file.path</summary>
    public const string Path = "code.file.path";

}

/// <summary>
/// Semantic convention attributes for code.function.*
/// </summary>
public static class CodeFunctionAttributes
{
    /// <summary>code.function.name</summary>
    public const string Name = "code.function.name";

    /// <summary>code.function</summary>
    public const string Function = "code.function";

}

/// <summary>
/// Semantic convention attributes for code.line.*
/// </summary>
public static class CodeLineAttributes
{
    /// <summary>code.line.number</summary>
    public const string Number = "code.line.number";

}

/// <summary>
/// Semantic convention attributes for code.stacktrace.*
/// </summary>
public static class CodeStacktraceAttributes
{
    /// <summary>code.stacktrace</summary>
    public const string Stacktrace = "code.stacktrace";

}

/// <summary>
/// Semantic convention attributes for code.filepath.*
/// </summary>
public static class CodeFilepathAttributes
{
    /// <summary>code.filepath</summary>
    public const string Filepath = "code.filepath";

}

/// <summary>
/// Semantic convention attributes for code.lineno.*
/// </summary>
public static class CodeLinenoAttributes
{
    /// <summary>code.lineno</summary>
    public const string Lineno = "code.lineno";

}

/// <summary>
/// Semantic convention attributes for code.namespace.*
/// </summary>
public static class CodeNamespaceAttributes
{
    /// <summary>code.namespace</summary>
    public const string Namespace = "code.namespace";

}
