// <auto-generated/>
// Generated from @opentelemetry/semantic-conventions v1.39.0
// Domain: db
// Do not edit manually - run 'npm run generate:package' in SemconvGenerator

namespace OTelConventions;

/// <summary>
/// Semantic convention attributes for db.collection.*
/// </summary>
public static class DbCollectionAttributes
{
    /// <summary>db.collection.name</summary>
    public const string Name = "db.collection.name";

}

/// <summary>
/// Semantic convention attributes for db.namespace.*
/// </summary>
public static class DbNamespaceAttributes
{
    /// <summary>db.namespace</summary>
    public const string Namespace = "db.namespace";

}

/// <summary>
/// Semantic convention attributes for db.operation.*
/// </summary>
public static class DbOperationAttributes
{
    /// <summary>db.operation.batch.size</summary>
    public const string BatchSize = "db.operation.batch.size";

    /// <summary>db.operation.name</summary>
    public const string Name = "db.operation.name";

    /// <summary>db.operation</summary>
    public const string Operation = "db.operation";

}

/// <summary>
/// Semantic convention attributes for db.query.*
/// </summary>
public static class DbQueryAttributes
{
    /// <summary>db.query.summary</summary>
    public const string Summary = "db.query.summary";

    /// <summary>db.query.text</summary>
    public const string Text = "db.query.text";

}

/// <summary>
/// Semantic convention attributes for db.response.*
/// </summary>
public static class DbResponseAttributes
{
    /// <summary>db.response.status_code</summary>
    public const string StatusCode = "db.response.status_code";

    /// <summary>db.response.returned_rows</summary>
    public const string ReturnedRows = "db.response.returned_rows";

}

/// <summary>
/// Semantic convention attributes for db.stored_procedure.*
/// </summary>
public static class DbStoredProcedureAttributes
{
    /// <summary>db.stored_procedure.name</summary>
    public const string Name = "db.stored_procedure.name";

}

/// <summary>
/// Semantic convention attributes for db.system.*
/// </summary>
public static class DbSystemAttributes
{
    /// <summary>db.system.name</summary>
    public const string Name = "db.system.name";

    /// <summary>db.system</summary>
    public const string System = "db.system";

}

/// <summary>
/// Semantic convention attributes for db.cassandra.*
/// </summary>
public static class DbCassandraAttributes
{
    /// <summary>db.cassandra.consistency_level</summary>
    public const string ConsistencyLevel = "db.cassandra.consistency_level";

    /// <summary>db.cassandra.coordinator.dc</summary>
    public const string CoordinatorDc = "db.cassandra.coordinator.dc";

    /// <summary>db.cassandra.coordinator.id</summary>
    public const string CoordinatorId = "db.cassandra.coordinator.id";

    /// <summary>db.cassandra.idempotence</summary>
    public const string Idempotence = "db.cassandra.idempotence";

    /// <summary>db.cassandra.page_size</summary>
    public const string PageSize = "db.cassandra.page_size";

    /// <summary>db.cassandra.speculative_execution_count</summary>
    public const string SpeculativeExecutionCount = "db.cassandra.speculative_execution_count";

    /// <summary>db.cassandra.table</summary>
    public const string Table = "db.cassandra.table";

}

/// <summary>
/// Semantic convention attributes for db.client.*
/// </summary>
public static class DbClientAttributes
{
    /// <summary>db.client.connection.pool.name</summary>
    public const string ConnectionPoolName = "db.client.connection.pool.name";

    /// <summary>db.client.connection.state</summary>
    public const string ConnectionState = "db.client.connection.state";

    /// <summary>db.client.connections.pool.name</summary>
    public const string ConnectionsPoolName = "db.client.connections.pool.name";

    /// <summary>db.client.connections.state</summary>
    public const string ConnectionsState = "db.client.connections.state";

}

/// <summary>
/// Semantic convention attributes for db.connection_string.*
/// </summary>
public static class DbConnectionStringAttributes
{
    /// <summary>db.connection_string</summary>
    public const string Connection_string = "db.connection_string";

}

/// <summary>
/// Semantic convention attributes for db.cosmosdb.*
/// </summary>
public static class DbCosmosdbAttributes
{
    /// <summary>db.cosmosdb.client_id</summary>
    public const string ClientId = "db.cosmosdb.client_id";

    /// <summary>db.cosmosdb.connection_mode</summary>
    public const string ConnectionMode = "db.cosmosdb.connection_mode";

    /// <summary>db.cosmosdb.consistency_level</summary>
    public const string ConsistencyLevel = "db.cosmosdb.consistency_level";

    /// <summary>db.cosmosdb.container</summary>
    public const string Container = "db.cosmosdb.container";

    /// <summary>db.cosmosdb.operation_type</summary>
    public const string OperationType = "db.cosmosdb.operation_type";

    /// <summary>db.cosmosdb.regions_contacted</summary>
    public const string RegionsContacted = "db.cosmosdb.regions_contacted";

    /// <summary>db.cosmosdb.request_charge</summary>
    public const string RequestCharge = "db.cosmosdb.request_charge";

    /// <summary>db.cosmosdb.request_content_length</summary>
    public const string RequestContentLength = "db.cosmosdb.request_content_length";

    /// <summary>db.cosmosdb.status_code</summary>
    public const string StatusCode = "db.cosmosdb.status_code";

    /// <summary>db.cosmosdb.sub_status_code</summary>
    public const string SubStatusCode = "db.cosmosdb.sub_status_code";

}

/// <summary>
/// Semantic convention attributes for db.elasticsearch.*
/// </summary>
public static class DbElasticsearchAttributes
{
    /// <summary>db.elasticsearch.cluster.name</summary>
    public const string ClusterName = "db.elasticsearch.cluster.name";

    /// <summary>db.elasticsearch.node.name</summary>
    public const string NodeName = "db.elasticsearch.node.name";

}

/// <summary>
/// Semantic convention attributes for db.instance.*
/// </summary>
public static class DbInstanceAttributes
{
    /// <summary>db.instance.id</summary>
    public const string Id = "db.instance.id";

}

/// <summary>
/// Semantic convention attributes for db.jdbc.*
/// </summary>
public static class DbJdbcAttributes
{
    /// <summary>db.jdbc.driver_classname</summary>
    public const string DriverClassname = "db.jdbc.driver_classname";

}

/// <summary>
/// Semantic convention attributes for db.mongodb.*
/// </summary>
public static class DbMongodbAttributes
{
    /// <summary>db.mongodb.collection</summary>
    public const string Collection = "db.mongodb.collection";

}

/// <summary>
/// Semantic convention attributes for db.mssql.*
/// </summary>
public static class DbMssqlAttributes
{
    /// <summary>db.mssql.instance_name</summary>
    public const string InstanceName = "db.mssql.instance_name";

}

/// <summary>
/// Semantic convention attributes for db.name.*
/// </summary>
public static class DbNameAttributes
{
    /// <summary>db.name</summary>
    public const string Name = "db.name";

}

/// <summary>
/// Semantic convention attributes for db.redis.*
/// </summary>
public static class DbRedisAttributes
{
    /// <summary>db.redis.database_index</summary>
    public const string DatabaseIndex = "db.redis.database_index";

}

/// <summary>
/// Semantic convention attributes for db.sql.*
/// </summary>
public static class DbSqlAttributes
{
    /// <summary>db.sql.table</summary>
    public const string Table = "db.sql.table";

}

/// <summary>
/// Semantic convention attributes for db.statement.*
/// </summary>
public static class DbStatementAttributes
{
    /// <summary>db.statement</summary>
    public const string Statement = "db.statement";

}

/// <summary>
/// Semantic convention attributes for db.user.*
/// </summary>
public static class DbUserAttributes
{
    /// <summary>db.user</summary>
    public const string User = "db.user";

}
