// <auto-generated/>
// Generated from @opentelemetry/semantic-conventions v1.39.0
// Domain: dotnet
// Do not edit manually - run 'npm run generate:package' in SemconvGenerator

namespace OTelConventions;

/// <summary>
/// Semantic convention attributes for dotnet.gc.*
/// </summary>
public static class DotnetGcAttributes
{
    /// <summary>dotnet.gc.heap.generation</summary>
    public const string HeapGeneration = "dotnet.gc.heap.generation";

}
