// <auto-generated/>
// Generated from @opentelemetry/semantic-conventions v1.39.0
// Domain: feature_flag
// Do not edit manually - run 'npm run generate:package' in SemconvGenerator

namespace OTelConventions;

/// <summary>
/// Semantic convention attributes for feature_flag.context.*
/// </summary>
public static class FeatureFlagContextAttributes
{
    /// <summary>feature_flag.context.id</summary>
    public const string Id = "feature_flag.context.id";

}

/// <summary>
/// Semantic convention attributes for feature_flag.evaluation.*
/// </summary>
public static class FeatureFlagEvaluationAttributes
{
    /// <summary>feature_flag.evaluation.error.message</summary>
    public const string ErrorMessage = "feature_flag.evaluation.error.message";

    /// <summary>feature_flag.evaluation.reason</summary>
    public const string Reason = "feature_flag.evaluation.reason";

}

/// <summary>
/// Semantic convention attributes for feature_flag.key.*
/// </summary>
public static class FeatureFlagKeyAttributes
{
    /// <summary>feature_flag.key</summary>
    public const string Key = "feature_flag.key";

}

/// <summary>
/// Semantic convention attributes for feature_flag.provider.*
/// </summary>
public static class FeatureFlagProviderAttributes
{
    /// <summary>feature_flag.provider.name</summary>
    public const string Name = "feature_flag.provider.name";

}

/// <summary>
/// Semantic convention attributes for feature_flag.result.*
/// </summary>
public static class FeatureFlagResultAttributes
{
    /// <summary>feature_flag.result.reason</summary>
    public const string Reason = "feature_flag.result.reason";

    /// <summary>feature_flag.result.value</summary>
    public const string Value = "feature_flag.result.value";

    /// <summary>feature_flag.result.variant</summary>
    public const string Variant = "feature_flag.result.variant";

}

/// <summary>
/// Semantic convention attributes for feature_flag.set.*
/// </summary>
public static class FeatureFlagSetAttributes
{
    /// <summary>feature_flag.set.id</summary>
    public const string Id = "feature_flag.set.id";

}

/// <summary>
/// Semantic convention attributes for feature_flag.variant.*
/// </summary>
public static class FeatureFlagVariantAttributes
{
    /// <summary>feature_flag.variant</summary>
    public const string Variant = "feature_flag.variant";

}

/// <summary>
/// Semantic convention attributes for feature_flag.version.*
/// </summary>
public static class FeatureFlagVersionAttributes
{
    /// <summary>feature_flag.version</summary>
    public const string Version = "feature_flag.version";

}
