// <auto-generated/>
// Generated from @opentelemetry/semantic-conventions v1.39.0
// Domain: file
// Do not edit manually - run 'npm run generate:package' in SemconvGenerator

namespace OTelConventions;

/// <summary>
/// Semantic convention attributes for file.accessed.*
/// </summary>
public static class FileAccessedAttributes
{
    /// <summary>file.accessed</summary>
    public const string Accessed = "file.accessed";

}

/// <summary>
/// Semantic convention attributes for file.attributes.*
/// </summary>
public static class FileAttributesAttributes
{
    /// <summary>file.attributes</summary>
    public const string Attributes = "file.attributes";

}

/// <summary>
/// Semantic convention attributes for file.changed.*
/// </summary>
public static class FileChangedAttributes
{
    /// <summary>file.changed</summary>
    public const string Changed = "file.changed";

}

/// <summary>
/// Semantic convention attributes for file.created.*
/// </summary>
public static class FileCreatedAttributes
{
    /// <summary>file.created</summary>
    public const string Created = "file.created";

}

/// <summary>
/// Semantic convention attributes for file.directory.*
/// </summary>
public static class FileDirectoryAttributes
{
    /// <summary>file.directory</summary>
    public const string Directory = "file.directory";

}

/// <summary>
/// Semantic convention attributes for file.extension.*
/// </summary>
public static class FileExtensionAttributes
{
    /// <summary>file.extension</summary>
    public const string Extension = "file.extension";

}

/// <summary>
/// Semantic convention attributes for file.fork_name.*
/// </summary>
public static class FileForkNameAttributes
{
    /// <summary>file.fork_name</summary>
    public const string Fork_name = "file.fork_name";

}

/// <summary>
/// Semantic convention attributes for file.group.*
/// </summary>
public static class FileGroupAttributes
{
    /// <summary>file.group.id</summary>
    public const string Id = "file.group.id";

    /// <summary>file.group.name</summary>
    public const string Name = "file.group.name";

}

/// <summary>
/// Semantic convention attributes for file.inode.*
/// </summary>
public static class FileInodeAttributes
{
    /// <summary>file.inode</summary>
    public const string Inode = "file.inode";

}

/// <summary>
/// Semantic convention attributes for file.mode.*
/// </summary>
public static class FileModeAttributes
{
    /// <summary>file.mode</summary>
    public const string Mode = "file.mode";

}

/// <summary>
/// Semantic convention attributes for file.modified.*
/// </summary>
public static class FileModifiedAttributes
{
    /// <summary>file.modified</summary>
    public const string Modified = "file.modified";

}

/// <summary>
/// Semantic convention attributes for file.name.*
/// </summary>
public static class FileNameAttributes
{
    /// <summary>file.name</summary>
    public const string Name = "file.name";

}

/// <summary>
/// Semantic convention attributes for file.owner.*
/// </summary>
public static class FileOwnerAttributes
{
    /// <summary>file.owner.id</summary>
    public const string Id = "file.owner.id";

    /// <summary>file.owner.name</summary>
    public const string Name = "file.owner.name";

}

/// <summary>
/// Semantic convention attributes for file.path.*
/// </summary>
public static class FilePathAttributes
{
    /// <summary>file.path</summary>
    public const string Path = "file.path";

}

/// <summary>
/// Semantic convention attributes for file.size.*
/// </summary>
public static class FileSizeAttributes
{
    /// <summary>file.size</summary>
    public const string Size = "file.size";

}

/// <summary>
/// Semantic convention attributes for file.symbolic_link.*
/// </summary>
public static class FileSymbolicLinkAttributes
{
    /// <summary>file.symbolic_link.target_path</summary>
    public const string TargetPath = "file.symbolic_link.target_path";

}
