// <auto-generated/>
// Generated from @opentelemetry/semantic-conventions v1.39.0
// Domain: gen_ai
// Do not edit manually - run 'npm run generate:package' in SemconvGenerator

namespace OTelConventions;

/// <summary>
/// Semantic convention attributes for gen_ai.agent.*
/// </summary>
public static class GenAiAgentAttributes
{
    /// <summary>gen_ai.agent.description</summary>
    public const string Description = "gen_ai.agent.description";

    /// <summary>gen_ai.agent.id</summary>
    public const string Id = "gen_ai.agent.id";

    /// <summary>gen_ai.agent.name</summary>
    public const string Name = "gen_ai.agent.name";

}

/// <summary>
/// Semantic convention attributes for gen_ai.completion.*
/// </summary>
public static class GenAiCompletionAttributes
{
    /// <summary>gen_ai.completion</summary>
    public const string Completion = "gen_ai.completion";

}

/// <summary>
/// Semantic convention attributes for gen_ai.conversation.*
/// </summary>
public static class GenAiConversationAttributes
{
    /// <summary>gen_ai.conversation.id</summary>
    public const string Id = "gen_ai.conversation.id";

}

/// <summary>
/// Semantic convention attributes for gen_ai.data_source.*
/// </summary>
public static class GenAiDataSourceAttributes
{
    /// <summary>gen_ai.data_source.id</summary>
    public const string Id = "gen_ai.data_source.id";

}

/// <summary>
/// Semantic convention attributes for gen_ai.embeddings.*
/// </summary>
public static class GenAiEmbeddingsAttributes
{
    /// <summary>gen_ai.embeddings.dimension.count</summary>
    public const string DimensionCount = "gen_ai.embeddings.dimension.count";

}

/// <summary>
/// Semantic convention attributes for gen_ai.evaluation.*
/// </summary>
public static class GenAiEvaluationAttributes
{
    /// <summary>gen_ai.evaluation.explanation</summary>
    public const string Explanation = "gen_ai.evaluation.explanation";

    /// <summary>gen_ai.evaluation.name</summary>
    public const string Name = "gen_ai.evaluation.name";

    /// <summary>gen_ai.evaluation.score.label</summary>
    public const string ScoreLabel = "gen_ai.evaluation.score.label";

    /// <summary>gen_ai.evaluation.score.value</summary>
    public const string ScoreValue = "gen_ai.evaluation.score.value";

}

/// <summary>
/// Semantic convention attributes for gen_ai.input.*
/// </summary>
public static class GenAiInputAttributes
{
    /// <summary>gen_ai.input.messages</summary>
    public const string Messages = "gen_ai.input.messages";

}

/// <summary>
/// Semantic convention attributes for gen_ai.openai.*
/// </summary>
public static class GenAiOpenaiAttributes
{
    /// <summary>gen_ai.openai.request.response_format</summary>
    public const string RequestResponseFormat = "gen_ai.openai.request.response_format";

    /// <summary>gen_ai.openai.request.seed</summary>
    public const string RequestSeed = "gen_ai.openai.request.seed";

    /// <summary>gen_ai.openai.request.service_tier</summary>
    public const string RequestServiceTier = "gen_ai.openai.request.service_tier";

    /// <summary>gen_ai.openai.response.service_tier</summary>
    public const string ResponseServiceTier = "gen_ai.openai.response.service_tier";

    /// <summary>gen_ai.openai.response.system_fingerprint</summary>
    public const string ResponseSystemFingerprint = "gen_ai.openai.response.system_fingerprint";

}

/// <summary>
/// Semantic convention attributes for gen_ai.operation.*
/// </summary>
public static class GenAiOperationAttributes
{
    /// <summary>gen_ai.operation.name</summary>
    public const string Name = "gen_ai.operation.name";

}

/// <summary>
/// Semantic convention attributes for gen_ai.output.*
/// </summary>
public static class GenAiOutputAttributes
{
    /// <summary>gen_ai.output.messages</summary>
    public const string Messages = "gen_ai.output.messages";

    /// <summary>gen_ai.output.type</summary>
    public const string Type = "gen_ai.output.type";

}

/// <summary>
/// Semantic convention attributes for gen_ai.prompt.*
/// </summary>
public static class GenAiPromptAttributes
{
    /// <summary>gen_ai.prompt</summary>
    public const string Prompt = "gen_ai.prompt";

    /// <summary>gen_ai.prompt.name</summary>
    public const string Name = "gen_ai.prompt.name";

}

/// <summary>
/// Semantic convention attributes for gen_ai.provider.*
/// </summary>
public static class GenAiProviderAttributes
{
    /// <summary>gen_ai.provider.name</summary>
    public const string Name = "gen_ai.provider.name";

}

/// <summary>
/// Semantic convention attributes for gen_ai.request.*
/// </summary>
public static class GenAiRequestAttributes
{
    /// <summary>gen_ai.request.choice.count</summary>
    public const string ChoiceCount = "gen_ai.request.choice.count";

    /// <summary>gen_ai.request.encoding_formats</summary>
    public const string EncodingFormats = "gen_ai.request.encoding_formats";

    /// <summary>gen_ai.request.frequency_penalty</summary>
    public const string FrequencyPenalty = "gen_ai.request.frequency_penalty";

    /// <summary>gen_ai.request.max_tokens</summary>
    public const string MaxTokens = "gen_ai.request.max_tokens";

    /// <summary>gen_ai.request.model</summary>
    public const string Model = "gen_ai.request.model";

    /// <summary>gen_ai.request.presence_penalty</summary>
    public const string PresencePenalty = "gen_ai.request.presence_penalty";

    /// <summary>gen_ai.request.seed</summary>
    public const string Seed = "gen_ai.request.seed";

    /// <summary>gen_ai.request.stop_sequences</summary>
    public const string StopSequences = "gen_ai.request.stop_sequences";

    /// <summary>gen_ai.request.temperature</summary>
    public const string Temperature = "gen_ai.request.temperature";

    /// <summary>gen_ai.request.top_k</summary>
    public const string TopK = "gen_ai.request.top_k";

    /// <summary>gen_ai.request.top_p</summary>
    public const string TopP = "gen_ai.request.top_p";

}

/// <summary>
/// Semantic convention attributes for gen_ai.response.*
/// </summary>
public static class GenAiResponseAttributes
{
    /// <summary>gen_ai.response.finish_reasons</summary>
    public const string FinishReasons = "gen_ai.response.finish_reasons";

    /// <summary>gen_ai.response.id</summary>
    public const string Id = "gen_ai.response.id";

    /// <summary>gen_ai.response.model</summary>
    public const string Model = "gen_ai.response.model";

}

/// <summary>
/// Semantic convention attributes for gen_ai.system.*
/// </summary>
public static class GenAiSystemAttributes
{
    /// <summary>gen_ai.system</summary>
    public const string System = "gen_ai.system";

}

/// <summary>
/// Semantic convention attributes for gen_ai.system_instructions.*
/// </summary>
public static class GenAiSystemInstructionsAttributes
{
    /// <summary>gen_ai.system_instructions</summary>
    public const string System_instructions = "gen_ai.system_instructions";

}

/// <summary>
/// Semantic convention attributes for gen_ai.token.*
/// </summary>
public static class GenAiTokenAttributes
{
    /// <summary>gen_ai.token.type</summary>
    public const string Type = "gen_ai.token.type";

}

/// <summary>
/// Semantic convention attributes for gen_ai.tool.*
/// </summary>
public static class GenAiToolAttributes
{
    /// <summary>gen_ai.tool.call.arguments</summary>
    public const string CallArguments = "gen_ai.tool.call.arguments";

    /// <summary>gen_ai.tool.call.id</summary>
    public const string CallId = "gen_ai.tool.call.id";

    /// <summary>gen_ai.tool.call.result</summary>
    public const string CallResult = "gen_ai.tool.call.result";

    /// <summary>gen_ai.tool.definitions</summary>
    public const string Definitions = "gen_ai.tool.definitions";

    /// <summary>gen_ai.tool.description</summary>
    public const string Description = "gen_ai.tool.description";

    /// <summary>gen_ai.tool.name</summary>
    public const string Name = "gen_ai.tool.name";

    /// <summary>gen_ai.tool.type</summary>
    public const string Type = "gen_ai.tool.type";

}

/// <summary>
/// Semantic convention attributes for gen_ai.usage.*
/// </summary>
public static class GenAiUsageAttributes
{
    /// <summary>gen_ai.usage.completion_tokens</summary>
    public const string CompletionTokens = "gen_ai.usage.completion_tokens";

    /// <summary>gen_ai.usage.input_tokens</summary>
    public const string InputTokens = "gen_ai.usage.input_tokens";

    /// <summary>gen_ai.usage.output_tokens</summary>
    public const string OutputTokens = "gen_ai.usage.output_tokens";

    /// <summary>gen_ai.usage.prompt_tokens</summary>
    public const string PromptTokens = "gen_ai.usage.prompt_tokens";

}
