// <auto-generated/>
// Generated from @opentelemetry/semantic-conventions v1.39.0
// Domain: geo
// Do not edit manually - run 'npm run generate:package' in SemconvGenerator

namespace OTelConventions;

/// <summary>
/// Semantic convention attributes for geo.continent.*
/// </summary>
public static class GeoContinentAttributes
{
    /// <summary>geo.continent.code</summary>
    public const string Code = "geo.continent.code";

}

/// <summary>
/// Semantic convention attributes for geo.country.*
/// </summary>
public static class GeoCountryAttributes
{
    /// <summary>geo.country.iso_code</summary>
    public const string IsoCode = "geo.country.iso_code";

}

/// <summary>
/// Semantic convention attributes for geo.locality.*
/// </summary>
public static class GeoLocalityAttributes
{
    /// <summary>geo.locality.name</summary>
    public const string Name = "geo.locality.name";

}

/// <summary>
/// Semantic convention attributes for geo.location.*
/// </summary>
public static class GeoLocationAttributes
{
    /// <summary>geo.location.lat</summary>
    public const string Lat = "geo.location.lat";

    /// <summary>geo.location.lon</summary>
    public const string Lon = "geo.location.lon";

}

/// <summary>
/// Semantic convention attributes for geo.postal_code.*
/// </summary>
public static class GeoPostalCodeAttributes
{
    /// <summary>geo.postal_code</summary>
    public const string Postal_code = "geo.postal_code";

}

/// <summary>
/// Semantic convention attributes for geo.region.*
/// </summary>
public static class GeoRegionAttributes
{
    /// <summary>geo.region.iso_code</summary>
    public const string IsoCode = "geo.region.iso_code";

}
