// <auto-generated/>
// Generated from @opentelemetry/semantic-conventions v1.39.0
// Domain: host
// Do not edit manually - run 'npm run generate:package' in SemconvGenerator

namespace OTelConventions;

/// <summary>
/// Semantic convention attributes for host.arch.*
/// </summary>
public static class HostArchAttributes
{
    /// <summary>host.arch</summary>
    public const string Arch = "host.arch";

}

/// <summary>
/// Semantic convention attributes for host.cpu.*
/// </summary>
public static class HostCpuAttributes
{
    /// <summary>host.cpu.cache.l2.size</summary>
    public const string CacheL2Size = "host.cpu.cache.l2.size";

    /// <summary>host.cpu.family</summary>
    public const string Family = "host.cpu.family";

    /// <summary>host.cpu.model.id</summary>
    public const string ModelId = "host.cpu.model.id";

    /// <summary>host.cpu.model.name</summary>
    public const string ModelName = "host.cpu.model.name";

    /// <summary>host.cpu.stepping</summary>
    public const string Stepping = "host.cpu.stepping";

    /// <summary>host.cpu.vendor.id</summary>
    public const string VendorId = "host.cpu.vendor.id";

}

/// <summary>
/// Semantic convention attributes for host.id.*
/// </summary>
public static class HostIdAttributes
{
    /// <summary>host.id</summary>
    public const string Id = "host.id";

}

/// <summary>
/// Semantic convention attributes for host.image.*
/// </summary>
public static class HostImageAttributes
{
    /// <summary>host.image.id</summary>
    public const string Id = "host.image.id";

    /// <summary>host.image.name</summary>
    public const string Name = "host.image.name";

    /// <summary>host.image.version</summary>
    public const string Version = "host.image.version";

}

/// <summary>
/// Semantic convention attributes for host.ip.*
/// </summary>
public static class HostIpAttributes
{
    /// <summary>host.ip</summary>
    public const string Ip = "host.ip";

}

/// <summary>
/// Semantic convention attributes for host.mac.*
/// </summary>
public static class HostMacAttributes
{
    /// <summary>host.mac</summary>
    public const string Mac = "host.mac";

}

/// <summary>
/// Semantic convention attributes for host.name.*
/// </summary>
public static class HostNameAttributes
{
    /// <summary>host.name</summary>
    public const string Name = "host.name";

}

/// <summary>
/// Semantic convention attributes for host.type.*
/// </summary>
public static class HostTypeAttributes
{
    /// <summary>host.type</summary>
    public const string Type = "host.type";

}
