// <auto-generated/>
// Generated from @opentelemetry/semantic-conventions v1.39.0
// Domain: process
// Do not edit manually - run 'npm run generate:package' in SemconvGenerator

namespace OTelConventions;

/// <summary>
/// Semantic convention attributes for process.args_count.*
/// </summary>
public static class ProcessArgsCountAttributes
{
    /// <summary>process.args_count</summary>
    public const string Args_count = "process.args_count";

}

/// <summary>
/// Semantic convention attributes for process.command.*
/// </summary>
public static class ProcessCommandAttributes
{
    /// <summary>process.command</summary>
    public const string Command = "process.command";

}

/// <summary>
/// Semantic convention attributes for process.command_args.*
/// </summary>
public static class ProcessCommandArgsAttributes
{
    /// <summary>process.command_args</summary>
    public const string Command_args = "process.command_args";

}

/// <summary>
/// Semantic convention attributes for process.command_line.*
/// </summary>
public static class ProcessCommandLineAttributes
{
    /// <summary>process.command_line</summary>
    public const string Command_line = "process.command_line";

}

/// <summary>
/// Semantic convention attributes for process.context_switch.*
/// </summary>
public static class ProcessContextSwitchAttributes
{
    /// <summary>process.context_switch.type</summary>
    public const string Type = "process.context_switch.type";

}

/// <summary>
/// Semantic convention attributes for process.cpu.*
/// </summary>
public static class ProcessCpuAttributes
{
    /// <summary>process.cpu.state</summary>
    public const string State = "process.cpu.state";

}

/// <summary>
/// Semantic convention attributes for process.creation.*
/// </summary>
public static class ProcessCreationAttributes
{
    /// <summary>process.creation.time</summary>
    public const string Time = "process.creation.time";

}

/// <summary>
/// Semantic convention attributes for process.executable.*
/// </summary>
public static class ProcessExecutableAttributes
{
    /// <summary>process.executable.build_id.gnu</summary>
    public const string BuildIdGnu = "process.executable.build_id.gnu";

    /// <summary>process.executable.build_id.go</summary>
    public const string BuildIdGo = "process.executable.build_id.go";

    /// <summary>process.executable.build_id.htlhash</summary>
    public const string BuildIdHtlhash = "process.executable.build_id.htlhash";

    /// <summary>process.executable.build_id.profiling</summary>
    public const string BuildIdProfiling = "process.executable.build_id.profiling";

    /// <summary>process.executable.name</summary>
    public const string Name = "process.executable.name";

    /// <summary>process.executable.path</summary>
    public const string Path = "process.executable.path";

}

/// <summary>
/// Semantic convention attributes for process.exit.*
/// </summary>
public static class ProcessExitAttributes
{
    /// <summary>process.exit.code</summary>
    public const string Code = "process.exit.code";

    /// <summary>process.exit.time</summary>
    public const string Time = "process.exit.time";

}

/// <summary>
/// Semantic convention attributes for process.group_leader.*
/// </summary>
public static class ProcessGroupLeaderAttributes
{
    /// <summary>process.group_leader.pid</summary>
    public const string Pid = "process.group_leader.pid";

}

/// <summary>
/// Semantic convention attributes for process.interactive.*
/// </summary>
public static class ProcessInteractiveAttributes
{
    /// <summary>process.interactive</summary>
    public const string Interactive = "process.interactive";

}

/// <summary>
/// Semantic convention attributes for process.linux.*
/// </summary>
public static class ProcessLinuxAttributes
{
    /// <summary>process.linux.cgroup</summary>
    public const string Cgroup = "process.linux.cgroup";

}

/// <summary>
/// Semantic convention attributes for process.owner.*
/// </summary>
public static class ProcessOwnerAttributes
{
    /// <summary>process.owner</summary>
    public const string Owner = "process.owner";

}

/// <summary>
/// Semantic convention attributes for process.paging.*
/// </summary>
public static class ProcessPagingAttributes
{
    /// <summary>process.paging.fault_type</summary>
    public const string FaultType = "process.paging.fault_type";

}

/// <summary>
/// Semantic convention attributes for process.parent_pid.*
/// </summary>
public static class ProcessParentPidAttributes
{
    /// <summary>process.parent_pid</summary>
    public const string Parent_pid = "process.parent_pid";

}

/// <summary>
/// Semantic convention attributes for process.pid.*
/// </summary>
public static class ProcessPidAttributes
{
    /// <summary>process.pid</summary>
    public const string Pid = "process.pid";

}

/// <summary>
/// Semantic convention attributes for process.real_user.*
/// </summary>
public static class ProcessRealUserAttributes
{
    /// <summary>process.real_user.id</summary>
    public const string Id = "process.real_user.id";

    /// <summary>process.real_user.name</summary>
    public const string Name = "process.real_user.name";

}

/// <summary>
/// Semantic convention attributes for process.runtime.*
/// </summary>
public static class ProcessRuntimeAttributes
{
    /// <summary>process.runtime.description</summary>
    public const string Description = "process.runtime.description";

    /// <summary>process.runtime.name</summary>
    public const string Name = "process.runtime.name";

    /// <summary>process.runtime.version</summary>
    public const string Version = "process.runtime.version";

}

/// <summary>
/// Semantic convention attributes for process.saved_user.*
/// </summary>
public static class ProcessSavedUserAttributes
{
    /// <summary>process.saved_user.id</summary>
    public const string Id = "process.saved_user.id";

    /// <summary>process.saved_user.name</summary>
    public const string Name = "process.saved_user.name";

}

/// <summary>
/// Semantic convention attributes for process.session_leader.*
/// </summary>
public static class ProcessSessionLeaderAttributes
{
    /// <summary>process.session_leader.pid</summary>
    public const string Pid = "process.session_leader.pid";

}

/// <summary>
/// Semantic convention attributes for process.state.*
/// </summary>
public static class ProcessStateAttributes
{
    /// <summary>process.state</summary>
    public const string State = "process.state";

}

/// <summary>
/// Semantic convention attributes for process.title.*
/// </summary>
public static class ProcessTitleAttributes
{
    /// <summary>process.title</summary>
    public const string Title = "process.title";

}

/// <summary>
/// Semantic convention attributes for process.user.*
/// </summary>
public static class ProcessUserAttributes
{
    /// <summary>process.user.id</summary>
    public const string Id = "process.user.id";

    /// <summary>process.user.name</summary>
    public const string Name = "process.user.name";

}

/// <summary>
/// Semantic convention attributes for process.vpid.*
/// </summary>
public static class ProcessVpidAttributes
{
    /// <summary>process.vpid</summary>
    public const string Vpid = "process.vpid";

}

/// <summary>
/// Semantic convention attributes for process.working_directory.*
/// </summary>
public static class ProcessWorkingDirectoryAttributes
{
    /// <summary>process.working_directory</summary>
    public const string Working_directory = "process.working_directory";

}
