// <auto-generated/>
// Generated from @opentelemetry/semantic-conventions v1.39.0
// Domain: signalr
// Do not edit manually - run 'npm run generate:package' in SemconvGenerator

namespace OTelConventions;

/// <summary>
/// Semantic convention attributes for signalr.connection.*
/// </summary>
public static class SignalrConnectionAttributes
{
    /// <summary>signalr.connection.status</summary>
    public const string Status = "signalr.connection.status";

}

/// <summary>
/// Semantic convention attributes for signalr.transport.*
/// </summary>
public static class SignalrTransportAttributes
{
    /// <summary>signalr.transport</summary>
    public const string Transport = "signalr.transport";

}
