// <auto-generated/>
// Generated from @opentelemetry/semantic-conventions v1.39.0
// Domain: url
// Do not edit manually - run 'npm run generate:package' in SemconvGenerator

namespace OTelConventions;

/// <summary>
/// Semantic convention attributes for url.fragment.*
/// </summary>
public static class UrlFragmentAttributes
{
    /// <summary>url.fragment</summary>
    public const string Fragment = "url.fragment";

}

/// <summary>
/// Semantic convention attributes for url.full.*
/// </summary>
public static class UrlFullAttributes
{
    /// <summary>url.full</summary>
    public const string Full = "url.full";

}

/// <summary>
/// Semantic convention attributes for url.path.*
/// </summary>
public static class UrlPathAttributes
{
    /// <summary>url.path</summary>
    public const string Path = "url.path";

}

/// <summary>
/// Semantic convention attributes for url.query.*
/// </summary>
public static class UrlQueryAttributes
{
    /// <summary>url.query</summary>
    public const string Query = "url.query";

}

/// <summary>
/// Semantic convention attributes for url.scheme.*
/// </summary>
public static class UrlSchemeAttributes
{
    /// <summary>url.scheme</summary>
    public const string Scheme = "url.scheme";

}

/// <summary>
/// Semantic convention attributes for url.domain.*
/// </summary>
public static class UrlDomainAttributes
{
    /// <summary>url.domain</summary>
    public const string Domain = "url.domain";

}

/// <summary>
/// Semantic convention attributes for url.extension.*
/// </summary>
public static class UrlExtensionAttributes
{
    /// <summary>url.extension</summary>
    public const string Extension = "url.extension";

}

/// <summary>
/// Semantic convention attributes for url.original.*
/// </summary>
public static class UrlOriginalAttributes
{
    /// <summary>url.original</summary>
    public const string Original = "url.original";

}

/// <summary>
/// Semantic convention attributes for url.port.*
/// </summary>
public static class UrlPortAttributes
{
    /// <summary>url.port</summary>
    public const string Port = "url.port";

}

/// <summary>
/// Semantic convention attributes for url.registered_domain.*
/// </summary>
public static class UrlRegisteredDomainAttributes
{
    /// <summary>url.registered_domain</summary>
    public const string Registered_domain = "url.registered_domain";

}

/// <summary>
/// Semantic convention attributes for url.subdomain.*
/// </summary>
public static class UrlSubdomainAttributes
{
    /// <summary>url.subdomain</summary>
    public const string Subdomain = "url.subdomain";

}

/// <summary>
/// Semantic convention attributes for url.template.*
/// </summary>
public static class UrlTemplateAttributes
{
    /// <summary>url.template</summary>
    public const string Template = "url.template";

}

/// <summary>
/// Semantic convention attributes for url.top_level_domain.*
/// </summary>
public static class UrlTopLevelDomainAttributes
{
    /// <summary>url.top_level_domain</summary>
    public const string Top_level_domain = "url.top_level_domain";

}
