// <auto-generated/>
// Generated from @opentelemetry/semantic-conventions v1.39.0
// Domain: webengine
// Do not edit manually - run 'npm run generate:package' in SemconvGenerator

namespace OTelConventions;

/// <summary>
/// Semantic convention attributes for webengine.description.*
/// </summary>
public static class WebengineDescriptionAttributes
{
    /// <summary>webengine.description</summary>
    public const string Description = "webengine.description";

}

/// <summary>
/// Semantic convention attributes for webengine.name.*
/// </summary>
public static class WebengineNameAttributes
{
    /// <summary>webengine.name</summary>
    public const string Name = "webengine.name";

}

/// <summary>
/// Semantic convention attributes for webengine.version.*
/// </summary>
public static class WebengineVersionAttributes
{
    /// <summary>webengine.version</summary>
    public const string Version = "webengine.version";

}
