// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Net;

/// <summary>Net Attributes (incubating).</summary>
public static class NetAttributes
{
    /// <summary>Deprecated, use `network.local.address`..</summary>
    [global::System.Obsolete("Replaced by network.local.address.", false)]
    public const string HostIp = "net.host.ip";

    /// <summary>Deprecated, use `server.address`..</summary>
    [global::System.Obsolete("Replaced by server.address.", false)]
    public const string HostName = "net.host.name";

    /// <summary>Deprecated, use `server.port`..</summary>
    [global::System.Obsolete("Replaced by server.port.", false)]
    public const string HostPort = "net.host.port";

    /// <summary>Deprecated, use `network.peer.address`..</summary>
    [global::System.Obsolete("Replaced by network.peer.address.", false)]
    public const string PeerIp = "net.peer.ip";

    /// <summary>Deprecated, use `server.address` on client spans and `client.address` on server spans..</summary>
    [global::System.Obsolete("Replaced by `server.address` on client spans and `client.address` on server spans.", false)]
    public const string PeerName = "net.peer.name";

    /// <summary>Deprecated, use `server.port` on client spans and `client.port` on server spans..</summary>
    [global::System.Obsolete("Replaced by `server.port` on client spans and `client.port` on server spans.", false)]
    public const string PeerPort = "net.peer.port";

    /// <summary>Deprecated, use `network.protocol.name`..</summary>
    [global::System.Obsolete("Replaced by network.protocol.name.", false)]
    public const string ProtocolName = "net.protocol.name";

    /// <summary>Deprecated, use `network.protocol.version`..</summary>
    [global::System.Obsolete("Replaced by network.protocol.version.", false)]
    public const string ProtocolVersion = "net.protocol.version";

    /// <summary>Deprecated, use `network.transport` and `network.type`..</summary>
    [global::System.Obsolete("Split to `network.transport` and `network.type`.", false)]
    public const string SockFamily = "net.sock.family";

    /// <summary>Values for the <c>SockFamily</c> attribute.</summary>
    public static class SockFamilyValues
    {
        /// <summary>IPv4 address.</summary>
        public const string Inet = "inet";
        /// <summary>IPv6 address.</summary>
        public const string Inet6 = "inet6";
        /// <summary>Unix domain socket path.</summary>
        public const string Unix = "unix";
    }

    /// <summary>Deprecated, use `network.local.address`..</summary>
    [global::System.Obsolete("Replaced by network.local.address.", false)]
    public const string SockHostAddr = "net.sock.host.addr";

    /// <summary>Deprecated, use `network.local.port`..</summary>
    [global::System.Obsolete("Replaced by network.local.port.", false)]
    public const string SockHostPort = "net.sock.host.port";

    /// <summary>Deprecated, use `network.peer.address`..</summary>
    [global::System.Obsolete("Replaced by network.peer.address.", false)]
    public const string SockPeerAddr = "net.sock.peer.addr";

    /// <summary>Deprecated, no replacement at this time..</summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string SockPeerName = "net.sock.peer.name";

    /// <summary>Deprecated, use `network.peer.port`..</summary>
    [global::System.Obsolete("Replaced by network.peer.port.", false)]
    public const string SockPeerPort = "net.sock.peer.port";

    /// <summary>Deprecated, use `network.transport`..</summary>
    [global::System.Obsolete("Replaced by network.transport.", false)]
    public const string Transport = "net.transport";

    /// <summary>Values for the <c>Transport</c> attribute.</summary>
    public static class TransportValues
    {
        /// <summary>In-process communication..</summary>
        public const string Inproc = "inproc";
        /// <summary>.</summary>
        public const string IpTcp = "ip_tcp";
        /// <summary>.</summary>
        public const string IpUdp = "ip_udp";
        /// <summary>Something else (non IP-based)..</summary>
        public const string Other = "other";
        /// <summary>Named or anonymous pipe..</summary>
        public const string Pipe = "pipe";
    }

}