// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@7fe537301d17919af7d7eb65b32e9be35da2c497
// Schema: https://opentelemetry.io/schemas/1.40.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Attributes.Db;

/// <summary>Db Attributes.</summary>
public static class DbAttributes
{
    /// <summary>The name of a collection (table, container) within the database..</summary>
    /// <remarks>It is RECOMMENDED to capture the value as provided by the application without attempting to do any case normalization.  The collection name SHOULD NOT be extracted from `db.query.text`, when the database system supports query text with multiple collections in non-batch operations.  For batch operations, if the individual operations are known to have the same collection name then that collection name SHOULD be used.</remarks>
    public const string CollectionName = "db.collection.name";

    /// <summary>The name of the database, fully qualified within the server address and port..</summary>
    /// <remarks>If a database system has multiple namespace components, they SHOULD be concatenated from the most general to the most specific namespace component, using `|` as a separator between the components. Any missing components (and their associated separators) SHOULD be omitted. Semantic conventions for individual database systems SHOULD document what `db.namespace` means in the context of that system. It is RECOMMENDED to capture the value as provided by the application without attempting to do any case normalization.</remarks>
    public const string Namespace = "db.namespace";

    /// <summary>The number of queries included in a batch operation..</summary>
    /// <remarks>Operations are only considered batches when they contain two or more operations, and so `db.operation.batch.size` SHOULD never be `1`.</remarks>
    public const string OperationBatchSize = "db.operation.batch.size";

    /// <summary>The name of the operation or command being executed..</summary>
    /// <remarks>It is RECOMMENDED to capture the value as provided by the application without attempting to do any case normalization.  The operation name SHOULD NOT be extracted from `db.query.text`, when the database system supports query text with multiple operations in non-batch operations.  If spaces can occur in the operation name, multiple consecutive spaces SHOULD be normalized to a single space.  For batch operations, if the individual operations are known to have the same operation name then that operation name SHOULD be used prepended by `BATCH `, otherwise `db.operation.name` SHOULD be `BATCH` or some other database system specific term if more applicable.</remarks>
    public const string OperationName = "db.operation.name";

    /// <summary>Low cardinality summary of a database query..</summary>
    /// <remarks>The query summary describes a class of database queries and is useful as a grouping key, especially when analyzing telemetry for database calls involving complex queries.  Summary may be available to the instrumentation through instrumentation hooks or other means. If it is not available, instrumentations that support query parsing SHOULD generate a summary following [Generating query summary](/docs/db/database-spans.md#generating-a-summary-of-the-query) section.  For batch operations, if the individual operations are known to have the same query summary then that query summary SHOULD be used prepended by `BATCH `, otherwise `db.query.summary` SHOULD be `BATCH` or some other database system specific term if more applicable.</remarks>
    public const string QuerySummary = "db.query.summary";

    /// <summary>The database query being executed..</summary>
    /// <remarks>For sanitization see [Sanitization of `db.query.text`](/docs/db/database-spans.md#sanitization-of-dbquerytext). For batch operations, if the individual operations are known to have the same query text then that query text SHOULD be used, otherwise all of the individual query texts SHOULD be concatenated with separator `; ` or some other database system specific separator if more applicable. Parameterized query text SHOULD NOT be sanitized. Even though parameterized query text can potentially have sensitive data, by using a parameterized query the user is giving a strong signal that any sensitive data will be passed as parameter values, and the benefit to observability of capturing the static part of the query text by default outweighs the risk.</remarks>
    public const string QueryText = "db.query.text";

    /// <summary>Database response status code..</summary>
    /// <remarks>The status code returned by the database. Usually it represents an error code, but may also represent partial success, warning, or differentiate between various types of successful outcomes. Semantic conventions for individual database systems SHOULD document what `db.response.status_code` means in the context of that system.</remarks>
    public const string ResponseStatusCode = "db.response.status_code";

    /// <summary>The name of a stored procedure within the database..</summary>
    /// <remarks>It is RECOMMENDED to capture the value as provided by the application without attempting to do any case normalization.  For batch operations, if the individual operations are known to have the same stored procedure name then that stored procedure name SHOULD be used.</remarks>
    public const string StoredProcedureName = "db.stored_procedure.name";

    /// <summary>The database management system (DBMS) product as identified by the client instrumentation..</summary>
    /// <remarks>The actual DBMS may differ from the one identified by the client. For example, when using PostgreSQL client libraries to connect to a CockroachDB, the `db.system.name` is set to `postgresql` based on the instrumentation's best knowledge.</remarks>
    public const string SystemName = "db.system.name";

    /// <summary>Values for the <c>SystemName</c> attribute.</summary>
    public static class SystemNameValues
    {
        /// <summary>[Actian Ingres](https://www.actian.com/databases/ingres/).</summary>
        public const string ActianIngres = "actian.ingres";
        /// <summary>[Amazon DynamoDB](https://aws.amazon.com/pm/dynamodb/).</summary>
        public const string AwsDynamodb = "aws.dynamodb";
        /// <summary>[Amazon Redshift](https://aws.amazon.com/redshift/).</summary>
        public const string AwsRedshift = "aws.redshift";
        /// <summary>[Azure Cosmos DB](https://learn.microsoft.com/azure/cosmos-db).</summary>
        public const string AzureCosmosdb = "azure.cosmosdb";
        /// <summary>[Apache Cassandra](https://cassandra.apache.org/).</summary>
        public const string Cassandra = "cassandra";
        /// <summary>[ClickHouse](https://clickhouse.com/).</summary>
        public const string Clickhouse = "clickhouse";
        /// <summary>[CockroachDB](https://www.cockroachlabs.com/).</summary>
        public const string Cockroachdb = "cockroachdb";
        /// <summary>[Couchbase](https://www.couchbase.com/).</summary>
        public const string Couchbase = "couchbase";
        /// <summary>[Apache CouchDB](https://couchdb.apache.org/).</summary>
        public const string Couchdb = "couchdb";
        /// <summary>[Apache Derby](https://db.apache.org/derby/).</summary>
        public const string Derby = "derby";
        /// <summary>[Elasticsearch](https://www.elastic.co/elasticsearch).</summary>
        public const string Elasticsearch = "elasticsearch";
        /// <summary>[Firebird](https://www.firebirdsql.org/).</summary>
        public const string Firebirdsql = "firebirdsql";
        /// <summary>[Google Cloud Spanner](https://cloud.google.com/spanner).</summary>
        public const string GcpSpanner = "gcp.spanner";
        /// <summary>[Apache Geode](https://geode.apache.org/).</summary>
        public const string Geode = "geode";
        /// <summary>[H2 Database](https://h2database.com/).</summary>
        public const string H2database = "h2database";
        /// <summary>[Apache HBase](https://hbase.apache.org/).</summary>
        public const string Hbase = "hbase";
        /// <summary>[Apache Hive](https://hive.apache.org/).</summary>
        public const string Hive = "hive";
        /// <summary>[HyperSQL Database](https://hsqldb.org/).</summary>
        public const string Hsqldb = "hsqldb";
        /// <summary>[IBM Db2](https://www.ibm.com/db2).</summary>
        public const string IbmDb2 = "ibm.db2";
        /// <summary>[IBM Informix](https://www.ibm.com/products/informix).</summary>
        public const string IbmInformix = "ibm.informix";
        /// <summary>[IBM Netezza](https://www.ibm.com/products/netezza).</summary>
        public const string IbmNetezza = "ibm.netezza";
        /// <summary>[InfluxDB](https://www.influxdata.com/).</summary>
        public const string Influxdb = "influxdb";
        /// <summary>[Instant](https://www.instantdb.com/).</summary>
        public const string Instantdb = "instantdb";
        /// <summary>[InterSystems Caché](https://www.intersystems.com/products/cache/).</summary>
        public const string IntersystemsCache = "intersystems.cache";
        /// <summary>[MariaDB](https://mariadb.org/).</summary>
        public const string Mariadb = "mariadb";
        /// <summary>[Memcached](https://memcached.org/).</summary>
        public const string Memcached = "memcached";
        /// <summary>[Microsoft SQL Server](https://www.microsoft.com/sql-server).</summary>
        public const string MicrosoftSqlServer = "microsoft.sql_server";
        /// <summary>[MongoDB](https://www.mongodb.com/).</summary>
        public const string Mongodb = "mongodb";
        /// <summary>[MySQL](https://www.mysql.com/).</summary>
        public const string Mysql = "mysql";
        /// <summary>[Neo4j](https://neo4j.com/).</summary>
        public const string Neo4j = "neo4j";
        /// <summary>[OpenSearch](https://opensearch.org/).</summary>
        public const string Opensearch = "opensearch";
        /// <summary>[Oracle Database](https://www.oracle.com/database/).</summary>
        public const string OracleDb = "oracle.db";
        /// <summary>Some other SQL database. Fallback only..</summary>
        public const string OtherSql = "other_sql";
        /// <summary>[PostgreSQL](https://www.postgresql.org/).</summary>
        public const string Postgresql = "postgresql";
        /// <summary>[Redis](https://redis.io/).</summary>
        public const string Redis = "redis";
        /// <summary>[SAP HANA](https://www.sap.com/products/technology-platform/hana/what-is-sap-hana.html).</summary>
        public const string SapHana = "sap.hana";
        /// <summary>[SAP MaxDB](https://maxdb.sap.com/).</summary>
        public const string SapMaxdb = "sap.maxdb";
        /// <summary>[Adabas (Adaptable Database System)](https://documentation.softwareag.com/?pf=adabas).</summary>
        public const string SoftwareagAdabas = "softwareag.adabas";
        /// <summary>[SQLite](https://www.sqlite.org/).</summary>
        public const string Sqlite = "sqlite";
        /// <summary>[Teradata](https://www.teradata.com/).</summary>
        public const string Teradata = "teradata";
        /// <summary>[Trino](https://trino.io/).</summary>
        public const string Trino = "trino";
    }

}