using qyl.collector.Auth;
using qyl.collector.BuildFailures;

namespace qyl.collector;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    NumberHandling = JsonNumberHandling.AllowReadingFromString,
    WriteIndented = false)]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(AuthCheckResponse))]
[JsonSerializable(typeof(StorageStats))]
[JsonSerializable(typeof(GenAiStats))]
[JsonSerializable(typeof(ConsoleLogEntry))]
[JsonSerializable(typeof(ConsoleLogEntry[]))]
[JsonSerializable(typeof(ConsoleIngestRequest))]
[JsonSerializable(typeof(ConsoleIngestBatch))]
[JsonSerializable(typeof(TelemetryEventDto))]
[JsonSerializable(typeof(TelemetryMessage))]
[JsonSerializable(typeof(SpanDto))]
[JsonSerializable(typeof(SpanDto[]))]
[JsonSerializable(typeof(List<SpanDto>))]
[JsonSerializable(typeof(GenAiSpanDataDto))]
[JsonSerializable(typeof(SpanEventDto))]
[JsonSerializable(typeof(SpanLinkDto))]
[JsonSerializable(typeof(SessionDto))]
[JsonSerializable(typeof(SessionDto[]))]
[JsonSerializable(typeof(List<SessionDto>))]
[JsonSerializable(typeof(SessionGenAiStatsDto))]
[JsonSerializable(typeof(SessionListResponseDto))]
[JsonSerializable(typeof(SpanListResponseDto))]
[JsonSerializable(typeof(TraceResponseDto))]
[JsonSerializable(typeof(SpanBatchDto))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(SpanBatch))]
[JsonSerializable(typeof(SpanStorageRow))]
[JsonSerializable(typeof(List<SpanStorageRow>))]
[JsonSerializable(typeof(Dictionary<string, string>), TypeInfoPropertyName = "DictionaryStringString")]
[JsonSerializable(typeof(OtlpExportTraceServiceRequest))]
[JsonSerializable(typeof(OtlpResourceSpans))]
[JsonSerializable(typeof(OtlpResource))]
[JsonSerializable(typeof(OtlpScopeSpans))]
[JsonSerializable(typeof(OtlpSpan))]
[JsonSerializable(typeof(OtlpStatus))]
[JsonSerializable(typeof(OtlpKeyValue))]
[JsonSerializable(typeof(OtlpAnyValue))]
[JsonSerializable(typeof(OtlpExportLogsServiceRequest))]
[JsonSerializable(typeof(OtlpResourceLogs))]
[JsonSerializable(typeof(OtlpScopeLogs))]
[JsonSerializable(typeof(OtlpLogRecord))]
[JsonSerializable(typeof(LogStorageRow))]
[JsonSerializable(typeof(List<LogStorageRow>))]
[JsonSerializable(typeof(string[]))]
// Ring buffer response types
[JsonSerializable(typeof(RecentSpansResponse))]
[JsonSerializable(typeof(TraceFromMemoryResponse))]
[JsonSerializable(typeof(SessionSpansFromMemoryResponse))]
[JsonSerializable(typeof(BufferStatsResponse))]
// Telemetry management types
[JsonSerializable(typeof(ClearTelemetryResponse))]
// Insights materializer types
[JsonSerializable(typeof(Insights.InsightsResponse))]
[JsonSerializable(typeof(Insights.InsightTierStatus))]
[JsonSerializable(typeof(IReadOnlyList<Insights.InsightTierStatus>))]
// Dashboard types
[JsonSerializable(typeof(Dashboards.DashboardDefinition))]
[JsonSerializable(typeof(Dashboards.DashboardData))]
[JsonSerializable(typeof(Dashboards.DashboardWidget))]
[JsonSerializable(typeof(Dashboards.StatCardData))]
[JsonSerializable(typeof(Dashboards.TimeSeriesPoint))]
[JsonSerializable(typeof(Dashboards.TopNRow))]
[JsonSerializable(typeof(IReadOnlyList<Dashboards.DashboardDefinition>))]
[JsonSerializable(typeof(IReadOnlyList<Dashboards.DashboardWidget>))]
[JsonSerializable(typeof(IReadOnlyList<Dashboards.TopNRow>))]
[JsonSerializable(typeof(IReadOnlyList<Dashboards.TimeSeriesPoint>))]
// Copilot types (for request body deserialization)
[JsonSerializable(typeof(qyl.protocol.Copilot.ChatRequest))]
[JsonSerializable(typeof(qyl.protocol.Copilot.WorkflowRunRequest))]
[JsonSerializable(typeof(qyl.protocol.Copilot.CopilotAuthStatus))]
[JsonSerializable(typeof(qyl.protocol.Copilot.StreamUpdate))]
// Meta endpoint types
[JsonSerializable(typeof(Meta.MetaResponse))]
[JsonSerializable(typeof(Meta.MetaBuild))]
[JsonSerializable(typeof(Meta.MetaCapabilities))]
[JsonSerializable(typeof(Meta.MetaStatus))]
[JsonSerializable(typeof(Meta.MetaLinks))]
[JsonSerializable(typeof(Meta.MetaPorts))]
// Error engine types
[JsonSerializable(typeof(ErrorStatusUpdate))]
[JsonSerializable(typeof(ErrorRow))]
[JsonSerializable(typeof(IReadOnlyList<ErrorRow>))]
[JsonSerializable(typeof(ErrorStats))]
[JsonSerializable(typeof(ErrorCategoryStat))]
[JsonSerializable(typeof(IReadOnlyList<ErrorCategoryStat>))]
[JsonSerializable(typeof(BuildFailureIngestRequest))]
[JsonSerializable(typeof(BuildFailureResponse))]
[JsonSerializable(typeof(BuildFailureResponse[]))]
public partial class QylSerializerContext : JsonSerializerContext;
