// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.System;

/// <summary>System Attributes (incubating).</summary>
public static class SystemAttributes
{
    /// <summary>
    /// Deprecated, use <c>cpu.logical_number</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by cpu.logical_number.", false)]
    public const string CpuLogicalNumber = "system.cpu.logical_number";

    /// <summary>
    /// Deprecated, use <c>cpu.mode</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by cpu.mode.", false)]
    public const string CpuState = "system.cpu.state";

    /// <summary>
    /// Values for the <c>CpuState</c> attribute.
    /// </summary>
    public static class CpuStateValues
    {
        /// <summary>
        /// idle.
        /// </summary>
        public const string Idle = "idle";

        /// <summary>
        /// interrupt.
        /// </summary>
        public const string Interrupt = "interrupt";

        /// <summary>
        /// iowait.
        /// </summary>
        public const string Iowait = "iowait";

        /// <summary>
        /// nice.
        /// </summary>
        public const string Nice = "nice";

        /// <summary>
        /// steal.
        /// </summary>
        public const string Steal = "steal";

        /// <summary>
        /// system.
        /// </summary>
        public const string System = "system";

        /// <summary>
        /// user.
        /// </summary>
        public const string User = "user";
    }

    /// <summary>
    /// The device identifier.
    /// </summary>
    public const string Device = "system.device";

    /// <summary>
    /// The filesystem mode.
    /// </summary>
    public const string FilesystemMode = "system.filesystem.mode";

    /// <summary>
    /// The filesystem mount path.
    /// </summary>
    public const string FilesystemMountpoint = "system.filesystem.mountpoint";

    /// <summary>
    /// The filesystem state.
    /// </summary>
    public const string FilesystemState = "system.filesystem.state";

    /// <summary>
    /// Values for the <c>FilesystemState</c> attribute.
    /// </summary>
    public static class FilesystemStateValues
    {
        /// <summary>
        /// free.
        /// </summary>
        public const string Free = "free";

        /// <summary>
        /// reserved.
        /// </summary>
        public const string Reserved = "reserved";

        /// <summary>
        /// used.
        /// </summary>
        public const string Used = "used";
    }

    /// <summary>
    /// The filesystem type.
    /// </summary>
    public const string FilesystemType = "system.filesystem.type";

    /// <summary>
    /// Values for the <c>FilesystemType</c> attribute.
    /// </summary>
    public static class FilesystemTypeValues
    {
        /// <summary>
        /// exfat.
        /// </summary>
        public const string Exfat = "exfat";

        /// <summary>
        /// ext4.
        /// </summary>
        public const string Ext4 = "ext4";

        /// <summary>
        /// fat32.
        /// </summary>
        public const string Fat32 = "fat32";

        /// <summary>
        /// hfsplus.
        /// </summary>
        public const string Hfsplus = "hfsplus";

        /// <summary>
        /// ntfs.
        /// </summary>
        public const string Ntfs = "ntfs";

        /// <summary>
        /// refs.
        /// </summary>
        public const string Refs = "refs";
    }

    /// <summary>
    /// The Linux HugePages memory state.
    /// </summary>
    public const string MemoryLinuxHugepagesState = "system.memory.linux.hugepages.state";

    /// <summary>
    /// Values for the <c>MemoryLinuxHugepagesState</c> attribute.
    /// </summary>
    public static class MemoryLinuxHugepagesStateValues
    {
        /// <summary>
        /// free.
        /// </summary>
        public const string Free = "free";

        /// <summary>
        /// used.
        /// </summary>
        public const string Used = "used";
    }

    /// <summary>
    /// The Linux Slab memory state.
    /// </summary>
    public const string MemoryLinuxSlabState = "system.memory.linux.slab.state";

    /// <summary>
    /// Values for the <c>MemoryLinuxSlabState</c> attribute.
    /// </summary>
    public static class MemoryLinuxSlabStateValues
    {
        /// <summary>
        /// reclaimable.
        /// </summary>
        public const string Reclaimable = "reclaimable";

        /// <summary>
        /// unreclaimable.
        /// </summary>
        public const string Unreclaimable = "unreclaimable";
    }

    /// <summary>
    /// The memory state.
    /// </summary>
    public const string MemoryState = "system.memory.state";

    /// <summary>
    /// Values for the <c>MemoryState</c> attribute.
    /// </summary>
    public static class MemoryStateValues
    {
        /// <summary>
        /// buffers.
        /// </summary>
        public const string Buffers = "buffers";

        /// <summary>
        /// cached.
        /// </summary>
        public const string Cached = "cached";

        /// <summary>
        /// free.
        /// </summary>
        public const string Free = "free";

        /// <summary>
        /// shared.
        /// </summary>
        [global::System.Obsolete("{\"note\": \"Removed, report shared memory usage with `metric.system.memory.linux.shared` metric\", \"reason\": \"uncategorized\"}", false)]
        public const string Shared = "shared";

        /// <summary>
        /// Actual used virtual memory in bytes.
        /// </summary>
        public const string Used = "used";
    }

    /// <summary>
    /// Deprecated, use <c>network.connection.state</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by network.connection.state.", false)]
    public const string NetworkState = "system.network.state";

    /// <summary>
    /// Values for the <c>NetworkState</c> attribute.
    /// </summary>
    public static class NetworkStateValues
    {
        /// <summary>
        /// close.
        /// </summary>
        public const string Close = "close";

        /// <summary>
        /// close_wait.
        /// </summary>
        public const string CloseWait = "close_wait";

        /// <summary>
        /// closing.
        /// </summary>
        public const string Closing = "closing";

        /// <summary>
        /// delete.
        /// </summary>
        public const string Delete = "delete";

        /// <summary>
        /// established.
        /// </summary>
        public const string Established = "established";

        /// <summary>
        /// fin_wait_1.
        /// </summary>
        public const string FinWait1 = "fin_wait_1";

        /// <summary>
        /// fin_wait_2.
        /// </summary>
        public const string FinWait2 = "fin_wait_2";

        /// <summary>
        /// last_ack.
        /// </summary>
        public const string LastAck = "last_ack";

        /// <summary>
        /// listen.
        /// </summary>
        public const string Listen = "listen";

        /// <summary>
        /// syn_recv.
        /// </summary>
        public const string SynRecv = "syn_recv";

        /// <summary>
        /// syn_sent.
        /// </summary>
        public const string SynSent = "syn_sent";

        /// <summary>
        /// time_wait.
        /// </summary>
        public const string TimeWait = "time_wait";
    }

    /// <summary>
    /// The paging access direction.
    /// </summary>
    public const string PagingDirection = "system.paging.direction";

    /// <summary>
    /// Values for the <c>PagingDirection</c> attribute.
    /// </summary>
    public static class PagingDirectionValues
    {
        /// <summary>
        /// in.
        /// </summary>
        public const string In = "in";

        /// <summary>
        /// out.
        /// </summary>
        public const string Out = "out";
    }

    /// <summary>
    /// The paging fault type.
    /// </summary>
    public const string PagingFaultType = "system.paging.fault.type";

    /// <summary>
    /// Values for the <c>PagingFaultType</c> attribute.
    /// </summary>
    public static class PagingFaultTypeValues
    {
        /// <summary>
        /// major.
        /// </summary>
        public const string Major = "major";

        /// <summary>
        /// minor.
        /// </summary>
        public const string Minor = "minor";
    }

    /// <summary>
    /// The memory paging state.
    /// </summary>
    public const string PagingState = "system.paging.state";

    /// <summary>
    /// Values for the <c>PagingState</c> attribute.
    /// </summary>
    public static class PagingStateValues
    {
        /// <summary>
        /// free.
        /// </summary>
        public const string Free = "free";

        /// <summary>
        /// used.
        /// </summary>
        public const string Used = "used";
    }

    /// <summary>
    /// Deprecated, use <c>system.paging.fault.type</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by system.paging.fault.type.", false)]
    public const string PagingType = "system.paging.type";

    /// <summary>
    /// Values for the <c>PagingType</c> attribute.
    /// </summary>
    public static class PagingTypeValues
    {
        /// <summary>
        /// major.
        /// </summary>
        public const string Major = "major";

        /// <summary>
        /// minor.
        /// </summary>
        public const string Minor = "minor";
    }

    /// <summary>
    /// Deprecated, use <c>process.state</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by process.state.", false)]
    public const string ProcessStatus = "system.process.status";

    /// <summary>
    /// Values for the <c>ProcessStatus</c> attribute.
    /// </summary>
    public static class ProcessStatusValues
    {
        /// <summary>
        /// defunct.
        /// </summary>
        public const string Defunct = "defunct";

        /// <summary>
        /// running.
        /// </summary>
        public const string Running = "running";

        /// <summary>
        /// sleeping.
        /// </summary>
        public const string Sleeping = "sleeping";

        /// <summary>
        /// stopped.
        /// </summary>
        public const string Stopped = "stopped";
    }

    /// <summary>
    /// Deprecated, use <c>process.state</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by process.state.", false)]
    public const string ProcessesStatus = "system.processes.status";

    /// <summary>
    /// Values for the <c>ProcessesStatus</c> attribute.
    /// </summary>
    public static class ProcessesStatusValues
    {
        /// <summary>
        /// defunct.
        /// </summary>
        public const string Defunct = "defunct";

        /// <summary>
        /// running.
        /// </summary>
        public const string Running = "running";

        /// <summary>
        /// sleeping.
        /// </summary>
        public const string Sleeping = "sleeping";

        /// <summary>
        /// stopped.
        /// </summary>
        public const string Stopped = "stopped";
    }
}
