// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Source;

/// <summary>Source Attributes (incubating).</summary>
public static class SourceAttributes
{
    /// <summary>Source address - domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name..</summary>
    /// <remarks>When observed from the destination side, and when communicating through an intermediary, `source.address` SHOULD represent the source address behind any intermediaries, for example proxies, if it's available.</remarks>
    public const string Address = "source.address";

    /// <summary>Source port number.</summary>
    public const string Port = "source.port";

}