#!/usr/bin/env python3
# Copyright (c) 2025-2026 ancplua
"""
Generates DeprecatedDiagnostics.g.cs from
eng/semconv/deprecated-lookup/master-programmatic.yaml.

One DiagnosticDescriptor is emitted per deprecated entry (QYLSC0001 onward),
so consumers can tune severity per entry via .editorconfig.

Usage:
    python3 gen.py \
        --yaml eng/semconv/deprecated-lookup/master-programmatic.yaml \
        --out  packages/Qyl.OpenTelemetry.SemanticConventions.Analyzers/Model/DeprecatedDiagnostics.g.cs
"""
from __future__ import annotations

import argparse
import pathlib
import sys
import textwrap

import yaml

CS_ESCAPES = {'"': r'\"', "\\": r"\\"}


def cs_escape(value: str) -> str:
    """Escape a string for a C# verbatim-safe literal."""
    out: list[str] = []
    for ch in value:
        if ch in CS_ESCAPES:
            out.append(CS_ESCAPES[ch])
        elif ch == "\n":
            out.append(r"\n")
        elif ch == "\r":
            out.append(r"\r")
        elif ch == "\t":
            out.append(r"\t")
        else:
            out.append(ch)
    return "".join(out)


VALID_MODES = {
    "direct",
    "alternative",
    "field_mapping",
    "integrate",
    "removed",
    "composite",
    "conditional",
    "contextual",
    "example",
    "note_only",
}

VALID_KINDS = {"attribute", "metric", "event", "entity", "enum_member"}
VALID_STATUSES = {"renamed", "obsoleted", "uncategorized"}


def mode_to_enum(mode: str) -> str:
    if mode not in VALID_MODES:
        raise SystemExit(f"unknown replacement_mode: {mode!r}")
    # PascalCase C# enum members
    return {
        "direct": "Direct",
        "alternative": "Alternative",
        "field_mapping": "FieldMapping",
        "integrate": "Integrate",
        "removed": "Removed",
        "composite": "Composite",
        "conditional": "Conditional",
        "contextual": "Contextual",
        "example": "Example",
        "note_only": "NoteOnly",
    }[mode]


def kind_to_enum(kind: str) -> str:
    if kind not in VALID_KINDS:
        raise SystemExit(f"unknown kind: {kind!r}")
    return {
        "attribute": "Attribute",
        "metric": "Metric",
        "event": "Event",
        "entity": "Entity",
        "enum_member": "EnumMember",
    }[kind]


def make_title(entry: dict) -> str:
    return f"{entry['deprecated_id']} is deprecated"


def make_message(entry: dict) -> str:
    status = entry.get("status", "")
    resolution = entry.get("resolution_text") or ""
    replacements = entry.get("replacements") or []

    if status == "renamed" and replacements:
        return f"'{{0}}' is deprecated. Use '{replacements[0]}' instead."
    if replacements and entry.get("replacement_mode") == "alternative":
        choices = ", ".join(f"'{r}'" for r in replacements)
        return f"'{{0}}' is deprecated. Use one of: {choices}."
    if entry.get("replacement_mode") == "removed":
        return f"'{{0}}' is deprecated and has been removed with no replacement."
    if resolution:
        return f"'{{0}}' is deprecated ({resolution})."
    return f"'{{0}}' is deprecated."


def make_help_link(entry: dict, tag: str) -> str:
    src_file = entry.get("source_file") or ""
    src_line = entry.get("source_line") or 0
    if not src_file:
        return "https://github.com/open-telemetry/semantic-conventions"
    return (
        "https://github.com/open-telemetry/semantic-conventions/"
        f"blob/{tag}/{src_file}#L{src_line}"
    )


def make_description(entry: dict, tag: str) -> str:
    basis = entry.get("resolution_basis") or ""
    kind = entry.get("kind") or ""
    folder = entry.get("folder") or ""
    parts = [f"OTel semconv {tag} deprecated {kind}"]
    if folder:
        parts.append(f"(folder: {folder})")
    if basis:
        parts.append(f"[basis: {basis}]")
    return " ".join(parts)


HEADER = """\
// <auto-generated/>
// Copyright (c) 2025-2026 ancplua
//
// Generated from eng/semconv/deprecated-lookup/master-programmatic.yaml
// Regenerate: python3 eng/semconv/tools/gen-deprecated-diagnostics/gen.py
//
// One DiagnosticDescriptor per deprecated OTel semantic-convention entry.
// Each entry has its own rule id (QYLSC0001..QYLSC{count:04d}) so consumers can
// tune severity per entry via .editorconfig.

#nullable enable
using System.Collections.Generic;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;

namespace Qyl.OpenTelemetry.SemanticConventions.Analyzers.Model;

internal enum DeprecatedReplacementMode
{
    Direct,
    Alternative,
    FieldMapping,
    Integrate,
    Removed,
    Composite,
    Conditional,
    Contextual,
    Example,
    NoteOnly,
}

internal enum DeprecatedEntryKind
{
    Attribute,
    Metric,
    Event,
    Entity,
    EnumMember,
}

internal sealed record DeprecatedEntry(
    string DeprecatedId,
    string RuleId,
    DiagnosticDescriptor Descriptor,
    DeprecatedReplacementMode Mode,
    DeprecatedEntryKind Kind,
    ImmutableArray<string> Replacements,
    string ResolutionText,
    string ResolutionBasis,
    string Folder);

internal static partial class DeprecatedDiagnostics
{
"""


def descriptor_field(rule_id: str, title: str, message: str, desc: str, help_link: str) -> str:
    return textwrap.dedent(
        f'''\
        private static readonly DiagnosticDescriptor s_{rule_id.lower()} = new(
            id: "{rule_id}",
            title: "{cs_escape(title)}",
            messageFormat: "{cs_escape(message)}",
            category: "QylSemanticConventions",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "{cs_escape(desc)}",
            helpLinkUri: "{cs_escape(help_link)}");
        '''
    )


def entry_record(entry: dict, rule_id: str) -> str:
    mode = mode_to_enum(entry["replacement_mode"])
    kind = kind_to_enum(entry["kind"])
    replacements = entry.get("replacements") or []
    replacements_arg = (
        "ImmutableArray<string>.Empty"
        if not replacements
        else "ImmutableArray.Create(" + ", ".join(f'"{cs_escape(r)}"' for r in replacements) + ")"
    )
    resolution_text = cs_escape(entry.get("resolution_text") or "")
    resolution_basis = cs_escape(entry.get("resolution_basis") or "")
    folder = cs_escape(entry.get("folder") or "")
    return (
        f'new DeprecatedEntry('
        f'DeprecatedId: "{cs_escape(entry["deprecated_id"])}", '
        f'RuleId: "{rule_id}", '
        f'Descriptor: s_{rule_id.lower()}, '
        f'Mode: DeprecatedReplacementMode.{mode}, '
        f'Kind: DeprecatedEntryKind.{kind}, '
        f'Replacements: {replacements_arg}, '
        f'ResolutionText: "{resolution_text}", '
        f'ResolutionBasis: "{resolution_basis}", '
        f'Folder: "{folder}")'
    )


def render(entries: list[dict], tag: str) -> str:
    # Deterministic order: by (folder, kind, deprecated_id).
    entries_sorted = sorted(
        entries,
        key=lambda e: (
            e.get("folder") or "",
            e.get("kind") or "",
            e.get("deprecated_id") or "",
        ),
    )

    for i, e in enumerate(entries_sorted):
        if e.get("kind") not in VALID_KINDS:
            raise SystemExit(f"entry {i}: bad kind {e.get('kind')!r}")
        if e.get("status") not in VALID_STATUSES:
            raise SystemExit(f"entry {i}: bad status {e.get('status')!r}")
        # enum_member entries carry their id under deprecated_member_id; normalize.
        if not e.get("deprecated_id"):
            member = e.get("deprecated_member_id")
            if not member:
                raise SystemExit(f"entry {i}: missing deprecated_id and deprecated_member_id")
            e["deprecated_id"] = member

    count = len(entries_sorted)
    lines: list[str] = [HEADER.replace("{count:04d}", f"{count:04d}")]

    # Emit descriptor fields
    for i, entry in enumerate(entries_sorted, start=1):
        rule_id = f"QYLSC{i:04d}"
        lines.append(
            "    "
            + descriptor_field(
                rule_id=rule_id,
                title=make_title(entry),
                message=make_message(entry),
                desc=make_description(entry, tag),
                help_link=make_help_link(entry, tag),
            ).replace("\n", "\n    ").rstrip()
            + "\n"
        )

    # Emit entry records in a dictionary initializer
    lines.append("    public static readonly ImmutableDictionary<string, DeprecatedEntry> ByDeprecatedId =\n")
    lines.append("        new Dictionary<string, DeprecatedEntry>(System.StringComparer.OrdinalIgnoreCase)\n")
    lines.append("        {\n")
    for i, entry in enumerate(entries_sorted, start=1):
        rule_id = f"QYLSC{i:04d}"
        record = entry_record(entry, rule_id)
        lines.append(f'            ["{cs_escape(entry["deprecated_id"])}"] = {record},\n')
    lines.append("        }.ToImmutableDictionary(System.StringComparer.OrdinalIgnoreCase);\n\n")

    # Rule ids list and descriptors
    lines.append("    public static readonly ImmutableArray<DiagnosticDescriptor> AllDescriptors =\n")
    lines.append("        ImmutableArray.Create(\n")
    for i in range(1, count + 1):
        rule_id = f"QYLSC{i:04d}"
        comma = "," if i < count else ""
        lines.append(f"            s_{rule_id.lower()}{comma}\n")
    lines.append("        );\n\n")

    lines.append("    public static readonly ImmutableArray<string> AllRuleIds =\n")
    lines.append("        ImmutableArray.Create(\n")
    for i in range(1, count + 1):
        rule_id = f"QYLSC{i:04d}"
        comma = "," if i < count else ""
        lines.append(f'            "{rule_id}"{comma}\n')
    lines.append("        );\n")

    lines.append("}\n")
    return "".join(lines)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--yaml", required=True)
    p.add_argument("--out", required=True)
    args = p.parse_args()

    yaml_path = pathlib.Path(args.yaml)
    out_path = pathlib.Path(args.out)
    if not yaml_path.exists():
        print(f"[gen-deprecated-diagnostics] missing yaml: {yaml_path}", file=sys.stderr)
        return 1

    with yaml_path.open("r", encoding="utf-8") as f:
        doc = yaml.safe_load(f)

    entries = doc.get("entries") or []
    if not entries:
        print("[gen-deprecated-diagnostics] no entries found", file=sys.stderr)
        return 1

    tag = ((doc.get("source") or {}).get("tag")) or "main"
    text = render(entries, tag)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8-sig")
    print(f"[gen-deprecated-diagnostics] wrote {out_path} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
