// =============================================================================
// INTENTIONALLY BROKEN — OTelEmitter with constants instead of string literals
// =============================================================================
// This is the Agents generator's OTelEmitter rewritten to reference the Stage 1
// generated constants (GenAiAttributes.Metrics.*) instead of hardcoded strings.
//
// IT WILL NOT COMPILE because:
//   1. Qyl.Agents.Generator targets netstandard2.0 (Roslyn analyzer)
//   2. GenAiAttributes.g.cs lives in qyl.contracts (net10.0)
//   3. A Roslyn generator cannot reference a net10.0 project
//
// This is the structural problem: the pipeline's own output (Stage 1 constants)
// cannot be consumed by its own generators (Stage 6) due to TFM mismatch.
//
// Fix options:
//   A. Emit the constant values into the generator via <Compile Include> of a
//      shared constants file generated by Stage 1 (netstandard2.0 compatible)
//   B. The generator reads the constant values from qyl-extensions.json at
//      compile time via AdditionalFiles, not from C# references
//   C. Accept the string duplication and add a test that asserts the generator's
//      strings match the generated constants (current implicit approach)
// =============================================================================

namespace Qyl.Agents.Generator.Generation;

using Models;

internal static class OTelEmitterBroken
{
    public static void Emit(IndentedStringBuilder sb, ServerModel server)
    {
        sb.AppendLine("private static readonly string s_instrumentationVersion =");
        sb.AppendLine($"    typeof({server.ClassName}).Assembly.GetName().Version?.ToString() ?? \"0.0.0\";");
        sb.AppendLine();

        sb.AppendLine("private static readonly global::System.Diagnostics.ActivitySource s_activitySource =");
        sb.AppendLine("    new global::System.Diagnostics.ActivitySource(\"Qyl.Agents\", s_instrumentationVersion);");
        sb.AppendLine();

        sb.AppendLine("private static readonly global::System.Diagnostics.Metrics.Meter s_meter =");
        sb.AppendLine("    new global::System.Diagnostics.Metrics.Meter(\"Qyl.Agents\", s_instrumentationVersion);");
        sb.AppendLine();

        // BROKEN: These reference GenAiAttributes which is in qyl.contracts (net10.0).
        // A netstandard2.0 Roslyn generator cannot see this type. CS0103.
        sb.AppendLine(
            "private static readonly global::System.Diagnostics.Metrics.Histogram<double> s_requestDuration =");
        sb.AppendLine(
            $"    s_meter.CreateHistogram<double>(GenAiAttributes.Metrics.ClientOperationDuration, \"s\", \"Duration of tool execution\");");
        sb.AppendLine();

        // BROKEN: Same — McpAttributes is in qyl.contracts, invisible to the generator.
        sb.AppendLine(
            "private static readonly global::System.Diagnostics.Metrics.Histogram<double> s_mcpOperationDuration =");
        sb.AppendLine(
            $"    s_meter.CreateHistogram<double>(McpAttributes.Metrics.ServerOperationDuration, \"s\", \"Duration of MCP server operations\");");
    }
}
