using ANcpLua.Roslyn.Utilities;
using Qyl.Mcp.Generators.Models;

namespace Qyl.Mcp.Generators.Emitters;

internal static class ToolManifestEmitter
{
    public static string Emit(
        EquatableArray<ToolTypeEntry> toolTypes,
        EquatableArray<CapabilityDefinitionEntry> definitions)
    {
        if (toolTypes.IsEmpty)
            return string.Empty;

        var sorted = toolTypes
            .OrderBy(static e => e.FullyQualifiedTypeName, StringComparer.Ordinal)
            .ToArray();

        var capabilityToolIndex = BuildCapabilityToolIndex(sorted);

        var sb = new IndentedStringBuilder();
        sb.AppendLineNoIndent("// <auto-generated/>");
        sb.AppendLineNoIndent("#pragma warning disable");
        sb.AppendLine();

        using (sb.BeginNamespace("Qyl.Generated"))
        using (sb.BeginClass("internal static", "QylToolManifest"))
        {
            EmitToolTypesArray(sb, sorted);
            sb.AppendLine();
            EmitToolDescriptorsArray(sb, sorted);
            sb.AppendLine();
            EmitCapabilitiesArray(sb, definitions, capabilityToolIndex);
            sb.AppendLine();
            EmitCreateToolsMethod(sb, sorted);
            sb.AppendLine();
            EmitRegisterToolsMethod(sb, sorted);
            sb.AppendLine();
            EmitRegisterServicesMethod(sb, sorted);
        }

        return sb.ToString();
    }

    private static Dictionary<string, (List<string> Starting, List<string> FollowUp)> BuildCapabilityToolIndex(
        ToolTypeEntry[] sorted)
    {
        var index = new Dictionary<string, (List<string>, List<string>)>(StringComparer.Ordinal);

        foreach (var entry in sorted)
        {
            foreach (var method in entry.Methods)
            {
                foreach (var attribution in method.Capabilities)
                {
                    if (!index.TryGetValue(attribution.CapabilityId, out var buckets))
                    {
                        buckets = (new List<string>(), new List<string>());
                        index[attribution.CapabilityId] = buckets;
                    }

                    var target = attribution.Role == CapabilityRoleKind.FollowUp ? buckets.Item2 : buckets.Item1;
                    if (!target.Contains(method.ToolName, StringComparer.Ordinal))
                        target.Add(method.ToolName);
                }
            }
        }

        return index;
    }

    private static void EmitToolTypesArray(IndentedStringBuilder sb, ToolTypeEntry[] sorted)
    {
        sb.AppendLine("public static readonly global::System.Type[] ToolTypes =");
        using (sb.BeginBlock())
        {
            foreach (var entry in sorted)
                sb.AppendLine($"typeof({entry.FullyQualifiedTypeName}),");
        }
        sb.AppendLine(";");
    }

    private static void EmitToolDescriptorsArray(IndentedStringBuilder sb, ToolTypeEntry[] sorted)
    {
        sb.AppendLine(
            "public static readonly global::qyl.mcp.Metadata.ToolDescriptor[] ToolDescriptors =");
        using (sb.BeginBlock())
        {
            foreach (var entry in sorted)
            {
                foreach (var method in entry.Methods)
                {
                    sb.AppendLine("new()");
                    using (sb.BeginBlock())
                    {
                        sb.AppendLine($"Name = {StringLiteral(method.ToolName)},");
                        sb.AppendLine($"MethodName = {StringLiteral(method.MethodName)},");
                        sb.AppendLine($"DeclaringType = {StringLiteral(entry.FullyQualifiedTypeName)},");
                        sb.AppendLine($"Skill = {StringLiteral(SkillLabel(entry.SkillKindName))},");
                        sb.AppendLine($"SkillKind = {SkillKindExpression(entry.SkillKindName)},");
                        sb.AppendLine($"Title = {StringLiteral(method.Title)},");
                        sb.AppendLine($"Description = {StringLiteral(method.Description)},");
                        sb.AppendLine($"ReadOnly = {BoolLiteral(method.ReadOnly)},");
                        sb.AppendLine($"Destructive = {BoolLiteral(method.Destructive)},");
                        sb.AppendLine($"Idempotent = {BoolLiteral(method.Idempotent)},");
                        sb.AppendLine($"OpenWorld = {BoolLiteral(method.OpenWorld)},");
                        sb.AppendLine($"ReturnType = {StringLiteral(method.ReturnTypeDisplayName)},");
                    }
                    sb.AppendLine(",");
                }
            }
        }
        sb.AppendLine(";");
    }

    private static void EmitCapabilitiesArray(
        IndentedStringBuilder sb,
        EquatableArray<CapabilityDefinitionEntry> definitions,
        Dictionary<string, (List<string> Starting, List<string> FollowUp)> capabilityToolIndex)
    {
        sb.AppendLine(
            "public static readonly global::qyl.mcp.Capabilities.QylCapabilityDescriptor[] Capabilities =");
        using (sb.BeginBlock())
        {
            foreach (var def in definitions.OrderBy(static d => d.Id, StringComparer.Ordinal))
            {
                capabilityToolIndex.TryGetValue(def.Id, out var buckets);
                var starting = buckets.Starting ?? [];
                var followUp = buckets.FollowUp ?? [];
                var allTools = starting.Concat(followUp).Distinct(StringComparer.Ordinal).ToList();
                var skillLabel = !string.IsNullOrEmpty(def.SkillLabel)
                    ? def.SkillLabel
                    : SkillLabel(def.RequiredSkillKindName);

                sb.AppendLine("new()");
                using (sb.BeginBlock())
                {
                    sb.AppendLine($"Id = {StringLiteral(def.Id)},");
                    sb.AppendLine($"Title = {StringLiteral(def.Title)},");
                    sb.AppendLine($"Summary = {StringLiteral(def.Summary)},");
                    sb.AppendLine($"Skill = {StringLiteral(skillLabel)},");
                    sb.AppendLine($"RequiredSkill = {SkillKindExpression(def.RequiredSkillKindName)},");
                    EmitStringArrayInit(sb, "Tags", def.Tags);
                    EmitStringArrayInit(sb, "ToolNames", allTools);
                    EmitStringArrayInit(sb, "UseCases", def.UseCases);
                    EmitStringArrayInit(sb, "PrimaryIdentifiers", def.PrimaryIdentifiers);
                    EmitStringArrayInit(sb, "StartingTools", starting);
                    EmitStringArrayInit(sb, "FollowUpTools", followUp);
                    EmitStringArrayInit(sb, "ScopingHints", def.ScopingHints);
                    EmitStringArrayInit(sb, "EvidenceHints", def.EvidenceHints);
                    EmitStringArrayInit(sb, "RelatedCapabilityIds", def.RelatedCapabilities);
                }
                sb.AppendLine(",");
            }
        }
        sb.AppendLine(";");
    }

    private static void EmitStringArrayInit(IndentedStringBuilder sb, string propertyName, IEnumerable<string> values)
    {
        var list = values.ToList();
        if (list.Count == 0)
        {
            sb.AppendLine($"{propertyName} = global::System.Array.Empty<string>(),");
            return;
        }

        sb.AppendLine($"{propertyName} = new string[]");
        using (sb.BeginBlock())
        {
            foreach (var value in list)
                sb.AppendLine($"{StringLiteral(value)},");
        }
        sb.AppendLine(",");
    }

    private static void EmitCreateToolsMethod(IndentedStringBuilder sb, ToolTypeEntry[] sorted)
    {
        sb.AppendLine(
            "public static global::System.Collections.Generic.List<global::Microsoft.Extensions.AI.AIFunction> CreateTools(");
        sb.AppendLine("    global::System.IServiceProvider services,");
        sb.AppendLine("    global::System.Func<global::System.Type, bool>? filter = null)");
        using (sb.BeginBlock())
        {
            sb.AppendLine(
                "var tools = new global::System.Collections.Generic.List<global::Microsoft.Extensions.AI.AIFunction>();");

            foreach (var entry in sorted)
            {
                if (entry.Methods.IsEmpty)
                    continue;

                sb.AppendLine();
                sb.AppendLine($"if (filter?.Invoke(typeof({entry.FullyQualifiedTypeName})) != false)");
                using (sb.BeginBlock())
                {
                    var local = SafeLocalName(entry);
                    sb.AppendLine(
                        $"var {local} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{entry.FullyQualifiedTypeName}>(services);");

                    foreach (var method in entry.Methods)
                    {
                        sb.AppendLine(
                            $"tools.Add(global::Microsoft.Extensions.AI.AIFunctionFactory.Create({local}.{method.MethodName}, new global::Microsoft.Extensions.AI.AIFunctionFactoryOptions {{ Name = {StringLiteral(method.ToolName)} }}));");
                    }
                }
            }

            sb.AppendLine();
            sb.AppendLine("return tools;");
        }
    }

    private static void EmitRegisterToolsMethod(IndentedStringBuilder sb, ToolTypeEntry[] sorted)
    {
        sb.AppendLine("public static void RegisterTools(");
        sb.AppendLine("    global::Microsoft.Extensions.DependencyInjection.IMcpServerBuilder mcpBuilder,");
        sb.AppendLine("    global::qyl.mcp.Skills.SkillConfiguration skills,");
        sb.AppendLine("    global::System.Text.Json.JsonSerializerOptions jsonOptions)");
        using (sb.BeginBlock())
        {
            foreach (var group in GroupBySkill(sorted))
            {
                sb.AppendLine(
                    $"if (skills.IsEnabled(global::qyl.mcp.Skills.QylSkillKind.{group.Key}))");
                using (sb.BeginBlock())
                {
                    foreach (var entry in group.Value)
                    {
                        sb.AppendLine(
                            $"global::Microsoft.Extensions.DependencyInjection.McpServerBuilderExtensions.WithTools<{entry.FullyQualifiedTypeName}>(mcpBuilder, jsonOptions);");
                    }
                }
            }
        }
    }

    private static void EmitRegisterServicesMethod(IndentedStringBuilder sb, ToolTypeEntry[] sorted)
    {
        sb.AppendLine("public static void RegisterServices(");
        sb.AppendLine("    global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        sb.AppendLine("    global::qyl.mcp.Skills.SkillConfiguration skills)");
        using (sb.BeginBlock())
        {
            foreach (var group in GroupBySkill(sorted))
            {
                sb.AppendLine(
                    $"if (skills.IsEnabled(global::qyl.mcp.Skills.QylSkillKind.{group.Key}))");
                using (sb.BeginBlock())
                {
                    foreach (var entry in group.Value)
                    {
                        sb.AppendLine(
                            $"global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<{entry.FullyQualifiedTypeName}>(services);");
                    }
                }
            }
        }
    }

    private static SortedDictionary<string, List<ToolTypeEntry>> GroupBySkill(ToolTypeEntry[] sorted)
    {
        var groups = new SortedDictionary<string, List<ToolTypeEntry>>(StringComparer.Ordinal);
        foreach (var entry in sorted)
        {
            if (entry.SkillKindName is null)
                continue;

            if (!groups.TryGetValue(entry.SkillKindName, out var list))
            {
                list = [];
                groups[entry.SkillKindName] = list;
            }

            list.Add(entry);
        }

        return groups;
    }

    private static string SkillLabel(string? skillKindName) =>
        skillKindName switch
        {
            "Inspect" => "inspect",
            "Health" => "health",
            "Analytics" => "analytics",
            "Agent" => "agent",
            "Build" => "build",
            "Anomaly" => "anomaly",
            "Loom" => "loom",
            "Apps" => "apps",
            "Debug" => "debug",
            _ => "core"
        };

    private static string SkillKindExpression(string? skillKindName) =>
        skillKindName is null ? "null" : $"global::qyl.mcp.Skills.QylSkillKind.{skillKindName}";

    private static string SafeLocalName(ToolTypeEntry entry)
    {
        var fqn = entry.FullyQualifiedTypeName;
        return "svc_" + fqn
            .Replace("global::", string.Empty, StringComparison.Ordinal)
            .Replace('.', '_')
            .Replace(':', '_')
            .Replace('+', '_')
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace(',', '_')
            .Replace(' ', '_');
    }

    private static string BoolLiteral(bool value) => value ? "true" : "false";

    private static string StringLiteral(string? value)
    {
        if (value is null)
            return "null";

        return "\"" + value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal) + "\"";
    }
}
