using System;
using System.Globalization;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Qyl.Sdk.Xml.Generator;

/// <summary>Writes the partial type that implements <c>Qyl.Xml.IXmlWritable</c> for an <see cref="XmlModelSpec"/>.</summary>
internal static class XmlWriterEmitter
{
    private const string XmlSchemaInstanceNamespace = "http://www.w3.org/2001/XMLSchema-instance";

    public static string Emit(XmlModelSpec spec)
    {
        var code = new CodeWriter();
        var modifiers = spec.HidesBaseImplementation ? "public new " : "public ";

        code.Line("// <auto-generated/>");
        code.Line("// Generated by Qyl.Sdk.Xml.Generator for [GenerateXml]. Do not edit; change the model instead.");
        code.Line("#nullable enable");
        code.Line();

        if (spec.Namespace is not null)
        {
            code.Line("namespace " + spec.Namespace);
            code.Open();
        }

        code.Line("partial " + spec.TypeKeyword + " " + spec.TypeName + " : global::Qyl.Xml.IXmlWritable");
        code.Open();

        EmitShape(code, spec, modifiers);
        code.Line();

        code.Line("/// <inheritdoc />");
        code.Line(modifiers + "void WriteXml(global::System.Xml.XmlWriter writer)");
        code.Open();
        code.Line("global::System.ArgumentNullException.ThrowIfNull(writer);");
        code.Line();
        code.Line("WriteXml(writer, " + Literal(spec.Root.LocalName) + ", " + NamespaceArgument(spec.Root.Namespace) + ");");
        code.Close();
        code.Line();

        code.Line("/// <inheritdoc />");
        code.Line(modifiers + "void WriteXml(global::System.Xml.XmlWriter writer, string localName, string? ns)");
        code.Open();
        code.Line("global::System.ArgumentNullException.ThrowIfNull(writer);");
        code.Line("global::System.ArgumentNullException.ThrowIfNull(localName);");
        code.Line();
        code.Line("if (ns is null)");
        code.Open();
        code.Line("writer.WriteStartElement(localName);");
        code.Close();
        code.Line("else");
        code.Open();
        code.Line("writer.WriteStartElement(null, localName, ns);");
        code.Close();
        code.Line();

        // XmlWriter requires attributes before any content; XmlSerializer writes them first as well.
        var index = 0;
        foreach (var node in spec.Nodes)
        {
            if (node is XmlAttributeNode attribute)
            {
                EmitAttribute(code, attribute, index++);
            }
        }

        foreach (var node in spec.Nodes)
        {
            if (node is not XmlAttributeNode)
            {
                EmitContent(code, node, index++);
            }
        }

        code.Line("writer.WriteEndElement();");
        code.Close();

        foreach (var enumSpec in spec.Enums)
        {
            code.Line();
            EmitEnumFormatter(code, enumSpec);
        }

        code.Close();

        if (spec.Namespace is not null)
        {
            code.Close();
        }

        return code.ToString();
    }

    /// <summary>The same tree as data: what the OpenAPI contract describes the document with.</summary>
    private static void EmitShape(CodeWriter code, XmlModelSpec spec, string modifiers)
    {
        code.Line("/// <inheritdoc />");
        code.Line(modifiers + "static global::Qyl.Xml.XmlShape XmlShape { get; } = CreateXmlShape();");
        code.Line();
        // A method rather than the initializer itself: a model that refers to itself reads XmlShape inside a lambda, which the
        // compiler would otherwise treat as a read of the not-yet-assigned property.
        code.Line("private static global::Qyl.Xml.XmlShape CreateXmlShape() => new global::Qyl.Xml.XmlShape(");
        code.Line("    " + Literal(spec.TypeName) + ",");
        code.Line("    " + Name(spec.Root) + ",");
        code.Line("    new global::Qyl.Xml.XmlShapeNode[]");
        code.Line("    {");

        foreach (var node in spec.Nodes)
        {
            if (node is XmlAttributeNode attribute)
            {
                code.Line("        new global::Qyl.Xml.XmlAttributeShape(" + Literal(attribute.PropertyName) + ", " + Name(attribute.Name) + ", " +
                    ScalarShape(attribute.Value, spec) + ", " + Bool(attribute.Value.IsNullable) + "),");
            }
        }

        foreach (var node in spec.Nodes)
        {
            switch (node)
            {
                case XmlElementNode element:
                    code.Line("        new global::Qyl.Xml.XmlElementShape(" + Literal(element.PropertyName) + ", " + Name(element.Name) + ", " +
                        ScalarShape(element.Value, spec) + ", " + Bool(element.Value.IsNullable && !element.WriteNil) + ", " + Bool(element.WriteNil) + "),");
                    break;
                case XmlTextNode text:
                    code.Line("        new global::Qyl.Xml.XmlTextShape(" + Literal(text.PropertyName) + ", " + ScalarShape(text.Value, spec) + ", " +
                        Bool(text.Value.IsNullable) + "),");
                    break;
                case XmlModelNode model:
                    code.Line("        new global::Qyl.Xml.XmlModelShape(" + Literal(model.PropertyName) + ", " + Name(model.Name) + ", static () => " +
                        model.TypeName + ".XmlShape, " + Bool(!model.WriteNil) + ", " + Bool(model.WriteNil) + "),");
                    break;
                case XmlCollectionNode collection:
                    var itemCanBeAbsent = collection.ItemScalar is null || collection.ItemScalar.IsNullable;
                    code.Line("        new global::Qyl.Xml.XmlCollectionShape(" + Literal(collection.PropertyName) + ", " +
                        (collection.Wrapper is { } wrapper ? Name(wrapper) : "null") + ", " + Name(collection.ItemName) + ", " +
                        (collection.ItemScalar is { } itemScalar ? ScalarShape(itemScalar, spec) : "null") + ", " +
                        (collection.ItemTypeName is { } itemType ? "static () => " + itemType + ".XmlShape" : "null") + ", " +
                        Bool(!collection.WrapperWriteNil) + ", " + Bool(collection.ItemWriteNil && itemCanBeAbsent) + "),");
                    break;
            }
        }

        code.Line("    });");
    }

    private static string ScalarShape(XmlScalarSpec scalar, XmlModelSpec spec)
    {
        var values = "null";
        if (scalar.Kind == ValueKind.Enum)
        {
            foreach (var enumSpec in spec.Enums)
            {
                if (enumSpec.FormatterName == scalar.EnumFormatter && !enumSpec.IsFlags)
                {
                    var names = new System.Text.StringBuilder("new string[] { ");
                    foreach (var member in enumSpec.Members)
                    {
                        names.Append(Literal(member.XmlName)).Append(", ");
                    }

                    values = names.Append('}').ToString();
                }
            }
        }

        return "new global::Qyl.Xml.XmlScalarShape(global::Qyl.Xml.XmlScalarType." + scalar.SchemaType + ", " + values + ")";
    }

    private static string Name(XmlNameSpec name) => "new global::Qyl.Xml.XmlName(" + Literal(name.LocalName) + ", " + NamespaceArgument(name.Namespace) + ")";

    private static string Bool(bool value) => value ? "true" : "false";

    private static void EmitAttribute(CodeWriter code, XmlAttributeNode node, int index)
    {
        var local = DeclareLocal(code, node.PropertyName, index);
        var prefix = "writer.WriteAttributeString(" + Literal(node.Name.LocalName) + ", " +
            (node.Name.Namespace is null ? string.Empty : Literal(node.Name.Namespace) + ", ");

        EmitGuarded(code, node.Value, local, value => code.Line(prefix + Format(value, node.Value) + ");"), whenAbsent: null);
    }

    private static void EmitContent(CodeWriter code, XmlNodeSpec node, int index)
    {
        var local = DeclareLocal(code, node.PropertyName, index);

        switch (node)
        {
            case XmlElementNode element:
                EmitGuarded(
                    code,
                    element.Value,
                    local,
                    value => EmitScalarElement(code, element.Name, Format(value, element.Value)),
                    element.WriteNil ? () => EmitNilElement(code, element.Name) : null);
                break;

            case XmlTextNode text:
                EmitGuarded(code, text.Value, local, value => code.Line("writer.WriteString(" + Format(value, text.Value) + ");"), whenAbsent: null);
                break;

            case XmlModelNode model:
                EmitNullCheck(
                    code,
                    local,
                    () => EmitChildModel(code, local, model.Name),
                    model.WriteNil ? () => EmitNilElement(code, model.Name) : null);
                break;

            case XmlCollectionNode collection:
                EmitNullCheck(
                    code,
                    local,
                    () => EmitCollection(code, local, collection),
                    collection.Wrapper is { } wrapper && collection.WrapperWriteNil ? () => EmitNilElement(code, wrapper) : null);
                break;

            default:
                throw new InvalidOperationException("Unknown XML node kind.");
        }
    }

    private static void EmitCollection(CodeWriter code, string local, XmlCollectionNode collection)
    {
        if (collection.Wrapper is { } wrapper)
        {
            EmitStartElement(code, wrapper);
        }

        code.Line("foreach (var item in " + local + ")");
        code.Open();

        Action? whenAbsent = collection.ItemWriteNil ? () => EmitNilElement(code, collection.ItemName) : null;
        if (collection.ItemScalar is { } itemScalar)
        {
            EmitGuarded(code, itemScalar, "item", value => EmitScalarElement(code, collection.ItemName, Format(value, itemScalar)), whenAbsent);
        }
        else
        {
            EmitNullCheck(code, "item", () => EmitChildModel(code, "item", collection.ItemName), whenAbsent);
        }

        code.Close();

        if (collection.Wrapper is not null)
        {
            code.Line("writer.WriteEndElement();");
        }
    }

    private static void EmitScalarElement(CodeWriter code, XmlNameSpec name, string formatted)
    {
        EmitStartElement(code, name);
        code.Line("writer.WriteString(" + formatted + ");");
        code.Line("writer.WriteEndElement();");
    }

    private static void EmitChildModel(CodeWriter code, string expression, XmlNameSpec name)
    {
        code.Line(expression + ".WriteXml(writer, " + Literal(name.LocalName) + ", " + NamespaceArgument(name.Namespace) + ");");
    }

    /// <summary>The empty element XmlSerializer writes for an absent value; the writer invents the prefix, as it does for XmlSerializer.</summary>
    private static void EmitNilElement(CodeWriter code, XmlNameSpec name)
    {
        EmitStartElement(code, name);
        code.Line("writer.WriteAttributeString(\"nil\", " + Literal(XmlSchemaInstanceNamespace) + ", \"true\");");
        code.Line("writer.WriteEndElement();");
    }

    private static string DeclareLocal(CodeWriter code, string propertyName, int index)
    {
        var local = "value" + index.ToString(CultureInfo.InvariantCulture);
        code.Line("var " + local + " = this." + EscapeIdentifier(propertyName) + ";");
        return local;
    }

    /// <summary>Runs <paramref name="body"/> with the present value's expression, inside a null check when the scalar can be absent.</summary>
    private static void EmitGuarded(CodeWriter code, XmlScalarSpec scalar, string local, Action<string> body, Action? whenAbsent)
    {
        if (!scalar.IsNullable)
        {
            body(local);
            return;
        }

        if (scalar.Kind == ValueKind.String)
        {
            EmitNullCheck(code, local, () => body(local), whenAbsent);
            return;
        }

        code.Line("if (" + local + ".HasValue)");
        code.Open();
        body(local + ".Value");
        code.Close();
        EmitElse(code, whenAbsent);
    }

    private static void EmitNullCheck(CodeWriter code, string expression, Action whenPresent, Action? whenAbsent)
    {
        code.Line("if (" + expression + " is not null)");
        code.Open();
        whenPresent();
        code.Close();
        EmitElse(code, whenAbsent);
    }

    private static void EmitElse(CodeWriter code, Action? whenAbsent)
    {
        if (whenAbsent is null)
        {
            return;
        }

        code.Line("else");
        code.Open();
        whenAbsent();
        code.Close();
    }

    private static void EmitStartElement(CodeWriter code, XmlNameSpec name)
    {
        code.Line(name.Namespace is null
            ? "writer.WriteStartElement(" + Literal(name.LocalName) + ");"
            : "writer.WriteStartElement(null, " + Literal(name.LocalName) + ", " + Literal(name.Namespace) + ");");
    }

    private static string Format(string expression, XmlScalarSpec scalar)
    {
        return scalar.Kind switch
        {
            ValueKind.String => expression,
            ValueKind.DateTime => "global::System.Xml.XmlConvert.ToString(" + expression + ", global::System.Xml.XmlDateTimeSerializationMode.RoundtripKind)",
            ValueKind.DateOnly => expression + ".ToString(\"O\", global::System.Globalization.CultureInfo.InvariantCulture)",
            ValueKind.TimeOnly => expression + ".ToString(\"HH:mm:ss.FFFFFFF\", global::System.Globalization.CultureInfo.InvariantCulture)",
            ValueKind.Enum => scalar.EnumFormatter + "(" + expression + ")",
            ValueKind.XmlConvertScalar or ValueKind.DateTimeOffset or ValueKind.Guid or ValueKind.TimeSpan =>
                "global::System.Xml.XmlConvert.ToString(" + expression + ")",
            _ => throw new InvalidOperationException("Unknown XML scalar kind."),
        };
    }

    /// <summary>
    /// The text XmlSerializer writes for an enum: an exact member match first (so a composite flags member wins), then for flags
    /// the set members in declaration order separated by spaces, and an exception for a value no member covers.
    /// </summary>
    private static void EmitEnumFormatter(CodeWriter code, XmlEnumSpec spec)
    {
        var invalid = "throw new global::System.InvalidOperationException(\"Instance validation error: '\" + value.ToString() + \"' is not a valid value for " +
            spec.ShortName + ".\");";

        code.Line("private static string " + spec.FormatterName + "(" + spec.TypeName + " value)");
        code.Open();
        code.Line("switch (value)");
        code.Open();
        foreach (var member in spec.Members)
        {
            code.Line("case " + spec.TypeName + "." + EscapeIdentifier(member.MemberName) + ":");
            code.Line("    return " + Literal(member.XmlName) + ";");
        }

        if (!spec.IsFlags)
        {
            code.Line("default:");
            code.Line("    " + invalid);
            code.Close();
            code.Close();
            return;
        }

        code.Close();
        code.Line();

        string? zeroName = null;
        code.Line("var remaining = value;");
        code.Line("var builder = new global::System.Text.StringBuilder();");

        foreach (var member in spec.Members)
        {
            if (member.IsZero)
            {
                zeroName ??= member.XmlName;
                continue;
            }

            var constant = spec.TypeName + "." + EscapeIdentifier(member.MemberName);
            code.Line("if (remaining != 0 && (value & " + constant + ") == " + constant + ")");
            code.Open();
            code.Line("if (builder.Length != 0)");
            code.Open();
            code.Line("builder.Append(' ');");
            code.Close();
            code.Line();
            code.Line("builder.Append(" + Literal(member.XmlName) + ");");
            code.Line("remaining &= ~" + constant + ";");
            code.Close();
        }

        code.Line();
        code.Line("if (remaining != 0)");
        code.Open();
        code.Line(invalid);
        code.Close();
        code.Line();
        code.Line("return builder.Length != 0 ? builder.ToString() : " + Literal(zeroName ?? string.Empty) + ";");
        code.Close();
    }

    private static string NamespaceArgument(string? ns) => ns is null ? "null" : Literal(ns);

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static string EscapeIdentifier(string identifier)
    {
        return SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(identifier) != SyntaxKind.None
            ? "@" + identifier
            : identifier;
    }
}
