// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Error;

/// <summary>Error Attributes (incubating).</summary>
public static class ErrorAttributes
{
    /// <summary>A message providing more detail about an error in human-readable form..</summary>
    /// <remarks>`error.message` should provide additional context and detail about an error. It is NOT RECOMMENDED to duplicate the value of `error.type` in `error.message`. It is also NOT RECOMMENDED to duplicate the value of `exception.message` in `error.message`.  `error.message` is NOT RECOMMENDED for metrics or spans due to its unbounded cardinality and overlap with span status.</remarks>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string Message = "error.message";

}