// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Event;

/// <summary>Event Attributes (incubating).</summary>
public static class EventAttributes
{
    /// <summary>
    /// Identifies the class / type of event.
    /// </summary>
    [global::System.Obsolete("The value of this attribute MUST now be set as the value of the EventName field on the LogRecord to indicate that the LogRecord represents an Event.", false)]
    public const string Name = "event.name";
}
