/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Api_authCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Api_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Api_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Api_getConsoleLogs"];
        put?: never;
        post: operations["Api_ingestConsoleLogs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Api_getConsoleErrors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Api_liveConsole"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Api_submitFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Api_ingestSpans"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Api_liveStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Api_listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Api_getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Api_getSessionFeedback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/spans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Api_getSessionSpans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/{traceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Api_getTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Mcp_getManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/tools/call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Mcp_callTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["otlpIngest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Key-value attributes map */
        Attributes: Record<string, never>;
        /** @description Auth check response */
        AuthCheckResponse: {
            authenticated: boolean;
        };
        /** @description Console log batch */
        ConsoleIngestBatch: {
            logs: components["schemas"]["ConsoleIngestRequest"][];
        };
        /** @description Console log ingest request */
        ConsoleIngestRequest: {
            level?: string;
            message?: string;
            sessionId?: string;
            url?: string;
            stack?: string;
        };
        /**
         * @description Console log level
         * @enum {string}
         */
        ConsoleLevel: "debug" | "log" | "info" | "warn" | "error";
        /** @description Console log entry */
        ConsoleLogEntry: {
            level?: components["schemas"]["ConsoleLevel"];
            message?: string;
            sessionId?: string;
            url?: string;
            stack?: string;
            timestamp: components["schemas"]["Timestamp"];
        };
        /** @description Error response */
        ErrorResponse: {
            error: string;
            message?: string;
        };
        /** @description Feedback response (placeholder) */
        FeedbackResponse: {
            feedback: unknown[];
        };
        /** @description GenAI-specific span data (OTel semconv 1.38) */
        GenAiSpanData: {
            providerName?: string;
            operationName?: string;
            requestModel?: string;
            responseModel?: string;
            /** Format: int64 */
            inputTokens?: number;
            /** Format: int64 */
            outputTokens?: number;
            /** Format: int64 */
            totalTokens?: number;
            /** Format: double */
            costUsd?: number;
            /** Format: double */
            temperature?: number;
            /** Format: int32 */
            maxTokens?: number;
            finishReason?: string;
            toolName?: string;
            toolCallId?: string;
        };
        /** @description Health response */
        HealthResponse: {
            status: string;
        };
        /** @description Login request */
        LoginRequest: {
            token: string;
        };
        /** @description Login response */
        LoginResponse: {
            success: boolean;
            error?: string;
        };
        /** @description MCP content */
        McpContent: {
            type: string;
            text?: string;
        };
        /** @description MCP manifest */
        McpManifest: {
            name: string;
            version: string;
            description: string;
            tools: components["schemas"]["McpTool"][];
        };
        /** @description MCP response */
        McpResponse: {
            content?: components["schemas"]["McpContent"];
            error?: string;
            isError: boolean;
        };
        /** @description MCP tool definition */
        McpTool: {
            name: string;
            description: string;
            inputSchema?: unknown;
        };
        /** @description MCP tool call */
        McpToolCall: {
            name: string;
            arguments?: unknown;
        };
        /** @description AI conversation session with aggregated metrics */
        Session: {
            sessionId: components["schemas"]["SessionId"];
            startTime: components["schemas"]["Timestamp"];
            lastActivity: components["schemas"]["Timestamp"];
            /** Format: double */
            durationMs: number;
            /** Format: int64 */
            spanCount: number;
            /** Format: int64 */
            traceCount: number;
            /** Format: int64 */
            errorCount: number;
            /** Format: double */
            errorRate: number;
            services: string[];
            traceIds: string[];
            isActive?: boolean;
            genaiStats: components["schemas"]["SessionGenAiStats"];
            attributes?: components["schemas"]["Attributes"];
        };
        /** @description GenAI statistics aggregated at session level */
        SessionGenAiStats: {
            /** Format: int64 */
            totalInputTokens: number;
            /** Format: int64 */
            totalOutputTokens: number;
            /** Format: int64 */
            totalTokens: number;
            /** Format: double */
            totalCostUsd: number;
            /** Format: int64 */
            requestCount: number;
            /** Format: int64 */
            toolCallCount: number;
            models: string[];
            providers: string[];
            primaryModel?: string;
        };
        /** @description Session identifier (GUID format) */
        SessionId: string;
        /** @description Session list response */
        SessionListResponse: {
            sessions: components["schemas"]["Session"][];
            /** Format: int32 */
            total: number;
            hasMore: boolean;
        };
        /** @description OpenTelemetry span */
        Span: {
            traceId: components["schemas"]["TraceId"];
            spanId: components["schemas"]["SpanId"];
            parentSpanId?: components["schemas"]["SpanId"];
            sessionId?: components["schemas"]["SessionId"];
            name: string;
            kind: components["schemas"]["SpanKind"];
            status: components["schemas"]["SpanStatus"];
            statusMessage?: string;
            startTime: components["schemas"]["Timestamp"];
            endTime: components["schemas"]["Timestamp"];
            /** Format: double */
            durationMs: number;
            serviceName: string;
            serviceVersion?: string;
            attributes?: components["schemas"]["Attributes"];
            events?: components["schemas"]["SpanEvent"][];
            links?: components["schemas"]["SpanLink"][];
            /** @description GenAI-specific data if this is an AI span */
            genai?: components["schemas"]["GenAiSpanData"];
        };
        /** @description Span batch for ingestion */
        SpanBatch: {
            spans: components["schemas"]["Span"][];
        };
        /** @description Span event (log attached to span) */
        SpanEvent: {
            name: string;
            timestamp: components["schemas"]["Timestamp"];
            attributes?: components["schemas"]["Attributes"];
        };
        /** @description 16-character hex span ID */
        SpanId: string;
        /**
         * @description OpenTelemetry span kind
         * @enum {string}
         */
        SpanKind: "internal" | "server" | "client" | "producer" | "consumer";
        /** @description Span link (cross-trace reference) */
        SpanLink: {
            traceId: components["schemas"]["TraceId"];
            spanId: components["schemas"]["SpanId"];
            attributes?: components["schemas"]["Attributes"];
        };
        /** @description Span list response */
        SpanListResponse: {
            spans: components["schemas"]["Span"][];
        };
        /**
         * @description OpenTelemetry span status
         * @enum {string}
         */
        SpanStatus: "unset" | "ok" | "error";
        /** @description SSE connected event */
        SseConnectedEvent: {
            connectionId: string;
        };
        /** @description SSE error data */
        SseErrorData: {
            errorType: string;
            message: string;
        };
        /** @description Storage statistics */
        StorageStats: {
            /** Format: int64 */
            spanCount: number;
            /** Format: int64 */
            sessionCount: number;
            /** Format: int64 */
            feedbackCount: number;
            oldestSpan?: components["schemas"]["Timestamp"];
            newestSpan?: components["schemas"]["Timestamp"];
        };
        /** @description ISO 8601 timestamp */
        Timestamp: string;
        /** @description 32-character hex trace ID (OTel W3C format) */
        TraceId: string;
        /** @description Trace response with hierarchy */
        TraceResponse: {
            traceId?: components["schemas"]["TraceId"];
            spans: components["schemas"]["Span"][];
            rootSpan?: components["schemas"]["Span"];
            /** Format: double */
            durationMs?: number;
            status?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Api_authCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthCheckResponse"];
                };
            };
        };
    };
    Api_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    Api_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    Api_getConsoleLogs: {
        parameters: {
            query?: {
                session?: string;
                level?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsoleLogEntry"][];
                };
            };
        };
    };
    Api_ingestConsoleLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsoleIngestBatch"];
            };
        };
        responses: {
            /** @description The request has been accepted for processing, but processing has not yet completed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Api_getConsoleErrors: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsoleLogEntry"][];
                };
            };
        };
    };
    Api_liveConsole: {
        parameters: {
            query?: {
                session?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SseConnectedEvent"];
                };
            };
        };
    };
    Api_submitFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has been accepted for processing, but processing has not yet completed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Api_ingestSpans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpanBatch"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request has been accepted for processing, but processing has not yet completed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Api_liveStream: {
        parameters: {
            query?: {
                session?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SseConnectedEvent"];
                };
            };
        };
    };
    Api_listSessions: {
        parameters: {
            query?: {
                limit?: number;
                serviceName?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
        };
    };
    Api_getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["schemas"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Api_getSessionFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["schemas"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
        };
    };
    Api_getSessionSpans: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["schemas"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpanListResponse"];
                };
            };
        };
    };
    Api_getTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                traceId: components["schemas"]["TraceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    Mcp_getManifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpManifest"];
                };
            };
        };
    };
    Mcp_callTool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["McpToolCall"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpResponse"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    otlpIngest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request has been accepted for processing, but processing has not yet completed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
