// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@7fe537301d17919af7d7eb65b32e9be35da2c497
// Schema: https://opentelemetry.io/schemas/1.40.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Nfs;

/// <summary>Nfs Attributes (incubating).</summary>
public static class NfsAttributes
{
    /// <summary>NFSv4+ operation name..</summary>
    public const string OperationName = "nfs.operation.name";

    /// <summary>Linux: one of "hit" (NFSD_STATS_RC_HITS), "miss" (NFSD_STATS_RC_MISSES), or "nocache" (NFSD_STATS_RC_NOCACHE -- uncacheable).</summary>
    public const string ServerRepcacheStatus = "nfs.server.repcache.status";

}