// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@7fe537301d17919af7d7eb65b32e9be35da2c497
// Schema: https://opentelemetry.io/schemas/1.40.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Http;

/// <summary>Http Attributes (incubating).</summary>
public static class HttpAttributes
{
    /// <summary>Deprecated, use `client.address` instead..</summary>
    [global::System.Obsolete("Replaced by client.address.", false)]
    public const string ClientIp = "http.client_ip";

    /// <summary>State of the HTTP connection in the HTTP connection pool..</summary>
    public const string ConnectionState = "http.connection.state";

    /// <summary>Values for the <c>ConnectionState</c> attribute.</summary>
    public static class ConnectionStateValues
    {
        /// <summary>active state..</summary>
        public const string Active = "active";
        /// <summary>idle state..</summary>
        public const string Idle = "idle";
    }

    /// <summary>Deprecated, use `network.protocol.name` and `network.protocol.version` instead..</summary>
    [global::System.Obsolete("Split into `network.protocol.name` and `network.protocol.version`", false)]
    public const string Flavor = "http.flavor";

    /// <summary>Values for the <c>Flavor</c> attribute.</summary>
    public static class FlavorValues
    {
        /// <summary>HTTP/1.0.</summary>
        public const string Http10 = "1.0";
        /// <summary>HTTP/1.1.</summary>
        public const string Http11 = "1.1";
        /// <summary>HTTP/2.</summary>
        public const string Http20 = "2.0";
        /// <summary>HTTP/3.</summary>
        public const string Http30 = "3.0";
        /// <summary>QUIC protocol..</summary>
        public const string Quic = "QUIC";
        /// <summary>SPDY protocol..</summary>
        public const string Spdy = "SPDY";
    }

    /// <summary>Deprecated, use one of `server.address`, `client.address` or `http.request.header.host` instead, depending on the usage..</summary>
    [global::System.Obsolete("Replaced by one of `server.address`, `client.address` or `http.request.header.host`, depending on the usage.", false)]
    public const string Host = "http.host";

    /// <summary>Deprecated, use `http.request.method` instead..</summary>
    [global::System.Obsolete("Replaced by http.request.method.", false)]
    public const string Method = "http.method";

    /// <summary>The size of the request payload body in bytes. This is the number of bytes transferred excluding headers and is often, but not always, present as the [Content-Length](https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length) header. For requests using transport encoding, this should be the compressed size..</summary>
    public const string RequestBodySize = "http.request.body.size";

    /// <summary>The total size of the request in bytes. This should be the total number of bytes sent over the wire, including the request line (HTTP/1.1), framing (HTTP/2 and HTTP/3), headers, and request body if any..</summary>
    public const string RequestSize = "http.request.size";

    /// <summary>Deprecated, use `http.request.header.content-length` instead..</summary>
    [global::System.Obsolete("Replaced by `http.request.header.content-length`.", false)]
    public const string RequestContentLength = "http.request_content_length";

    /// <summary>Deprecated, use `http.request.body.size` instead..</summary>
    [global::System.Obsolete("Replaced by http.request.body.size.", false)]
    public const string RequestContentLengthUncompressed = "http.request_content_length_uncompressed";

    /// <summary>The size of the response payload body in bytes. This is the number of bytes transferred excluding headers and is often, but not always, present as the [Content-Length](https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length) header. For requests using transport encoding, this should be the compressed size..</summary>
    public const string ResponseBodySize = "http.response.body.size";

    /// <summary>The total size of the response in bytes. This should be the total number of bytes sent over the wire, including the status line (HTTP/1.1), framing (HTTP/2 and HTTP/3), headers, and response body and trailers if any..</summary>
    public const string ResponseSize = "http.response.size";

    /// <summary>Deprecated, use `http.response.header.content-length` instead..</summary>
    [global::System.Obsolete("Replaced by `http.response.header.content-length`.", false)]
    public const string ResponseContentLength = "http.response_content_length";

    /// <summary>Deprecated, use `http.response.body.size` instead..</summary>
    [global::System.Obsolete("Replaced by http.response.body.size.", false)]
    public const string ResponseContentLengthUncompressed = "http.response_content_length_uncompressed";

    /// <summary>Deprecated, use `url.scheme` instead..</summary>
    [global::System.Obsolete("Replaced by url.scheme.", false)]
    public const string Scheme = "http.scheme";

    /// <summary>Deprecated, use `server.address` instead..</summary>
    [global::System.Obsolete("Replaced by server.address.", false)]
    public const string ServerName = "http.server_name";

    /// <summary>Deprecated, use `http.response.status_code` instead..</summary>
    [global::System.Obsolete("Replaced by http.response.status_code.", false)]
    public const string StatusCode = "http.status_code";

    /// <summary>Deprecated, use `url.path` and `url.query` instead..</summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string Target = "http.target";

    /// <summary>Deprecated, use `url.full` instead..</summary>
    [global::System.Obsolete("Replaced by url.full.", false)]
    public const string Url = "http.url";

    /// <summary>Deprecated, use `user_agent.original` instead..</summary>
    [global::System.Obsolete("Replaced by user_agent.original.", false)]
    public const string UserAgent = "http.user_agent";

}