// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@7fe537301d17919af7d7eb65b32e9be35da2c497
// Schema: https://opentelemetry.io/schemas/1.40.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Mainframe;

/// <summary>Mainframe Attributes (incubating).</summary>
public static class MainframeAttributes
{
    /// <summary>Name of the logical partition that hosts a systems with a mainframe operating system..</summary>
    public const string LparName = "mainframe.lpar.name";

}