<Project Sdk="Microsoft.NET.Sdk.Web">
    <Import Project="../../packages/Qyl.Api.Sdk/Sdk/Sdk.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <RootNamespace>Qyl.Sample</RootNamespace>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <Import Project="../../packages/Qyl.Api.Sdk/Sdk/Sdk.targets" />
</Project>
