using System.Text;
using Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Extractors;
using Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Models;

namespace Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Emitters;

/// <summary>
/// Emits typed <c>System.Diagnostics.Activity</c> setter extensions for every
/// semconv attribute matching the marker's prefix. Each setter calls
/// <c>Activity.SetTag(string, object?)</c> with the registry-defined key and
/// the correctly-typed value.
///
/// Stability is propagated per-attribute only for <c>stability: deprecated</c>,
/// which projects to <c>[Obsolete]</c>. This matches contrib, Java, and Python
/// upstream generators, which carry no per-symbol annotation for non-stable
/// tiers — stable/incubating separation is handled at the Weaver-template/
/// registry-filter layer, not the symbol layer. For <c>template[...]</c>
/// attributes the setter takes a <c>string segment</c> parameter to compose
/// the runtime key. For enum-typed attributes the registry's enum values are
/// emitted as a nested static class of <c>const string</c>s so call sites are
/// discoverable (e.g.
/// <c>activity.SetHttpRequestMethod(HttpActivityExtensions.HttpRequestMethodValues.Get)</c>).
///
/// Audit (pinned-goal directive, Phase B-2): this emitter writes thin
/// extension methods on a consumer-provided <c>Activity</c>
/// (<c>this Activity activity</c>) that forward to <c>Activity.SetTag</c>.
/// No generated <c>ActivitySource</c> singletons, no
/// <c>private static readonly ActivitySource ... = new ActivitySource(...)</c>.
/// Consumers own the <c>ActivitySource</c>/<c>Activity</c> lifecycle; the
/// generator only provides typed setters over the BCL surface.
/// </summary>
internal static class ActivityExtensionsEmitter
{
    public static FileWithName Generate(ActivitiesMarkerModel marker, ActivityRegistryModel registry)
    {
        var attributes = FilterByPrefix(registry, marker.Prefix, marker.Filter);

        var builder = new StringBuilder();
        WriteHeader(builder);
        WriteNamespace(builder, marker.ContainingNamespace);
        WriteClass(builder, marker.ClassName, attributes, marker.Filter);

        return new FileWithName($"{marker.ClassName}.g.cs", builder.ToString());
    }

    private static List<ActivityAttributeModel> FilterByPrefix(ActivityRegistryModel registry, string prefix, StabilityFilter filter)
    {
        var result = new List<ActivityAttributeModel>();
        foreach (var attr in registry.Attributes)
        {
            if (!PrefixMatches(attr.Key, prefix))
                continue;

            // Stability gate. Deprecated rows survive every projection until
            // upstream drops them (contrib/Java/Python parity): the
            // [Obsolete] symbol stays so consumers can migrate at their pace.
            if (!StabilityFiltering.IsIncludedOrDeprecated(attr.Stability, attr.Deprecated, filter))
                continue;

            result.Add(attr);
        }
        result.Sort(static (a, b) => StringComparer.Ordinal.Compare(a.Key, b.Key));
        return result;
    }

    private static bool PrefixMatches(string key, string prefix)
    {
        if (string.Equals(key, prefix, StringComparison.Ordinal)) return true;
        if (key.Length <= prefix.Length) return false;
        if (!key.StartsWith(prefix, StringComparison.Ordinal)) return false;
        return key[prefix.Length] == '.';
    }

    private static void WriteHeader(StringBuilder builder)
    {
        builder.AppendLine("// <auto-generated>This file has been auto generated from 'Qyl.OpenTelemetry.SemanticConventions.SourceGeneration'.</auto-generated>");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("#pragma warning disable CS1570 // XML comment has badly formed XML");
        builder.AppendLine();
    }

    private static void WriteNamespace(StringBuilder builder, string ns)
    {
        if (!string.IsNullOrEmpty(ns))
        {
            builder.Append("namespace ").Append(ns).AppendLine(";");
            builder.AppendLine();
        }
    }

    private static void WriteClass(
        StringBuilder builder,
        string className,
        List<ActivityAttributeModel> attributes,
        StabilityFilter filter)
    {
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Typed setter extensions for OpenTelemetry semantic-convention attributes on a span.");
        builder.AppendLine("/// Each method invokes <c>global::System.Diagnostics.Activity.SetTag</c> with the");
        builder.AppendLine("/// registry-defined key and a strongly-typed value.");
        builder.AppendLine("/// </summary>");
        builder.Append("static partial class ").AppendLine(className);
        builder.AppendLine("{");

        var first = true;
        foreach (var attr in attributes)
        {
            if (!first) builder.AppendLine();
            first = false;
            WriteSetter(builder, attr);
        }

        foreach (var attr in attributes)
        {
            if (!attr.IsEnum) continue;
            builder.AppendLine();
            WriteEnumValueClass(builder, attr, filter);
        }

        builder.AppendLine("}");
    }

    private static void WriteSetter(StringBuilder builder, ActivityAttributeModel attr)
    {
        WriteSummaryComment(builder, attr.Brief, indent: 4);
        WriteStabilityAttribute(builder, attr, indent: 4);

        var methodName = "Set" + ToPascalCase(attr.Key);
        var parameterType = attr.CSharpParameterType;

        if (attr.IsTemplate)
        {
            builder.Append("    public static global::System.Diagnostics.Activity ")
                   .Append(methodName).AppendLine("(");
            builder.AppendLine("        this global::System.Diagnostics.Activity activity,");
            builder.AppendLine("        string segment,");
            builder.Append("        ").Append(parameterType).AppendLine(" value)");
            builder.Append("        => activity.SetTag($\"").Append(attr.Key).AppendLine(".{segment}\", value);");
        }
        else
        {
            builder.Append("    public static global::System.Diagnostics.Activity ")
                   .Append(methodName).AppendLine("(");
            builder.AppendLine("        this global::System.Diagnostics.Activity activity,");
            builder.Append("        ").Append(parameterType).AppendLine(" value)");
            builder.Append("        => activity.SetTag(\"").Append(attr.Key).AppendLine("\", value);");
        }
    }

    private static void WriteEnumValueClass(StringBuilder builder, ActivityAttributeModel attr, StabilityFilter filter)
    {
        WriteSummaryComment(builder, attr.Brief, indent: 4);
        WriteStabilityAttribute(builder, attr, indent: 4);

        var enumClassName = ToPascalCase(attr.Key) + "Values";
        builder.Append("    public static class ").AppendLine(enumClassName);
        builder.AppendLine("    {");

        var first = true;
        foreach (var member in attr.EnumMembers)
        {
            if (!StabilityFiltering.IsIncludedOrDeprecated(member.Stability, member.Deprecated ?? attr.Deprecated, filter))
                continue;

            if (!first) builder.AppendLine();
            first = false;
            WriteEnumMember(builder, member);
        }

        builder.AppendLine("    }");
    }

    private static void WriteEnumMember(StringBuilder builder, EnumMemberModel member)
    {
        var brief = string.IsNullOrEmpty(member.Brief) ? member.Id + "." : member.Brief;
        WriteSummaryComment(builder, brief, indent: 8);

        if (member.Deprecated is not null)
        {
            var msg = member.Deprecated switch
            {
                DeprecatedModel.Renamed r => $"Replaced by {r.RenamedTo}.",
                DeprecatedModel.Obsoleted => "Removed, no replacement.",
                DeprecatedModel.Uncategorized u => string.IsNullOrEmpty(u.Note) ? "Deprecated." : u.Note,
                _ => "Deprecated."
            };
            builder.Append("        [global::System.Obsolete(\"")
                   .Append(EscapeForAttribute(msg)).AppendLine("\")]");
        }

        var memberName = ToPascalCase(member.Id);
        builder.Append("        public const string ").Append(memberName)
               .Append(" = \"").Append(member.Value).AppendLine("\";");
    }

    private static void WriteStabilityAttribute(StringBuilder builder, ActivityAttributeModel attr, int indent)
    {
        if (attr.Stability != StabilityModel.Deprecated && attr.Deprecated is null) return;

        var pad = new string(' ', indent);
        var message = attr.Deprecated switch
        {
            DeprecatedModel.Renamed r => $"Replaced by {r.RenamedTo}.",
            DeprecatedModel.Obsoleted => "Removed, no replacement.",
            DeprecatedModel.Uncategorized u => string.IsNullOrEmpty(u.Note) ? "Deprecated." : u.Note,
            null => "Deprecated.",
            _ => "Deprecated."
        };
        builder.Append(pad).Append("[global::System.Obsolete(\"")
               .Append(EscapeForAttribute(message)).AppendLine("\")]");
    }

    private static void WriteSummaryComment(StringBuilder builder, string text, int indent)
    {
        var pad = new string(' ', indent);
        builder.Append(pad).AppendLine("/// <summary>");
        foreach (var line in SplitLines(text))
        {
            builder.Append(pad).Append("/// ").AppendLine(line);
        }
        builder.Append(pad).AppendLine("/// </summary>");
    }

    internal static string ToPascalCase(string value)
    {
        if (string.IsNullOrEmpty(value)) return string.Empty;
        var builder = new StringBuilder(value.Length);
        var upperNext = true;
        foreach (var ch in value)
        {
            if (ch is '.' or '_' or '-' or ' ')
            {
                upperNext = true;
                continue;
            }
            if (upperNext)
            {
                builder.Append(char.ToUpperInvariant(ch));
                upperNext = false;
            }
            else
            {
                builder.Append(ch);
            }
        }
        return builder.ToString();
    }

    private static IEnumerable<string> SplitLines(string text)
    {
        if (string.IsNullOrEmpty(text)) yield break;
        foreach (var line in text.Split('\n'))
            yield return line.TrimEnd('\r');
    }

    private static string EscapeForAttribute(string text)
        => text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", " ").Replace("\r", string.Empty);
}
