using System.Text;
using Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Extractors;
using Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Models;

namespace Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Emitters;

/// <summary>
/// Emits the source file completing a partial class marked with
/// <c>[SemanticConventionEvents("&lt;prefix&gt;")]</c>.
///
/// For each event group whose <c>event_name</c> starts with the requested prefix the emitter
/// produces:
/// <list type="bullet">
///   <item><description>A <c>public const string Event&lt;PascalName&gt; = "&lt;event.name&gt;";</c> constant.</description></item>
///   <item><description>A <c>public readonly record struct &lt;PascalName&gt;Payload</c> whose properties
///         project the event's payload attributes (required attributes first, non-nullable;
///         recommended attributes after, nullable).</description></item>
/// </list>
/// </summary>
internal static class EventsEmitter
{
    // Event-emission target audit (semconv v1.41.0):
    // The resolved-registry event schema carries only { event_name, brief, deprecated,
    // stability, payload[] } — there is NO discriminator field (no event_type / kind /
    // body / event_body) that distinguishes ActivityEvent-targeted events from
    // LogRecord/Event-emitter-targeted events. All v1.41.0 event rows therefore emit
    // the same payload-struct shape and the caller picks the emission API at use-site.
    //
    // If upstream introduces a discriminator (tracked on
    // open-telemetry/semantic-conventions board #74 view 4), gate the emit shape here
    // by reading the new field on EventGroupModel and branching the WritePayloadStruct
    // output (e.g. add a `static OtelEventTarget Target => ...` constant on the
    // emitted struct). The marker library stays target-agnostic until then.

    public static FileWithName Generate(EventsMarkerModel marker, InstrumentRegistryModel instruments)
    {
        var events = ResolveEvents(instruments, marker.Prefix, marker.Filter);

        var builder = new StringBuilder();
        WriteHeader(builder);
        WriteNamespace(builder, marker.ContainingNamespace);
        WriteClass(builder, marker.ClassName, events);

        var fileName = $"{marker.ClassName}.g.cs";
        return new FileWithName(fileName, builder.ToString());
    }

    private static List<EventGroupModel> ResolveEvents(InstrumentRegistryModel instruments, string prefix, StabilityFilter filter)
    {
        // Stability gating mirrors the contrib/Java/Python "stable package" vs "incubating
        // package" split — same semantics as MetricsEmitter.ResolveMetrics. Deprecated rows
        // stay emitted (with [Obsolete]) under whichever stability tier owns them, per
        // OTel telemetry-stability.md.
        var dotted = prefix + ".";
        var matched = new List<EventGroupModel>();
        foreach (var ev in instruments.Events)
        {
            if (!string.Equals(ev.EventName, prefix, StringComparison.Ordinal) &&
                !ev.EventName.StartsWith(dotted, StringComparison.Ordinal))
            {
                continue;
            }

            if (!StabilityFiltering.IsIncludedOrDeprecated(ev.Stability, ev.Deprecated, filter))
            {
                continue;
            }

            matched.Add(ev);
        }
        matched.Sort(static (a, b) => StringComparer.Ordinal.Compare(a.EventName, b.EventName));
        return matched;
    }

    private static void WriteHeader(StringBuilder builder)
    {
        builder.AppendLine("// <auto-generated>This file has been auto generated from 'Qyl.OpenTelemetry.SemanticConventions.SourceGeneration'.</auto-generated>");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("#pragma warning disable CS1570 // XML comment has badly formed XML");
        builder.AppendLine();
    }

    private static void WriteNamespace(StringBuilder builder, string ns)
    {
        if (!string.IsNullOrEmpty(ns))
        {
            builder.Append("namespace ").Append(ns).AppendLine(";");
            builder.AppendLine();
        }
    }

    private static void WriteClass(StringBuilder builder, string className, List<EventGroupModel> events)
    {
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Constants for event names and typed payload structs outlined by the OpenTelemetry specifications.");
        builder.AppendLine("/// </summary>");
        builder.Append("static partial class ").AppendLine(className);
        builder.AppendLine("{");

        var first = true;
        foreach (var ev in events)
        {
            if (!first) builder.AppendLine();
            first = false;
            WriteEventConstant(builder, ev);
        }

        foreach (var ev in events)
        {
            builder.AppendLine();
            WritePayloadStruct(builder, ev);
        }

        builder.AppendLine("}");
    }

    private static void WriteEventConstant(StringBuilder builder, EventGroupModel ev)
    {
        WriteSummaryComment(builder, ev.Brief, indent: 4);
        WriteObsolete(builder, ev.Deprecated, indent: 4);

        var memberName = EventMemberName(ev.EventName);
        builder.Append("    public const string ").Append(memberName)
               .Append(" = \"").Append(ev.EventName).AppendLine("\";");
    }

    private static void WritePayloadStruct(StringBuilder builder, EventGroupModel ev)
    {
        var ordered = OrderPayload(ev.Payload);

        WriteSummaryComment(builder, ev.Brief, indent: 4);
        WriteObsolete(builder, ev.Deprecated, indent: 4);

        var structName = PayloadStructName(ev.EventName);
        builder.Append("    public readonly record struct ").AppendLine(structName);
        builder.AppendLine("    {");

        var first = true;
        foreach (var member in ordered)
        {
            if (!first) builder.AppendLine();
            first = false;
            WritePayloadProperty(builder, member);
        }

        builder.AppendLine("    }");
    }

    private static List<EventAttributeModel> OrderPayload(EquatableArray<EventAttributeModel> payload)
    {
        var required = new List<EventAttributeModel>();
        var recommended = new List<EventAttributeModel>();
        foreach (var member in payload)
        {
            if (member.Required) required.Add(member);
            else recommended.Add(member);
        }
        required.Sort(static (a, b) => StringComparer.Ordinal.Compare(a.Key, b.Key));
        recommended.Sort(static (a, b) => StringComparer.Ordinal.Compare(a.Key, b.Key));
        required.AddRange(recommended);
        return required;
    }

    private static void WritePayloadProperty(StringBuilder builder, EventAttributeModel member)
    {
        WriteSummaryComment(builder, member.Brief, indent: 8);

        var propertyType = PropertyTypeName(member.Type, member.Required);
        var propertyName = PropertyName(member.Key);
        builder.Append("        public ").Append(propertyType).Append(' ')
               .Append(propertyName).AppendLine(" { get; init; }");
    }

    private static void WriteSummaryComment(StringBuilder builder, string text, int indent)
    {
        var pad = new string(' ', indent);
        builder.Append(pad).AppendLine("/// <summary>");
        foreach (var line in SplitLines(text))
        {
            builder.Append(pad).Append("/// ").AppendLine(line);
        }
        builder.Append(pad).AppendLine("/// </summary>");
    }

    private static void WriteObsolete(StringBuilder builder, DeprecatedModel? deprecated, int indent)
    {
        if (deprecated is null) return;

        var pad = new string(' ', indent);
        var message = deprecated switch
        {
            DeprecatedModel.Renamed r => $"Replaced by {r.RenamedTo}.",
            DeprecatedModel.Obsoleted => "Removed, no replacement.",
            DeprecatedModel.Uncategorized u => string.IsNullOrEmpty(u.Note) ? "Deprecated." : u.Note,
            _ => "Deprecated."
        };
        builder.Append(pad).Append("[global::System.Obsolete(\"")
               .Append(EscapeForAttribute(message)).AppendLine("\")]");
    }

    internal static string EventMemberName(string eventName) => "Event" + ToPascalCase(eventName);

    internal static string PayloadStructName(string eventName) => ToPascalCase(eventName) + "Payload";

    internal static string PropertyName(string attributeKey) => ToPascalCase(attributeKey);

    private static string PropertyTypeName(AttributeTypeModel type, bool required)
    {
        var baseType = type switch
        {
            AttributeTypeModel.Primitive p => MapPrimitive(p.Name),
            AttributeTypeModel.Template => "string",
            AttributeTypeModel.EnumType => "string",
            _ => "string"
        };

        return required ? baseType : baseType + "?";
    }

    private static string MapPrimitive(string name) => name switch
    {
        "string" => "string",
        "int" => "long",
        "double" => "double",
        "boolean" => "bool",
        "string[]" => "global::System.Collections.Generic.IReadOnlyList<string>",
        "int[]" => "global::System.Collections.Generic.IReadOnlyList<long>",
        "double[]" => "global::System.Collections.Generic.IReadOnlyList<double>",
        "boolean[]" => "global::System.Collections.Generic.IReadOnlyList<bool>",
        _ => "string"
    };

    internal static string ToPascalCase(string value)
    {
        if (string.IsNullOrEmpty(value)) return string.Empty;

        var builder = new StringBuilder(value.Length);
        var upperNext = true;
        foreach (var ch in value)
        {
            if (ch is '.' or '_' or '-' or ' ')
            {
                upperNext = true;
                continue;
            }

            if (upperNext)
            {
                builder.Append(char.ToUpperInvariant(ch));
                upperNext = false;
            }
            else
            {
                builder.Append(ch);
            }
        }
        return builder.ToString();
    }

    private static IEnumerable<string> SplitLines(string text)
    {
        if (string.IsNullOrEmpty(text)) yield break;

        foreach (var line in text.Split('\n'))
        {
            yield return line.TrimEnd('\r');
        }
    }

    private static string EscapeForAttribute(string text)
        => text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", " ").Replace("\r", string.Empty);
}
