using System.Text;
using Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Extractors;
using Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Models;

namespace Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Emitters;

/// <summary>
/// Emits the source file completing a partial class marked with
/// <c>[SemanticConventionMetrics("&lt;prefix&gt;")]</c>.
///
/// For each metric group whose <c>metric_name</c> starts with the requested prefix the emitter
/// produces:
/// <list type="bullet">
///   <item><description>A <c>public const string Metric&lt;PascalName&gt; = "&lt;metric.name&gt;";</c> constant.</description></item>
///   <item><description>A <c>public static partial class &lt;PascalName&gt;Descriptor</c> carrying
///         <c>Name</c>, <c>Unit</c>, <c>Instrument</c>, and <c>Brief</c> constants.</description></item>
/// </list>
/// </summary>
internal static class MetricsEmitter
{
    public static FileWithName Generate(MetricsMarkerModel marker, InstrumentRegistryModel instruments)
    {
        var metrics = ResolveMetrics(instruments, marker.Prefix, marker.Filter);

        var builder = new StringBuilder();
        WriteHeader(builder);
        WriteNamespace(builder, marker.ContainingNamespace);
        WriteClass(builder, marker.ClassName, metrics);

        var fileName = $"{marker.ClassName}.g.cs";
        return new FileWithName(fileName, builder.ToString());
    }

    private static List<MetricGroupModel> ResolveMetrics(InstrumentRegistryModel instruments, string prefix, StabilityFilter filter)
    {
        // Stability gating mirrors the contrib/Java/Python "stable package" vs "incubating
        // package" split: under StableOnly we emit only stability=stable rows, under
        // AllStabilities we emit every row (stable + development + release_candidate + ...).
        // Per OTel telemetry-stability.md, deprecated rows stay emitted (with [Obsolete])
        // until upstream drops them — DeprecatedModel is orthogonal to StabilityModel here,
        // so a stable+deprecated row stays under StableOnly while a development+deprecated
        // row only appears under AllStabilities.
        var dotted = prefix + ".";
        var matched = new List<MetricGroupModel>();
        foreach (var metric in instruments.Metrics)
        {
            if (!string.Equals(metric.MetricName, prefix, StringComparison.Ordinal) &&
                !metric.MetricName.StartsWith(dotted, StringComparison.Ordinal))
            {
                continue;
            }

            if (!StabilityFiltering.IsIncluded(metric.Stability, filter))
            {
                continue;
            }

            matched.Add(metric);
        }
        matched.Sort(static (a, b) => StringComparer.Ordinal.Compare(a.MetricName, b.MetricName));
        return matched;
    }

    private static void WriteHeader(StringBuilder builder)
    {
        builder.AppendLine("// <auto-generated>This file has been auto generated from 'Qyl.OpenTelemetry.SemanticConventions.SourceGeneration'.</auto-generated>");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("#pragma warning disable CS1570 // XML comment has badly formed XML");
        builder.AppendLine();
    }

    private static void WriteNamespace(StringBuilder builder, string ns)
    {
        if (!string.IsNullOrEmpty(ns))
        {
            builder.Append("namespace ").Append(ns).AppendLine(";");
            builder.AppendLine();
        }
    }

    private static void WriteClass(StringBuilder builder, string className, List<MetricGroupModel> metrics)
    {
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Constants for metric names and descriptors outlined by the OpenTelemetry specifications.");
        builder.AppendLine("/// </summary>");
        builder.Append("static partial class ").AppendLine(className);
        builder.AppendLine("{");

        var first = true;
        foreach (var metric in metrics)
        {
            if (!first) builder.AppendLine();
            first = false;
            WriteMetricConstant(builder, metric);
        }

        foreach (var metric in metrics)
        {
            builder.AppendLine();
            WriteDescriptorClass(builder, metric);
        }

        builder.AppendLine("}");
    }

    private static void WriteMetricConstant(StringBuilder builder, MetricGroupModel metric)
    {
        WriteSummaryComment(builder, metric.Brief, indent: 4);
        WriteObsolete(builder, metric.Deprecated, indent: 4);

        var memberName = MetricMemberName(metric.MetricName);
        builder.Append("    public const string ").Append(memberName)
               .Append(" = \"").Append(metric.MetricName).AppendLine("\";");
    }

    private static void WriteDescriptorClass(StringBuilder builder, MetricGroupModel metric)
    {
        WriteSummaryComment(builder, metric.Brief, indent: 4);
        WriteObsolete(builder, metric.Deprecated, indent: 4);

        var descriptorName = DescriptorClassName(metric.MetricName);
        builder.Append("    public static partial class ").AppendLine(descriptorName);
        builder.AppendLine("    {");
        builder.Append("        public const string Name = \"").Append(metric.MetricName).AppendLine("\";");
        builder.Append("        public const string Unit = \"").Append(EscapeForLiteral(metric.Unit)).AppendLine("\";");
        builder.Append("        public const string Instrument = \"").Append(EscapeForLiteral(metric.Instrument)).AppendLine("\";");
        builder.Append("        public const string Brief = \"").Append(EscapeForLiteral(metric.Brief)).AppendLine("\";");
        builder.AppendLine("    }");
    }

    private static void WriteSummaryComment(StringBuilder builder, string text, int indent)
    {
        var pad = new string(' ', indent);
        builder.Append(pad).AppendLine("/// <summary>");
        foreach (var line in SplitLines(text))
        {
            builder.Append(pad).Append("/// ").AppendLine(line);
        }
        builder.Append(pad).AppendLine("/// </summary>");
    }

    private static void WriteObsolete(StringBuilder builder, DeprecatedModel? deprecated, int indent)
    {
        if (deprecated is null) return;

        var pad = new string(' ', indent);
        var message = deprecated switch
        {
            DeprecatedModel.Renamed r => $"Replaced by {r.RenamedTo}.",
            DeprecatedModel.Obsoleted => "Removed, no replacement.",
            DeprecatedModel.Uncategorized u => string.IsNullOrEmpty(u.Note) ? "Deprecated." : u.Note,
            _ => "Deprecated."
        };
        builder.Append(pad).Append("[global::System.Obsolete(\"")
               .Append(EscapeForAttribute(message)).AppendLine("\")]");
    }

    internal static string MetricMemberName(string metricName) => "Metric" + ToPascalCase(metricName);

    internal static string DescriptorClassName(string metricName) => ToPascalCase(metricName) + "Descriptor";

    internal static string ToPascalCase(string value)
    {
        if (string.IsNullOrEmpty(value)) return string.Empty;

        var builder = new StringBuilder(value.Length);
        var upperNext = true;
        foreach (var ch in value)
        {
            if (ch is '.' or '_' or '-' or ' ')
            {
                upperNext = true;
                continue;
            }

            if (upperNext)
            {
                builder.Append(char.ToUpperInvariant(ch));
                upperNext = false;
            }
            else
            {
                builder.Append(ch);
            }
        }
        return builder.ToString();
    }

    private static IEnumerable<string> SplitLines(string text)
    {
        if (string.IsNullOrEmpty(text)) yield break;

        foreach (var line in text.Split('\n'))
        {
            yield return line.TrimEnd('\r');
        }
    }

    private static string EscapeForLiteral(string text)
        => text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", string.Empty);

    private static string EscapeForAttribute(string text)
        => text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", " ").Replace("\r", string.Empty);
}
