
namespace Qyl.Collector.Storage.Generators;

internal static class DuckDbEmitter
{
    public static string Emit(DuckDbTableInfo table)
    {
        var sb = new StringBuilder(4096);

        sb.AppendLine("""
                      // <auto-generated/>
                      // DuckDB helpers for type-safe parameter binding and reader mapping

                      #nullable enable

                      using System;
                      using System.Data.Common;
                      using System.Runtime.CompilerServices;
                      using System.Text;
                      using DuckDB.NET.Data;
                      """);

        sb.Append("namespace ").Append(table.Namespace).AppendLine(";");
        sb.AppendLine();

        sb.Append("partial ").Append(table.TypeKind).Append(' ').AppendLine(table.TypeName);
        sb.AppendLine("{");

        var insertColumns = table.Columns.Where(static c => !c.ExcludeFromInsert).ToArray();

        EmitColumnList(sb, table.TableName, insertColumns);

        sb.Append("    public const int ColumnCount = ").Append(insertColumns.Length).AppendLine(";");
        sb.AppendLine();

        EmitAddParameters(sb, table.TypeName, insertColumns);

        EmitMapFromReader(sb, table, [.. table.Columns]);

        EmitBuildMultiRowInsertSql(sb, table);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitColumnList(StringBuilder sb, string tableName, DuckDbColumnInfo[] columns)
    {
        sb.Append("    public const string TableName = \"").Append(tableName).AppendLine("\";");
        sb.AppendLine();

        sb.AppendLine("    public const string ColumnList = \"\"\"");
        sb.Append("        ");
        for (var i = 0; i < columns.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
                if (i % 4 is 0)
                {
                    sb.AppendLine();
                    sb.Append("        ");
                }
            }

            sb.Append(SqlIdentifier.Quote(columns[i].ColumnName));
        }

        sb.AppendLine();
        sb.AppendLine("        \"\"\";");
        sb.AppendLine();
    }

    private static void EmitAddParameters(StringBuilder sb, string typeName, IEnumerable<DuckDbColumnInfo> columns)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds parameters for INSERT in column order.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("    public static void AddParameters(DuckDBCommand cmd, ").Append(typeName).AppendLine(" row)");
        sb.AppendLine("    {");

        foreach (var col in columns)
        {
            EmitParameterAdd(sb, col);
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitParameterAdd(StringBuilder sb, DuckDbColumnInfo col)
    {
        sb.Append("        cmd.Parameters.Add(new DuckDBParameter { Value = ");

        var valueExpr = $"row.{col.PropertyName}";

        if (col.IsUBigInt)
        {
            if (col.IsNullable)
            {
                sb.Append(valueExpr).Append(".HasValue ? (object)(decimal)").Append(valueExpr)
                    .Append(".Value : DBNull.Value");
            }
            else
            {
                sb.Append("(decimal)").Append(valueExpr);
            }
        }
        else if (col.IsNullable)
        {
            sb.Append(valueExpr).Append(" ?? (object)DBNull.Value");
        }
        else
        {
            sb.Append(valueExpr);
        }

        sb.AppendLine(" });");
    }

    private static void EmitMapFromReader(StringBuilder sb, DuckDbTableInfo table,
        IReadOnlyList<DuckDbColumnInfo> columns)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps a DbDataReader row to the type using ordinal-based access.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("    public static ").Append(table.TypeName).AppendLine(" MapFromReader(DbDataReader reader)");
        sb.AppendLine("    {");
        sb.Append("        return new ").Append(table.TypeName).AppendLine();
        sb.AppendLine("        {");

        for (var i = 0; i < columns.Count; i++)
        {
            var col = columns[i];
            var ordinal = col.Ordinal;

            sb.Append("            ").Append(col.PropertyName).Append(" = ");
            EmitReaderAccess(sb, col, ordinal);

            if (i < columns.Count - 1)
                sb.Append(',');
            sb.AppendLine();
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitReaderAccess(StringBuilder sb, DuckDbColumnInfo col, int ordinal)
    {
        var baseType = col.PropertyType.TrimEnd('?');

        if (col.IsNullable)
        {
            switch (baseType)
            {
                case "string":
                    sb.Append("reader.Col(").Append(ordinal).Append(").AsString");
                    break;
                case "ulong":
                case "System.UInt64":
                    sb.Append("reader.Col(").Append(ordinal).Append(").AsUInt64");
                    break;
                case "long":
                case "System.Int64":
                    sb.Append("reader.Col(").Append(ordinal).Append(").AsInt64");
                    break;
                case "double":
                case "System.Double":
                    sb.Append("reader.Col(").Append(ordinal).Append(").AsDouble");
                    break;
                case "int":
                case "System.Int32":
                    sb.Append("reader.Col(").Append(ordinal).Append(").AsInt32");
                    break;
                case "byte":
                case "System.Byte":
                    sb.Append("reader.Col(").Append(ordinal).Append(").AsByte");
                    break;
                case "System.DateTimeOffset":
                case "DateTimeOffset":
                    sb.Append("reader.Col(").Append(ordinal).Append(").AsDateTimeOffset");
                    break;
                default:
                    sb.Append("reader.IsDBNull(").Append(ordinal).Append(") ? default : reader.GetValue(")
                        .Append(ordinal).Append(')');
                    break;
            }
        }
        else
        {
            switch (baseType)
            {
                case "string":
                    sb.Append("reader.Col(").Append(ordinal).Append(").GetString(\"\")");
                    break;
                case "ulong":
                case "System.UInt64":
                    sb.Append("reader.Col(").Append(ordinal).Append(").GetUInt64(0UL)");
                    break;
                case "long":
                case "System.Int64":
                    sb.Append("reader.Col(").Append(ordinal).Append(").GetInt64(0L)");
                    break;
                case "double":
                case "System.Double":
                    sb.Append("reader.Col(").Append(ordinal).Append(").GetDouble(0d)");
                    break;
                case "int":
                case "System.Int32":
                    sb.Append("reader.Col(").Append(ordinal).Append(").GetInt32(0)");
                    break;
                case "byte":
                case "System.Byte":
                    sb.Append("reader.Col(").Append(ordinal).Append(").GetByte(0)");
                    break;
                default:
                    sb.Append("reader.IsDBNull(").Append(ordinal).Append(") ? default : reader.GetValue(")
                        .Append(ordinal).Append(')');
                    break;
            }
        }
    }

    private static void EmitBuildMultiRowInsertSql(StringBuilder sb, DuckDbTableInfo table)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Builds a multi-row INSERT statement with positional parameters.");
        sb.AppendLine("    /// Example: INSERT INTO table (col1, col2) VALUES ($1, $2), ($3, $4)");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static string BuildMultiRowInsertSql(int rowCount)");
        sb.AppendLine("    {");
        sb.AppendLine("        var sb = new StringBuilder(1024);");
        sb.Append(
            "        sb.Append(\"INSERT INTO \").Append(TableName).Append(\" (\").Append(ColumnList).Append(\") VALUES \");");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("        for (var i = 0; i < rowCount; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (i > 0) sb.Append(\", \");");
        sb.AppendLine();
        sb.AppendLine("            var baseParam = i * ColumnCount;");
        sb.AppendLine("            sb.Append('(');");
        sb.AppendLine("            for (var col = 0; col < ColumnCount; col++)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (col > 0) sb.Append(\", \");");
        sb.AppendLine("                sb.Append('$').Append(baseParam + col + 1);");
        sb.AppendLine("            }");
        sb.AppendLine("            sb.Append(')');");
        sb.AppendLine("        }");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(table.OnConflict))
        {
            sb.AppendLine("        // ON CONFLICT clause for upsert behavior");
            sb.Append("        sb.Append(\" \").Append(\"\"\"");
            sb.AppendLine();
            sb.Append("            ").AppendLine(table.OnConflict);
            sb.AppendLine("            \"\"\");");
        }

        sb.AppendLine();
        sb.AppendLine("        return sb.ToString();");
        sb.AppendLine("    }");
    }
}
