using Microsoft.CodeAnalysis.CSharp;
using Qyl.Instrumentation.Generators.Models;

namespace Qyl.Instrumentation.Generators.Emitters;

/// <summary>
///     Emits interceptor source code for <c>IChatClient</c> call sites detected by
///     <see cref="Analyzers.ChatClientCallSiteAnalyzer" />.
/// </summary>
/// <remarks>
///     Each interceptor:
///     <list type="number">
///         <item>Calls <c>ToolInstrumentingChatClient.PrepareOptions(options)</c> to instrument any tools.</item>
///         <item>
///             Delegates through <c>GenAiInstrumentation.ExecuteAsync</c> /
///             <c>GenAiInstrumentation.ExecuteStreamingAsync</c> so a full OTel span is recorded with
///             <c>gen_ai.*</c> attributes.
///         </item>
///     </list>
/// </remarks>
internal static class ChatClientInterceptorEmitter
{
    public static string Emit(ImmutableArray<ChatClientCallSite> invocations)
    {
        if (invocations.IsEmpty)
            return string.Empty;

        var sb = new IndentedStringBuilder();

        sb.AppendLineNoIndent("// <auto-generated/>");
        sb.AppendLineNoIndent("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using qyl.contracts.Attributes;");
        sb.AppendLine("using Qyl.Instrumentation.Instrumentation;");
        sb.AppendLine("using Qyl.Instrumentation.Instrumentation.GenAi;");
        sb.AppendLine();

        EmitterHelpers.AppendInterceptsLocationAttribute(sb);

        using (sb.BeginNamespace("Qyl.Instrumentation.Generators"))
        using (sb.BeginClass("file static", "ChatClientInterceptors"))
        {
            var index = 0;
            foreach (var invocation in invocations.OrderBy(static i => i.SortKey, StringComparer.Ordinal))
            {
                if (invocation.IsStreaming)
                    AppendStreamingInterceptor(sb, invocation, index);
                else
                    AppendNonStreamingInterceptor(sb, invocation, index);
                index++;
            }
        }

        return sb.ToString();
    }

    private static void AppendNonStreamingInterceptor(
        IndentedStringBuilder sb,
        ChatClientCallSite invocation,
        int index)
    {
        var displayLocation = invocation.Location.GetDisplayLocation();
        var interceptAttribute = invocation.Location.GetInterceptsLocationAttributeSyntax();
        var methodName = $"Intercept_ChatClient_{index}";
        var returnType = invocation.ReturnTypeName;
        var originalMethod = invocation.MethodName;

        var parameters = EmitterHelpers.BuildParameterList(
            invocation.ContainingTypeName, invocation.ParameterTypes, invocation.ParameterNames);
        var arguments = BuildForwardArguments(invocation.ParameterNames);

        sb.AppendLine($"// Intercepted IChatClient call at {displayLocation}");
        sb.AppendLine(interceptAttribute);
        sb.AppendLine($"public static async {returnType} {methodName}({parameters})");
        using (sb.BeginBlock())
        {
            // Instrument tools in options before delegating
            sb.AppendLine("// Ensure any ChatOptions.Tools are wrapped for execute_tool spans");
            sb.AppendLine($"global::Qyl.Instrumentation.Instrumentation.GenAi.ChatClientExtensions.AddInstrumentedTools({GetOptionsArgument(invocation.ParameterNames)});");
            sb.AppendLine();

            sb.AppendLine($"return await global::Qyl.Instrumentation.Instrumentation.GenAi.GenAiInstrumentation.ExecuteAsync(");
            sb.AppendLine(@"    ""unknown"",");
            sb.AppendLine("    GenAiAttributes.Operations.Chat,");
            sb.AppendLine("    null,");
            sb.AppendLine($"    async () => await @this.{originalMethod}({arguments}).ConfigureAwait(false));");
        }

        sb.AppendLine();
    }

    private static void AppendStreamingInterceptor(
        IndentedStringBuilder sb,
        ChatClientCallSite invocation,
        int index)
    {
        var displayLocation = invocation.Location.GetDisplayLocation();
        var interceptAttribute = invocation.Location.GetInterceptsLocationAttributeSyntax();
        var methodName = $"Intercept_ChatClient_{index}";
        var returnType = invocation.ReturnTypeName;
        var originalMethod = invocation.MethodName;

        var parameters = EmitterHelpers.BuildParameterList(
            invocation.ContainingTypeName, invocation.ParameterTypes, invocation.ParameterNames);
        var arguments = BuildForwardArguments(invocation.ParameterNames);
        var elementType = ExtractStreamingElementType(returnType);

        sb.AppendLine($"// Intercepted IChatClient streaming call at {displayLocation}");
        sb.AppendLine(interceptAttribute);
        sb.AppendLine($"public static {returnType} {methodName}({parameters})");
        using (sb.BeginBlock())
        {
            sb.AppendLine("// Ensure any ChatOptions.Tools are wrapped for execute_tool spans");
            sb.AppendLine($"global::Qyl.Instrumentation.Instrumentation.GenAi.ChatClientExtensions.AddInstrumentedTools({GetOptionsArgument(invocation.ParameterNames)});");
            sb.AppendLine();

            sb.AppendLine($"return global::Qyl.Instrumentation.Instrumentation.GenAi.GenAiInstrumentation.ExecuteStreamingAsync<{elementType}>(");
            sb.AppendLine(@"    ""unknown"",");
            sb.AppendLine("    GenAiAttributes.Operations.Chat,");
            sb.AppendLine("    null,");
            sb.AppendLine($"    () => @this.{originalMethod}({arguments}));");
        }

        sb.AppendLine();
    }

    /// <summary>
    ///     Identifies the <c>options</c> parameter (ChatOptions?) and returns its name,
    ///     or <c>null</c> if not present.
    /// </summary>
    private static string GetOptionsArgument(EquatableArray<string> parameterNames)
    {
        // IChatClient methods: (messages, options, cancellationToken)
        // "options" is the conventional parameter name
        foreach (var name in parameterNames)
        {
            if (string.Equals(name, "options", StringComparison.Ordinal))
                return name;
        }

        return "null";
    }

    /// <summary>
    ///     Builds the argument list to forward to the original method,
    ///     keeping all parameter names as-is.
    /// </summary>
    private static string BuildForwardArguments(EquatableArray<string> parameterNames) =>
        parameterNames.Length is 0 ? string.Empty : string.Join(", ", parameterNames);

    private static string ExtractStreamingElementType(string returnType)
    {
        var start = returnType.IndexOf('<');
        var end = returnType.LastIndexOf('>');
        return start < 0 || end < 0 || end <= start ? "object" : returnType[(start + 1)..end];
    }
}
