// =============================================================================
// qyl.instrumentation.generators - Interceptor Code Emitter
// Generates C# interceptor code that wraps GenAI calls with OTel spans
// Owner: qyl.instrumentation.generators
// =============================================================================

using ANcpLua.Roslyn.Utilities;
using qyl.instrumentation.generators.Extractors;
using qyl.instrumentation.generators.Interceptors;

namespace qyl.instrumentation.generators.Emitters;

/// <summary>
///     Emits C# interceptor code that wraps method calls with OTel spans.
///     Uses qyl.protocol GenAiAttributes for semantic conventions.
/// </summary>
internal static class InterceptorEmitter
{
    public static string Emit(IEnumerable<InterceptorTarget> targets)
    {
        var sb = new StringBuilder();

        sb.AppendLine("""
                      // <auto-generated/>
                      // Generated by qyl.instrumentation.generators
                      //
                      // Interception = HOW you capture data (this code)
                      // Semantic conventions = WHAT you capture (qyl.protocol.GenAiAttributes)
                      //
                      // LIMITATIONS:
                      // - Cannot intercept interface calls
                      // - Cannot intercept virtual dispatch
                      // - Cannot intercept compiled packages
                      // - Only works on YOUR source code

                      #nullable enable

                      using System;
                      using System.Collections.Generic;
                      using System.Diagnostics;
                      using System.Linq;
                      using System.Runtime.CompilerServices;
                      using System.Threading.Tasks;
                      using qyl.protocol.Attributes;

                      namespace qyl.instrumentation.Generated;

                      /// <summary>
                      /// Auto-generated interceptors for GenAI SDK calls.
                      /// </summary>
                      [System.CodeDom.Compiler.GeneratedCode("qyl.instrumentation.generators", "1.0.0")]
                      file static class GenAiInterceptors
                      {
                          private static readonly ActivitySource Source = new(
                              "qyl.instrumentation.GenAi",
                              "1.0.0");

                      """);

        foreach (var target in targets)
        {
            EmitInterceptor(sb, target);
        }

        // Add the response extractor helper
        sb.AppendLine(ResponseExtractorSource.Source);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitInterceptor(StringBuilder sb, InterceptorTarget target)
    {
        var methodId = GetMethodId(target);
        var isTask = target.ReturnType.Contains("Task");
        var isVoid = target.ReturnType is "void" or "System.Void";

        sb.AppendLine($"""
                           /// <summary>Intercepts {target.ContainingType}.{target.MethodName}</summary>
                           [InterceptsLocation(@"{EscapePath(target.FilePath)}", {target.Line}, {target.Column})]
                       """);

        switch (isTask)
        {
            case true when !isVoid:
                EmitAsyncInterceptor(sb, target, methodId);
                break;
            case true:
                EmitAsyncTaskInterceptor(sb, target, methodId);
                break;
            default:
                EmitSyncInterceptor(sb, target, methodId);
                break;
        }
    }

    private static void EmitAsyncInterceptor(StringBuilder sb, InterceptorTarget target, string methodId)
    {
        var commonTagLines = BuildCommonTagLines(target);

        var source = $$"""
                            internal static async {{target.ReturnType}} {{methodId}}(
                                this {{target.ContainingType}} instance{{FormatParameters(target.Parameters)}})
                            {
                                using var activity = Source.StartActivity("{{target.SpanNameTemplate}}", ActivityKind.Client);

                                // OTel GenAI semantic conventions (gen_ai.*)
                                __COMMON_TAGS__

                                try
                                {
                                    var result = await instance.{{target.MethodName}}({{FormatArguments(target.Parameters)}}).ConfigureAwait(false);

                                    // Extract response attributes if available
                                    ExtractResponseAttributes(activity, result);

                                    activity?.SetStatus(ActivityStatusCode.Ok);
                                    return result;
                                }
                                catch (Exception ex)
                                {
                                    activity?.SetStatus(ActivityStatusCode.Error, ex.Message);
                                    activity?.RecordException(ex);
                                    throw;
                                }
                            }

                        """;

        sb.AppendLine(source.Replace("__COMMON_TAGS__", commonTagLines));
    }

    private static void EmitAsyncTaskInterceptor(StringBuilder sb, InterceptorTarget target, string methodId)
    {
        var commonTagLines = BuildCommonTagLines(target);

        var source = $$"""
                            internal static async Task {{methodId}}(
                                this {{target.ContainingType}} instance{{FormatParameters(target.Parameters)}})
                            {
                                using var activity = Source.StartActivity("{{target.SpanNameTemplate}}", ActivityKind.Client);

                                __COMMON_TAGS__

                                try
                                {
                                    await instance.{{target.MethodName}}({{FormatArguments(target.Parameters)}}).ConfigureAwait(false);
                                    activity?.SetStatus(ActivityStatusCode.Ok);
                                }
                                catch (Exception ex)
                                {
                                    activity?.SetStatus(ActivityStatusCode.Error, ex.Message);
                                    activity?.RecordException(ex);
                                    throw;
                                }
                            }

                        """;

        sb.AppendLine(source.Replace("__COMMON_TAGS__", commonTagLines));
    }

    private static void EmitSyncInterceptor(StringBuilder sb, InterceptorTarget target, string methodId)
    {
        var isVoid = target.ReturnType is "void" or "System.Void";
        var commonTagLines = BuildCommonTagLines(target);

        var source = $$"""
                            internal static {{target.ReturnType}} {{methodId}}(
                                this {{target.ContainingType}} instance{{FormatParameters(target.Parameters)}})
                            {
                                using var activity = Source.StartActivity("{{target.SpanNameTemplate}}", ActivityKind.Client);
                                __COMMON_TAGS__

                                try
                                {
                        """;

        sb.AppendLine(source.Replace("__COMMON_TAGS__", commonTagLines));

        sb.AppendLine(isVoid
            ? $"""
                           instance.{target.MethodName}({FormatArguments(target.Parameters)});
                           activity?.SetStatus(ActivityStatusCode.Ok);
               """
            : $"""
                           var result = instance.{target.MethodName}({FormatArguments(target.Parameters)});
                           ExtractResponseAttributes(activity, result);
                           activity?.SetStatus(ActivityStatusCode.Ok);
                           return result;
               """);

        sb.AppendLine("""
                              }
                              catch (Exception ex)
                              {
                                  activity?.SetStatus(ActivityStatusCode.Error, ex.Message);
                                  activity?.RecordException(ex);
                                  throw;
                              }
                          }

                      """);
    }

    private static string GetMethodId(InterceptorTarget target)
        => $"Intercept_{SanitizeIdentifier(target.ContainingType)}_{target.MethodName}_{target.Line}_{target.Column}";

    private static string SanitizeIdentifier(string name)
        => name.Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace(",", "_").Replace(" ", "");

    private static string EscapePath(string path)
        => path.Replace("\\", @"\\");

    private static string BuildCommonTagLines(InterceptorTarget target)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"                                activity?.SetTag(GenAiAttributes.ProviderName, \"{target.Provider}\");");
        sb.AppendLine($"                                activity?.SetTag(GenAiAttributes.OperationName, \"{target.Operation}\");");

        var outputType = GetDefaultOutputType(target.Operation);
        if (outputType is not null)
        {
            sb.AppendLine($"                                activity?.SetTag(GenAiAttributes.OutputType, \"{outputType}\");");
        }

        var requestChoiceCountArgs = FormatChoiceCountArguments(target.Parameters);
        if (requestChoiceCountArgs.Length > 0)
        {
            sb.AppendLine($"                                TrySetRequestChoiceCount(activity, {requestChoiceCountArgs});");
        }

        return sb.ToString().TrimEnd();
    }

    private static string? GetDefaultOutputType(string operation)
    {
        return operation switch
        {
            "chat" => "text",
            "generate_content" => "text",
            "invoke_agent" => "text",
            "text_completion" => "text",
            "embeddings" => "json",
            "image_generation" => "image",
            "speech" => "speech",
            _ => null
        };
    }

    private static string FormatChoiceCountArguments(EquatableArray<ParameterInfo> parameters)
    {
        if (parameters.Length is 0)
        {
            return string.Empty;
        }

        return string.Join(", ", parameters.Select(static p => $"(\"{p.Name}\", (object?)@{p.Name})"));
    }

    private static string FormatParameters(EquatableArray<ParameterInfo> parameters)
    {
        if (parameters.Length is 0) return "";
        return ", " + string.Join(", ", parameters.Select(static p => $"{p.Type} @{p.Name}"));
    }

    private static string FormatArguments(EquatableArray<ParameterInfo> parameters)
        => string.Join(", ", parameters.Select(static p => $"@{p.Name}"));
}
