// <auto-generated>
//     This code was generated by qyl.build (CSharpGenerator).
//     Do not edit this file manually - changes will be overwritten.
//
//     Source:    eng/build/Domain/CodeGen/QylSchema.cs
//     Generator: CSharpGenerator
//     Output:    Primitives/SessionId.g.cs
//     Generated: 2025-12-17T23:31:13.7117590Z
// </auto-generated>

#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace qyl.protocol.Primitives;

/// <summary>
/// Unique identifier for an AI conversation session
/// </summary>
public readonly partial struct SessionId : ISpanParsable<SessionId>, IEquatable<SessionId>, IComparable<SessionId>, IFormattable
{
    private readonly Guid _value;

    /// <summary>Creates a new <see cref="SessionId"/> from the underlying value.</summary>
    public SessionId(Guid value) => _value = value;

    /// <summary>Gets the underlying Guid value.</summary>
    public Guid Value => _value;

    /// <summary>Gets the default (empty) value.</summary>
    public static SessionId Empty => new(Guid.Empty);

    /// <summary>Implicitly converts to the underlying type.</summary>
    public static implicit operator Guid(SessionId value) => value._value;

    /// <summary>Explicitly converts from the underlying type.</summary>
    public static explicit operator SessionId(Guid value) => new(value);

    /// <inheritdoc/>
    public bool Equals(SessionId other) => _value.Equals(other._value);

    /// <inheritdoc/>
    public override bool Equals([NotNullWhen(true)] object? obj) => obj is SessionId other && Equals(other);

    /// <inheritdoc/>
    public override int GetHashCode() => _value.GetHashCode();

    /// <inheritdoc/>
    public int CompareTo(SessionId other) => _value.CompareTo(other._value);

    /// <summary>Equality operator.</summary>
    public static bool operator ==(SessionId left, SessionId right) => left.Equals(right);

    /// <summary>Inequality operator.</summary>
    public static bool operator !=(SessionId left, SessionId right) => !left.Equals(right);

    /// <inheritdoc/>
    public override string ToString() => _value.ToString("N");

    /// <inheritdoc/>
    public string ToString(string? format, IFormatProvider? formatProvider) => _value.ToString(format, formatProvider);

    /// <summary>Parses a span of characters into a <see cref="SessionId"/>.</summary>
    public static SessionId Parse(ReadOnlySpan<char> s, IFormatProvider? provider = null)
        => new(Guid.Parse(s));

    /// <summary>Tries to parse a span of characters into a <see cref="SessionId"/>.</summary>
    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out SessionId result)
    {
        if (Guid.TryParse(s, out var value))
        {
            result = new SessionId(value);
            return true;
        }
        result = Empty;
        return false;
    }

    /// <summary>Parses a string into a <see cref="SessionId"/>.</summary>
    public static SessionId Parse(string s, IFormatProvider? provider = null)
        => Parse(s.AsSpan(), provider);

    /// <summary>Tries to parse a string into a <see cref="SessionId"/>.</summary>
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out SessionId result)
    {
        if (s is null)
        {
            result = Empty;
            return false;
        }
        return TryParse(s.AsSpan(), provider, out result);
    }

    /// <summary>Returns true if this is the default/empty value.</summary>
    public bool IsEmpty => _value == Guid.Empty;

}
