// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e018fe6f91862f5ed63c082f87697cddac596784
// Schema: https://opentelemetry.io/schemas/1.41.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Cloudevents;

/// <summary>Cloudevents Attributes (incubating).</summary>
public static class CloudeventsAttributes
{
    /// <summary>The [event_id](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#id) uniquely identifies the event..</summary>
    public const string EventId = "cloudevents.event_id";

    /// <summary>The [source](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#source-1) identifies the context in which an event happened..</summary>
    public const string EventSource = "cloudevents.event_source";

    /// <summary>The [version of the CloudEvents specification](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#specversion) which the event uses..</summary>
    public const string EventSpecVersion = "cloudevents.event_spec_version";

    /// <summary>The [subject](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#subject) of the event in the context of the event producer (identified by source)..</summary>
    public const string EventSubject = "cloudevents.event_subject";

    /// <summary>The [event_type](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#type) contains a value describing the type of event related to the originating occurrence..</summary>
    public const string EventType = "cloudevents.event_type";

}