// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@7fe537301d17919af7d7eb65b32e9be35da2c497
// Schema: https://opentelemetry.io/schemas/1.40.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Webengine;

/// <summary>Webengine Attributes (incubating).</summary>
public static class WebengineAttributes
{
    /// <summary>Additional description of the web engine (e.g. detailed version and edition information)..</summary>
    public const string Description = "webengine.description";

    /// <summary>The name of the web engine..</summary>
    public const string Name = "webengine.name";

    /// <summary>The version of the web engine..</summary>
    public const string Version = "webengine.version";

}